// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const getAdminAccount = `-- name: GetAdminAccount :one
SELECT id, organization_id, authentik_sub, username, display_name, role, locale, last_login_at FROM admin_account WHERE id = $1
`

func (q *Queries) GetAdminAccount(ctx context.Context, id uuid.UUID) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getAdminAccount, id)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthentikSub,
		&i.Username,
		&i.DisplayName,
		&i.Role,
		&i.Locale,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminAccountBySubject = `-- name: GetAdminAccountBySubject :one
SELECT id, organization_id, authentik_sub, username, display_name, role, locale, last_login_at FROM admin_account WHERE authentik_sub = $1
`

func (q *Queries) GetAdminAccountBySubject(ctx context.Context, authentikSub string) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getAdminAccountBySubject, authentikSub)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthentikSub,
		&i.Username,
		&i.DisplayName,
		&i.Role,
		&i.Locale,
		&i.LastLoginAt,
	)
	return i, err
}

const getPlatformAdmin = `-- name: GetPlatformAdmin :one
SELECT id, authentik_sub, username, display_name, locale, last_login_at FROM platform_admin WHERE id = $1
`

func (q *Queries) GetPlatformAdmin(ctx context.Context, id uuid.UUID) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdmin, id)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.AuthentikSub,
		&i.Username,
		&i.DisplayName,
		&i.Locale,
		&i.LastLoginAt,
	)
	return i, err
}

const getPlatformAdminBySubject = `-- name: GetPlatformAdminBySubject :one
SELECT id, authentik_sub, username, display_name, locale, last_login_at FROM platform_admin WHERE authentik_sub = $1
`

func (q *Queries) GetPlatformAdminBySubject(ctx context.Context, authentikSub string) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminBySubject, authentikSub)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.AuthentikSub,
		&i.Username,
		&i.DisplayName,
		&i.Locale,
		&i.LastLoginAt,
	)
	return i, err
}

const updateAdminAccountLocale = `-- name: UpdateAdminAccountLocale :one
UPDATE admin_account SET locale = $1 WHERE id = $2 RETURNING id, organization_id, authentik_sub, username, display_name, role, locale, last_login_at
`

type UpdateAdminAccountLocaleParams struct {
	Locale string
	ID     uuid.UUID
}

func (q *Queries) UpdateAdminAccountLocale(ctx context.Context, arg UpdateAdminAccountLocaleParams) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, updateAdminAccountLocale, arg.Locale, arg.ID)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthentikSub,
		&i.Username,
		&i.DisplayName,
		&i.Role,
		&i.Locale,
		&i.LastLoginAt,
	)
	return i, err
}

const updatePlatformAdminLocale = `-- name: UpdatePlatformAdminLocale :one
UPDATE platform_admin SET locale = $1 WHERE id = $2 RETURNING id, authentik_sub, username, display_name, locale, last_login_at
`

type UpdatePlatformAdminLocaleParams struct {
	Locale string
	ID     uuid.UUID
}

func (q *Queries) UpdatePlatformAdminLocale(ctx context.Context, arg UpdatePlatformAdminLocaleParams) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, updatePlatformAdminLocale, arg.Locale, arg.ID)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.AuthentikSub,
		&i.Username,
		&i.DisplayName,
		&i.Locale,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertAdminAccount = `-- name: UpsertAdminAccount :one
INSERT INTO admin_account (id, organization_id, authentik_sub, username, display_name, role, last_login_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (authentik_sub) DO UPDATE
SET username = EXCLUDED.username, display_name = EXCLUDED.display_name, role = EXCLUDED.role, last_login_at = now()
RETURNING id, organization_id, authentik_sub, username, display_name, role, locale, last_login_at
`

type UpsertAdminAccountParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	AuthentikSub   string
	Username       string
	DisplayName    string
	Role           string
}

func (q *Queries) UpsertAdminAccount(ctx context.Context, arg UpsertAdminAccountParams) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, upsertAdminAccount,
		arg.ID,
		arg.OrganizationID,
		arg.AuthentikSub,
		arg.Username,
		arg.DisplayName,
		arg.Role,
	)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthentikSub,
		&i.Username,
		&i.DisplayName,
		&i.Role,
		&i.Locale,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertPlatformAdmin = `-- name: UpsertPlatformAdmin :one
INSERT INTO platform_admin (id, authentik_sub, username, display_name, last_login_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (authentik_sub) DO UPDATE
SET username = EXCLUDED.username, display_name = EXCLUDED.display_name, last_login_at = now()
RETURNING id, authentik_sub, username, display_name, locale, last_login_at
`

type UpsertPlatformAdminParams struct {
	ID           uuid.UUID
	AuthentikSub string
	Username     string
	DisplayName  string
}

func (q *Queries) UpsertPlatformAdmin(ctx context.Context, arg UpsertPlatformAdminParams) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, upsertPlatformAdmin,
		arg.ID,
		arg.AuthentikSub,
		arg.Username,
		arg.DisplayName,
	)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.AuthentikSub,
		&i.Username,
		&i.DisplayName,
		&i.Locale,
		&i.LastLoginAt,
	)
	return i, err
}
