// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bundle.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const insertBundle = `-- name: InsertBundle :exec
INSERT INTO bundle (device_id, version, organization_id, content_sha256, envelope_sha256, object_key)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertBundleParams struct {
	DeviceID       uuid.UUID
	Version        int64
	OrganizationID uuid.UUID
	ContentSha256  []byte
	EnvelopeSha256 []byte
	ObjectKey      string
}

func (q *Queries) InsertBundle(ctx context.Context, arg InsertBundleParams) error {
	_, err := q.db.Exec(ctx, insertBundle,
		arg.DeviceID,
		arg.Version,
		arg.OrganizationID,
		arg.ContentSha256,
		arg.EnvelopeSha256,
		arg.ObjectKey,
	)
	return err
}

const listActiveDeviceIDs = `-- name: ListActiveDeviceIDs :many

SELECT id FROM device WHERE state = 'active' ORDER BY id
`

// Compiler (plan M2a decision 13).
func (q *Queries) ListActiveDeviceIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveDeviceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveGroupMemberIDs = `-- name: ListActiveGroupMemberIDs :many
SELECT d.id FROM device d JOIN device_group_member m ON m.device_id = d.id
WHERE m.device_group_id = $1 AND d.state = 'active'
ORDER BY d.id
`

func (q *Queries) ListActiveGroupMemberIDs(ctx context.Context, deviceGroupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveGroupMemberIDs, deviceGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompileTargets = `-- name: ListCompileTargets :many
SELECT id, state, bundle_seq FROM device WHERE id = ANY($1::uuid[]) ORDER BY id
`

type ListCompileTargetsRow struct {
	ID        uuid.UUID
	State     string
	BundleSeq int64
}

func (q *Queries) ListCompileTargets(ctx context.Context, ids []uuid.UUID) ([]ListCompileTargetsRow, error) {
	rows, err := q.db.Query(ctx, listCompileTargets, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompileTargetsRow{}
	for rows.Next() {
		var i ListCompileTargetsRow
		if err := rows.Scan(&i.ID, &i.State, &i.BundleSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestBundles = `-- name: ListLatestBundles :many
SELECT DISTINCT ON (device_id) device_id, version, organization_id, content_sha256, envelope_sha256, object_key, created_at FROM bundle ORDER BY device_id, version DESC
`

func (q *Queries) ListLatestBundles(ctx context.Context) ([]Bundle, error) {
	rows, err := q.db.Query(ctx, listLatestBundles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bundle{}
	for rows.Next() {
		var i Bundle
		if err := rows.Scan(
			&i.DeviceID,
			&i.Version,
			&i.OrganizationID,
			&i.ContentSha256,
			&i.EnvelopeSha256,
			&i.ObjectKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceBundleSeq = `-- name: SetDeviceBundleSeq :execrows
UPDATE device SET bundle_seq = $1 WHERE id = $2 AND bundle_seq = $3
`

type SetDeviceBundleSeqParams struct {
	NewSeq int64
	ID     uuid.UUID
	OldSeq int64
}

// Optimistic: a concurrent compile of the same device makes this update no row.
func (q *Queries) SetDeviceBundleSeq(ctx context.Context, arg SetDeviceBundleSeqParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDeviceBundleSeq, arg.NewSeq, arg.ID, arg.OldSeq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
