// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_set.sql

package pgstore

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countChangeSets = `-- name: CountChangeSets :one
SELECT count(*) FROM (
  SELECT 1 FROM change_set
  WHERE ($1::text IS NULL OR actor->>'display' ILIKE $1::text ESCAPE '\')
    AND ($2::text[] IS NULL OR source = ANY($2::text[]))
  LIMIT $3
) matching
`

type CountChangeSetsParams struct {
	QPattern   *string
	Sources    []string
	CountLimit int32
}

func (q *Queries) CountChangeSets(ctx context.Context, arg CountChangeSetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChangeSets, arg.QPattern, arg.Sources, arg.CountLimit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChangeSet = `-- name: GetChangeSet :one
SELECT id, organization_id, applied_at, actor, source, created_n, updated_n, deleted_n, sections, plan FROM change_set WHERE id = $1
`

func (q *Queries) GetChangeSet(ctx context.Context, id uuid.UUID) (ChangeSet, error) {
	row := q.db.QueryRow(ctx, getChangeSet, id)
	var i ChangeSet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AppliedAt,
		&i.Actor,
		&i.Source,
		&i.CreatedN,
		&i.UpdatedN,
		&i.DeletedN,
		&i.Sections,
		&i.Plan,
	)
	return i, err
}

const insertChangeSet = `-- name: InsertChangeSet :exec
INSERT INTO change_set (id, organization_id, actor, source, created_n, updated_n, deleted_n, sections, plan)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertChangeSetParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Actor          json.RawMessage
	Source         string
	CreatedN       int32
	UpdatedN       int32
	DeletedN       int32
	Sections       []string
	Plan           json.RawMessage
}

func (q *Queries) InsertChangeSet(ctx context.Context, arg InsertChangeSetParams) error {
	_, err := q.db.Exec(ctx, insertChangeSet,
		arg.ID,
		arg.OrganizationID,
		arg.Actor,
		arg.Source,
		arg.CreatedN,
		arg.UpdatedN,
		arg.DeletedN,
		arg.Sections,
		arg.Plan,
	)
	return err
}

const listChangeSets = `-- name: ListChangeSets :many

SELECT id, organization_id, applied_at, actor, source, created_n, updated_n, deleted_n, sections, plan FROM change_set
WHERE ($1::text IS NULL OR actor->>'display' ILIKE $1::text ESCAPE '\')
  AND ($2::text[] IS NULL OR source = ANY($2::text[]))
ORDER BY
  CASE WHEN $3::text = 'applied_at' THEN applied_at END ASC,
  CASE WHEN $3::text = '-applied_at' THEN applied_at END DESC,
  id
LIMIT $5 OFFSET $4
`

type ListChangeSetsParams struct {
	QPattern *string
	Sources  []string
	Sort     string
	SkipRows int32
	MaxRows  int32
}

// List queries (ADR 0018): see device_group.sql.
func (q *Queries) ListChangeSets(ctx context.Context, arg ListChangeSetsParams) ([]ChangeSet, error) {
	rows, err := q.db.Query(ctx, listChangeSets,
		arg.QPattern,
		arg.Sources,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangeSet{}
	for rows.Next() {
		var i ChangeSet
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AppliedAt,
			&i.Actor,
			&i.Source,
			&i.CreatedN,
			&i.UpdatedN,
			&i.DeletedN,
			&i.Sections,
			&i.Plan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConfigApply = `-- name: LockConfigApply :exec

SELECT pg_advisory_xact_lock(hashtextextended('config_apply:' || current_setting('paddock.org_id'), 0))
`

// Change sets of the declarative configuration (plan M6c decision 17).
// Serializes the declarative applies and dry runs of the transaction's organization (PDK-016): two concurrent applies
// would otherwise take device group locks in different orders and deadlock. Released at the end of the transaction.
func (q *Queries) LockConfigApply(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockConfigApply)
	return err
}
