// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: command.sql

package pgstore

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countDeviceCommands = `-- name: CountDeviceCommands :one
SELECT count(*) FROM (
  SELECT 1 FROM device_command
  WHERE device_id = $1
    AND ($2::text IS NULL OR type ILIKE $2::text ESCAPE '\')
    AND ($3::text[] IS NULL OR status = ANY($3::text[]))
    AND ($4::text[] IS NULL OR type = ANY($4::text[]))
  LIMIT $5
) matching
`

type CountDeviceCommandsParams struct {
	DeviceID   uuid.UUID
	QPattern   *string
	Statuses   []string
	Types      []string
	CountLimit int32
}

func (q *Queries) CountDeviceCommands(ctx context.Context, arg CountDeviceCommandsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeviceCommands,
		arg.DeviceID,
		arg.QPattern,
		arg.Statuses,
		arg.Types,
		arg.CountLimit,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const expireDeviceCommands = `-- name: ExpireDeviceCommands :many
UPDATE device_command SET status = 'expired', finished_at = $1::timestamptz
WHERE status IN ('pending','delivered') AND expires_at <= $1::timestamptz
RETURNING id, device_id
`

type ExpireDeviceCommandsRow struct {
	ID       uuid.UUID
	DeviceID uuid.UUID
}

func (q *Queries) ExpireDeviceCommands(ctx context.Context, now time.Time) ([]ExpireDeviceCommandsRow, error) {
	rows, err := q.db.Query(ctx, expireDeviceCommands, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireDeviceCommandsRow{}
	for rows.Next() {
		var i ExpireDeviceCommandsRow
		if err := rows.Scan(&i.ID, &i.DeviceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishDeviceCommand = `-- name: FinishDeviceCommand :execrows
UPDATE device_command SET status = $1, result = $2, finished_at = $3::timestamptz,
  delivered_at = coalesce(delivered_at, $3::timestamptz)
WHERE id = $4 AND device_id = $5 AND status IN ('pending','delivered')
`

type FinishDeviceCommandParams struct {
	Status     string
	Result     json.RawMessage
	FinishedAt time.Time
	ID         uuid.UUID
	DeviceID   uuid.UUID
}

// The first result counts; a command that is already finished or expired keeps its state.
func (q *Queries) FinishDeviceCommand(ctx context.Context, arg FinishDeviceCommandParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishDeviceCommand,
		arg.Status,
		arg.Result,
		arg.FinishedAt,
		arg.ID,
		arg.DeviceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeviceCommand = `-- name: GetDeviceCommand :one
SELECT id, organization_id, device_id, type, params, status, issued_by, issued_at, expires_at, not_before, delivered_at, finished_at, result FROM device_command WHERE id = $1
`

func (q *Queries) GetDeviceCommand(ctx context.Context, id uuid.UUID) (DeviceCommand, error) {
	row := q.db.QueryRow(ctx, getDeviceCommand, id)
	var i DeviceCommand
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.Type,
		&i.Params,
		&i.Status,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.NotBefore,
		&i.DeliveredAt,
		&i.FinishedAt,
		&i.Result,
	)
	return i, err
}

const insertDeviceCommand = `-- name: InsertDeviceCommand :one

INSERT INTO device_command (id, organization_id, device_id, type, params, status, issued_by, issued_at, expires_at, not_before)
VALUES ($1, $2, $3, $4, $5, 'pending', $6, $7, $8,
        $9)
RETURNING id, organization_id, device_id, type, params, status, issued_by, issued_at, expires_at, not_before, delivered_at, finished_at, result
`

type InsertDeviceCommandParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	Type           string
	Params         json.RawMessage
	IssuedBy       uuid.NullUUID
	IssuedAt       time.Time
	ExpiresAt      time.Time
	NotBefore      *time.Time
}

// Device commands (plan M4a decisions 1–3).
func (q *Queries) InsertDeviceCommand(ctx context.Context, arg InsertDeviceCommandParams) (DeviceCommand, error) {
	row := q.db.QueryRow(ctx, insertDeviceCommand,
		arg.ID,
		arg.OrganizationID,
		arg.DeviceID,
		arg.Type,
		arg.Params,
		arg.IssuedBy,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.NotBefore,
	)
	var i DeviceCommand
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.Type,
		&i.Params,
		&i.Status,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.NotBefore,
		&i.DeliveredAt,
		&i.FinishedAt,
		&i.Result,
	)
	return i, err
}

const listDeviceCommands = `-- name: ListDeviceCommands :many

SELECT id, organization_id, device_id, type, params, status, issued_by, issued_at, expires_at, not_before, delivered_at, finished_at, result FROM device_command
WHERE device_id = $1
  AND ($2::text IS NULL OR type ILIKE $2::text ESCAPE '\')
  AND ($3::text[] IS NULL OR status = ANY($3::text[]))
  AND ($4::text[] IS NULL OR type = ANY($4::text[]))
ORDER BY
  CASE WHEN $5::text = 'issued_at' THEN issued_at END ASC,
  CASE WHEN $5::text = '-issued_at' THEN issued_at END DESC,
  CASE WHEN $5::text = 'expires_at' THEN expires_at END ASC,
  CASE WHEN $5::text = '-expires_at' THEN expires_at END DESC,
  CASE WHEN $5::text = 'type' THEN type END ASC,
  CASE WHEN $5::text = '-type' THEN type END DESC,
  CASE WHEN $5::text = 'status' THEN status END ASC,
  CASE WHEN $5::text = '-status' THEN status END DESC,
  id
LIMIT $7 OFFSET $6
`

type ListDeviceCommandsParams struct {
	DeviceID uuid.UUID
	QPattern *string
	Statuses []string
	Types    []string
	Sort     string
	SkipRows int32
	MaxRows  int32
}

// List queries (ADR 0018): see device_group.sql.
func (q *Queries) ListDeviceCommands(ctx context.Context, arg ListDeviceCommandsParams) ([]DeviceCommand, error) {
	rows, err := q.db.Query(ctx, listDeviceCommands,
		arg.DeviceID,
		arg.QPattern,
		arg.Statuses,
		arg.Types,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceCommand{}
	for rows.Next() {
		var i DeviceCommand
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeviceID,
			&i.Type,
			&i.Params,
			&i.Status,
			&i.IssuedBy,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.NotBefore,
			&i.DeliveredAt,
			&i.FinishedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDeviceCommands = `-- name: ListDueDeviceCommands :many
SELECT id, organization_id, device_id, type, params, status, issued_by, issued_at, expires_at, not_before, delivered_at, finished_at, result FROM device_command
WHERE status IN ('pending','delivered') AND expires_at > $1 AND (not_before IS NULL OR not_before <= $1)
ORDER BY issued_at, id
`

// Open commands that are due and not expired: the worker makes sure each one is in cmd:<device_id>.
func (q *Queries) ListDueDeviceCommands(ctx context.Context, now time.Time) ([]DeviceCommand, error) {
	rows, err := q.db.Query(ctx, listDueDeviceCommands, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceCommand{}
	for rows.Next() {
		var i DeviceCommand
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeviceID,
			&i.Type,
			&i.Params,
			&i.Status,
			&i.IssuedBy,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.NotBefore,
			&i.DeliveredAt,
			&i.FinishedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviceCommandsDelivered = `-- name: MarkDeviceCommandsDelivered :execrows
UPDATE device_command SET status = 'delivered', delivered_at = $1::timestamptz
WHERE device_id = $2 AND id = ANY($3::uuid[]) AND status = 'pending'
`

type MarkDeviceCommandsDeliveredParams struct {
	DeliveredAt time.Time
	DeviceID    uuid.UUID
	Ids         []uuid.UUID
}

func (q *Queries) MarkDeviceCommandsDelivered(ctx context.Context, arg MarkDeviceCommandsDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDeviceCommandsDelivered, arg.DeliveredAt, arg.DeviceID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
