// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_group.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const deleteDeviceGroup = `-- name: DeleteDeviceGroup :execrows
DELETE FROM device_group WHERE id = $1
`

func (q *Queries) DeleteDeviceGroup(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeviceGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeviceGroup = `-- name: GetDeviceGroup :one
SELECT id, organization_id, name, description, created_at, updated_at FROM device_group WHERE id = $1
`

func (q *Queries) GetDeviceGroup(ctx context.Context, id uuid.UUID) (DeviceGroup, error) {
	row := q.db.QueryRow(ctx, getDeviceGroup, id)
	var i DeviceGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDeviceGroup = `-- name: InsertDeviceGroup :one
INSERT INTO device_group (id, organization_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, name, description, created_at, updated_at
`

type InsertDeviceGroupParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    string
}

func (q *Queries) InsertDeviceGroup(ctx context.Context, arg InsertDeviceGroupParams) (DeviceGroup, error) {
	row := q.db.QueryRow(ctx, insertDeviceGroup,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
	)
	var i DeviceGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceGroups = `-- name: ListDeviceGroups :many
SELECT id, organization_id, name, description, created_at, updated_at FROM device_group
WHERE ($1::uuid IS NULL OR id < $1::uuid)
ORDER BY id DESC
LIMIT $2
`

type ListDeviceGroupsParams struct {
	Before  uuid.NullUUID
	MaxRows int32
}

func (q *Queries) ListDeviceGroups(ctx context.Context, arg ListDeviceGroupsParams) ([]DeviceGroup, error) {
	rows, err := q.db.Query(ctx, listDeviceGroups, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceGroup{}
	for rows.Next() {
		var i DeviceGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceGroup = `-- name: UpdateDeviceGroup :one
UPDATE device_group SET name = $1, description = $2, updated_at = now()
WHERE id = $3
RETURNING id, organization_id, name, description, created_at, updated_at
`

type UpdateDeviceGroupParams struct {
	Name        string
	Description string
	ID          uuid.UUID
}

func (q *Queries) UpdateDeviceGroup(ctx context.Context, arg UpdateDeviceGroupParams) (DeviceGroup, error) {
	row := q.db.QueryRow(ctx, updateDeviceGroup, arg.Name, arg.Description, arg.ID)
	var i DeviceGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
