// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device.sql

package pgstore

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countDevices = `-- name: CountDevices :one
SELECT count(*) FROM (
  SELECT 1 FROM device LEFT JOIN device_status ON device_status.device_id = device.id
  WHERE ($1::text IS NULL
         OR hostname ILIKE $1::text ESCAPE '\'
         OR hardware_uuid ILIKE $1::text ESCAPE '\')
    AND ($2::text[] IS NULL OR state = ANY($2::text[]))
    AND ($3::text[] IS NULL OR device_status.health -> 'disk' ->> 'state' = ANY($3::text[]))
    AND ($4::uuid IS NULL OR EXISTS (
          SELECT 1 FROM device_group_member m
          WHERE m.device_id = device.id AND m.device_group_id = $4::uuid))
  LIMIT $5
) matching
`

type CountDevicesParams struct {
	QPattern      *string
	States        []string
	DiskStates    []string
	DeviceGroupID uuid.NullUUID
	CountLimit    int32
}

func (q *Queries) CountDevices(ctx context.Context, arg CountDevicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDevices,
		arg.QPattern,
		arg.States,
		arg.DiskStates,
		arg.DeviceGroupID,
		arg.CountLimit,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeviceGroupMember = `-- name: DeleteDeviceGroupMember :exec
DELETE FROM device_group_member WHERE device_group_id = $1 AND device_id = $2
`

type DeleteDeviceGroupMemberParams struct {
	DeviceGroupID uuid.UUID
	DeviceID      uuid.UUID
}

func (q *Queries) DeleteDeviceGroupMember(ctx context.Context, arg DeleteDeviceGroupMemberParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceGroupMember, arg.DeviceGroupID, arg.DeviceID)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, organization_id, hostname, state, bundle_seq, hardware_uuid, machine_id, os_release, enrollment_token_id, enrolled_at, state_changed_at, logins_suspended FROM device WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Hostname,
		&i.State,
		&i.BundleSeq,
		&i.HardwareUuid,
		&i.MachineID,
		&i.OsRelease,
		&i.EnrollmentTokenID,
		&i.EnrolledAt,
		&i.StateChangedAt,
		&i.LoginsSuspended,
	)
	return i, err
}

const getDeviceIdentityKey = `-- name: GetDeviceIdentityKey :one
SELECT key_id, organization_id, device_id, public_key, key_protection, status, created_at FROM device_identity_key WHERE key_id = $1
`

func (q *Queries) GetDeviceIdentityKey(ctx context.Context, keyID string) (DeviceIdentityKey, error) {
	row := q.db.QueryRow(ctx, getDeviceIdentityKey, keyID)
	var i DeviceIdentityKey
	err := row.Scan(
		&i.KeyID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.PublicKey,
		&i.KeyProtection,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceStatus = `-- name: GetDeviceStatus :one
SELECT device_id, organization_id, last_contact_at, applied_bundle_version, agent_version, last_seq, health, schema_versions, login_state, presumed_self_locked_at, presumed_lost_at FROM device_status WHERE device_id = $1
`

func (q *Queries) GetDeviceStatus(ctx context.Context, deviceID uuid.UUID) (DeviceStatus, error) {
	row := q.db.QueryRow(ctx, getDeviceStatus, deviceID)
	var i DeviceStatus
	err := row.Scan(
		&i.DeviceID,
		&i.OrganizationID,
		&i.LastContactAt,
		&i.AppliedBundleVersion,
		&i.AgentVersion,
		&i.LastSeq,
		&i.Health,
		&i.SchemaVersions,
		&i.LoginState,
		&i.PresumedSelfLockedAt,
		&i.PresumedLostAt,
	)
	return i, err
}

const getLatestBundle = `-- name: GetLatestBundle :one
SELECT device_id, version, organization_id, content_sha256, envelope_sha256, object_key, created_at, schema_version FROM bundle WHERE device_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestBundle(ctx context.Context, deviceID uuid.UUID) (Bundle, error) {
	row := q.db.QueryRow(ctx, getLatestBundle, deviceID)
	var i Bundle
	err := row.Scan(
		&i.DeviceID,
		&i.Version,
		&i.OrganizationID,
		&i.ContentSha256,
		&i.EnvelopeSha256,
		&i.ObjectKey,
		&i.CreatedAt,
		&i.SchemaVersion,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO device (id, organization_id, hostname, state, hardware_uuid, machine_id, os_release, enrollment_token_id)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8)
RETURNING id, organization_id, hostname, state, bundle_seq, hardware_uuid, machine_id, os_release, enrollment_token_id, enrolled_at, state_changed_at, logins_suspended
`

type InsertDeviceParams struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	Hostname          string
	State             string
	HardwareUuid      *string
	MachineID         *string
	OsRelease         json.RawMessage
	EnrollmentTokenID uuid.NullUUID
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, insertDevice,
		arg.ID,
		arg.OrganizationID,
		arg.Hostname,
		arg.State,
		arg.HardwareUuid,
		arg.MachineID,
		arg.OsRelease,
		arg.EnrollmentTokenID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Hostname,
		&i.State,
		&i.BundleSeq,
		&i.HardwareUuid,
		&i.MachineID,
		&i.OsRelease,
		&i.EnrollmentTokenID,
		&i.EnrolledAt,
		&i.StateChangedAt,
		&i.LoginsSuspended,
	)
	return i, err
}

const insertDeviceGroupMember = `-- name: InsertDeviceGroupMember :exec
INSERT INTO device_group_member (organization_id, device_group_id, device_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertDeviceGroupMemberParams struct {
	OrganizationID uuid.UUID
	DeviceGroupID  uuid.UUID
	DeviceID       uuid.UUID
}

func (q *Queries) InsertDeviceGroupMember(ctx context.Context, arg InsertDeviceGroupMemberParams) error {
	_, err := q.db.Exec(ctx, insertDeviceGroupMember, arg.OrganizationID, arg.DeviceGroupID, arg.DeviceID)
	return err
}

const insertDeviceIdentityKey = `-- name: InsertDeviceIdentityKey :exec
INSERT INTO device_identity_key (key_id, organization_id, device_id, public_key, key_protection, status)
VALUES ($1, $2, $3, $4, $5, 'active')
`

type InsertDeviceIdentityKeyParams struct {
	KeyID          string
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	PublicKey      []byte
	KeyProtection  string
}

func (q *Queries) InsertDeviceIdentityKey(ctx context.Context, arg InsertDeviceIdentityKeyParams) error {
	_, err := q.db.Exec(ctx, insertDeviceIdentityKey,
		arg.KeyID,
		arg.OrganizationID,
		arg.DeviceID,
		arg.PublicKey,
		arg.KeyProtection,
	)
	return err
}

const listCachedDeviceKeys = `-- name: ListCachedDeviceKeys :many
SELECT k.key_id, k.public_key, k.status AS key_status, d.id AS device_id, d.state
FROM device_identity_key k JOIN device d ON d.id = k.device_id
WHERE d.state <> 'pending' AND ($1::uuid IS NULL OR d.id = $1::uuid)
ORDER BY k.key_id
`

type ListCachedDeviceKeysRow struct {
	KeyID     string
	PublicKey []byte
	KeyStatus string
	DeviceID  uuid.UUID
	State     string
}

// Worker cache sync: identity keys with the state of their device; pending devices are not cached (plan M2a
// decision 10).
func (q *Queries) ListCachedDeviceKeys(ctx context.Context, deviceID uuid.NullUUID) ([]ListCachedDeviceKeysRow, error) {
	rows, err := q.db.Query(ctx, listCachedDeviceKeys, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCachedDeviceKeysRow{}
	for rows.Next() {
		var i ListCachedDeviceKeysRow
		if err := rows.Scan(
			&i.KeyID,
			&i.PublicKey,
			&i.KeyStatus,
			&i.DeviceID,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceGroupIDsOfDevice = `-- name: ListDeviceGroupIDsOfDevice :many
SELECT device_group_id FROM device_group_member WHERE device_id = $1 ORDER BY device_group_id
`

func (q *Queries) ListDeviceGroupIDsOfDevice(ctx context.Context, deviceID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDeviceGroupIDsOfDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var device_group_id uuid.UUID
		if err := rows.Scan(&device_group_id); err != nil {
			return nil, err
		}
		items = append(items, device_group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceGroupsOfDevice = `-- name: ListDeviceGroupsOfDevice :many
SELECT g.id, g.name FROM device_group_member m JOIN device_group g ON g.id = m.device_group_id
WHERE m.device_id = $1
ORDER BY g.name, g.id
`

type ListDeviceGroupsOfDeviceRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListDeviceGroupsOfDevice(ctx context.Context, deviceID uuid.UUID) ([]ListDeviceGroupsOfDeviceRow, error) {
	rows, err := q.db.Query(ctx, listDeviceGroupsOfDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceGroupsOfDeviceRow{}
	for rows.Next() {
		var i ListDeviceGroupsOfDeviceRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceIdentityKeys = `-- name: ListDeviceIdentityKeys :many
SELECT key_id, organization_id, device_id, public_key, key_protection, status, created_at FROM device_identity_key WHERE device_id = $1 ORDER BY created_at, key_id
`

func (q *Queries) ListDeviceIdentityKeys(ctx context.Context, deviceID uuid.UUID) ([]DeviceIdentityKey, error) {
	rows, err := q.db.Query(ctx, listDeviceIdentityKeys, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceIdentityKey{}
	for rows.Next() {
		var i DeviceIdentityKey
		if err := rows.Scan(
			&i.KeyID,
			&i.OrganizationID,
			&i.DeviceID,
			&i.PublicKey,
			&i.KeyProtection,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many

SELECT device.id, device.organization_id, device.hostname, device.state, device.bundle_seq, device.hardware_uuid, device.machine_id, device.os_release, device.enrollment_token_id, device.enrolled_at, device.state_changed_at, device.logins_suspended, device_status.last_contact_at, device_status.applied_bundle_version,
       device_status.agent_version, coalesce(device_status.health -> 'disk' ->> 'state', '')::text AS disk_state -- '' = none
FROM device LEFT JOIN device_status ON device_status.device_id = device.id
WHERE ($1::text IS NULL
       OR hostname ILIKE $1::text ESCAPE '\'
       OR hardware_uuid ILIKE $1::text ESCAPE '\')
  AND ($2::text[] IS NULL OR state = ANY($2::text[]))
  AND ($3::text[] IS NULL OR device_status.health -> 'disk' ->> 'state' = ANY($3::text[]))
  AND ($4::uuid IS NULL OR EXISTS (
        SELECT 1 FROM device_group_member m
        WHERE m.device_id = device.id AND m.device_group_id = $4::uuid))
ORDER BY
  CASE WHEN $5::text = 'hostname' THEN hostname END ASC,
  CASE WHEN $5::text = '-hostname' THEN hostname END DESC,
  CASE WHEN $5::text = 'last_contact_at' THEN last_contact_at END ASC,
  CASE WHEN $5::text = '-last_contact_at' THEN last_contact_at END DESC,
  CASE WHEN $5::text = 'enrolled_at' THEN enrolled_at END ASC,
  CASE WHEN $5::text = '-enrolled_at' THEN enrolled_at END DESC,
  CASE WHEN $5::text = 'state' THEN state END ASC,
  CASE WHEN $5::text = '-state' THEN state END DESC,
  id
LIMIT $7 OFFSET $6
`

type ListDevicesParams struct {
	QPattern      *string
	States        []string
	DiskStates    []string
	DeviceGroupID uuid.NullUUID
	Sort          string
	SkipRows      int32
	MaxRows       int32
}

type ListDevicesRow struct {
	Device               Device
	LastContactAt        *time.Time
	AppliedBundleVersion *int64
	AgentVersion         *string
	DiskState            string
}

// List queries (ADR 0018): see device_group.sql. Sort and search columns are unambiguous across the join.
func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]ListDevicesRow, error) {
	rows, err := q.db.Query(ctx, listDevices,
		arg.QPattern,
		arg.States,
		arg.DiskStates,
		arg.DeviceGroupID,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesRow{}
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(
			&i.Device.ID,
			&i.Device.OrganizationID,
			&i.Device.Hostname,
			&i.Device.State,
			&i.Device.BundleSeq,
			&i.Device.HardwareUuid,
			&i.Device.MachineID,
			&i.Device.OsRelease,
			&i.Device.EnrollmentTokenID,
			&i.Device.EnrolledAt,
			&i.Device.StateChangedAt,
			&i.Device.LoginsSuspended,
			&i.LastContactAt,
			&i.AppliedBundleVersion,
			&i.AgentVersion,
			&i.DiskState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDevice = `-- name: LockDevice :one
SELECT id, organization_id, hostname, state, bundle_seq, hardware_uuid, machine_id, os_release, enrollment_token_id, enrolled_at, state_changed_at, logins_suspended FROM device WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockDevice(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, lockDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Hostname,
		&i.State,
		&i.BundleSeq,
		&i.HardwareUuid,
		&i.MachineID,
		&i.OsRelease,
		&i.EnrollmentTokenID,
		&i.EnrolledAt,
		&i.StateChangedAt,
		&i.LoginsSuspended,
	)
	return i, err
}

const revokeDeviceIdentityKeys = `-- name: RevokeDeviceIdentityKeys :exec
UPDATE device_identity_key SET status = 'revoked' WHERE device_id = $1 AND status = 'active'
`

func (q *Queries) RevokeDeviceIdentityKeys(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeDeviceIdentityKeys, deviceID)
	return err
}

const setDeviceState = `-- name: SetDeviceState :one
UPDATE device SET state = $1, state_changed_at = now()
WHERE id = $2 AND state = $3
RETURNING id, organization_id, hostname, state, bundle_seq, hardware_uuid, machine_id, os_release, enrollment_token_id, enrolled_at, state_changed_at, logins_suspended
`

type SetDeviceStateParams struct {
	State     string
	ID        uuid.UUID
	FromState string
}

func (q *Queries) SetDeviceState(ctx context.Context, arg SetDeviceStateParams) (Device, error) {
	row := q.db.QueryRow(ctx, setDeviceState, arg.State, arg.ID, arg.FromState)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Hostname,
		&i.State,
		&i.BundleSeq,
		&i.HardwareUuid,
		&i.MachineID,
		&i.OsRelease,
		&i.EnrollmentTokenID,
		&i.EnrolledAt,
		&i.StateChangedAt,
		&i.LoginsSuspended,
	)
	return i, err
}
