// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_status.sql

package pgstore

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertDeviceEventSeen = `-- name: InsertDeviceEventSeen :execrows
INSERT INTO device_event_seen (device_id, event_seq, organization_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertDeviceEventSeenParams struct {
	DeviceID       uuid.UUID
	EventSeq       int64
	OrganizationID uuid.UUID
}

// Device events are deduplicated by (device_id, event_seq) (plan M2a decision 14).
func (q *Queries) InsertDeviceEventSeen(ctx context.Context, arg InsertDeviceEventSeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDeviceEventSeen, arg.DeviceID, arg.EventSeq, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDeviceSeqs = `-- name: ListDeviceSeqs :many
SELECT device_id, last_seq FROM device_status WHERE last_seq > 0 ORDER BY device_id
`

type ListDeviceSeqsRow struct {
	DeviceID uuid.UUID
	LastSeq  int64
}

func (q *Queries) ListDeviceSeqs(ctx context.Context) ([]ListDeviceSeqsRow, error) {
	rows, err := q.db.Query(ctx, listDeviceSeqs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceSeqsRow{}
	for rows.Next() {
		var i ListDeviceSeqsRow
		if err := rows.Scan(&i.DeviceID, &i.LastSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceLoginState = `-- name: SetDeviceLoginState :exec
INSERT INTO device_status (device_id, organization_id, login_state)
VALUES ($1, $2, jsonb_build_object($3::text, $4::jsonb))
ON CONFLICT (device_id) DO UPDATE
SET login_state = device_status.login_state || jsonb_build_object($3::text, $4::jsonb)
WHERE (device_status.login_state -> $3::text) IS NULL
   OR (device_status.login_state -> $3::text ->> 'occurred_at')::timestamptz <= ($4::jsonb ->> 'occurred_at')::timestamptz
`

type SetDeviceLoginStateParams struct {
	DeviceID       uuid.UUID
	OrganizationID uuid.UUID
	Area           string
	State          json.RawMessage
}

// The latest login.* or sudo.* event of a device per area (plan M3b decision 17); an older event never overwrites a
// newer one. A device whose heartbeat was not materialized yet gets its status row here.
func (q *Queries) SetDeviceLoginState(ctx context.Context, arg SetDeviceLoginStateParams) error {
	_, err := q.db.Exec(ctx, setDeviceLoginState,
		arg.DeviceID,
		arg.OrganizationID,
		arg.Area,
		arg.State,
	)
	return err
}

const upsertDeviceStatus = `-- name: UpsertDeviceStatus :exec
INSERT INTO device_status (device_id, organization_id, last_contact_at, applied_bundle_version, agent_version, last_seq, health,
                           schema_versions)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8)
ON CONFLICT (device_id) DO UPDATE
SET last_contact_at = EXCLUDED.last_contact_at, applied_bundle_version = EXCLUDED.applied_bundle_version,
    agent_version = EXCLUDED.agent_version, last_seq = greatest(device_status.last_seq, EXCLUDED.last_seq),
    health = EXCLUDED.health, schema_versions = EXCLUDED.schema_versions
WHERE device_status.last_contact_at IS NULL OR device_status.last_contact_at <= EXCLUDED.last_contact_at
`

type UpsertDeviceStatusParams struct {
	DeviceID             uuid.UUID
	OrganizationID       uuid.UUID
	LastContactAt        *time.Time
	AppliedBundleVersion *int64
	AgentVersion         *string
	LastSeq              int64
	Health               json.RawMessage
	SchemaVersions       []int32
}

// Worker heartbeat materialization (plan M2a decision 12); an older heartbeat never overwrites a newer one.
func (q *Queries) UpsertDeviceStatus(ctx context.Context, arg UpsertDeviceStatusParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceStatus,
		arg.DeviceID,
		arg.OrganizationID,
		arg.LastContactAt,
		arg.AppliedBundleVersion,
		arg.AgentVersion,
		arg.LastSeq,
		arg.Health,
		arg.SchemaVersions,
	)
	return err
}
