// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dms.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelSelfLocks = `-- name: CancelSelfLocks :many
UPDATE revocation_request r SET status = 'cancelled', finished_at = $1::timestamptz
WHERE r.action = 'self_lock' AND r.status IN ('issued','delivered')
  AND (NOT $2::boolean OR r.period_days <> $3::int OR r.expires_at <= $4::timestamptz
       OR NOT EXISTS (SELECT 1 FROM device d WHERE d.id = r.device_id AND d.state = 'active')
       OR r.volumes <> CASE
         WHEN coalesce((SELECT (s.health -> 'revoke_capabilities') ? 'volumes' FROM device_status s
                        WHERE s.device_id = r.device_id), false)
         THEN ARRAY(SELECT DISTINCT e.volume FROM escrow_secret e
                    WHERE e.device_id = r.device_id AND e.kind = 'luks_header' AND e.status = 'stored'
                      AND e.volume IS NOT NULL ORDER BY 1)
         ELSE '{}'::uuid[] END)
RETURNING r.id, r.device_id
`

type CancelSelfLocksParams struct {
	Now         time.Time
	Enabled     bool
	PeriodDays  int32
	RenewBefore time.Time
}

type CancelSelfLocksRow struct {
	ID       uuid.UUID
	DeviceID uuid.UUID
}

// Open self-lock tokens that no longer fit the settings: all of them when the switch is off, otherwise those of
// another period, of a device that is no longer active, expiring before renew_before, or whose volumes differ from the
// device's volumes with a confirmed header escrow (PDK-009; they are replaced). A device whose paddock-revoke does
// not understand volumes keeps a token without them.
func (q *Queries) CancelSelfLocks(ctx context.Context, arg CancelSelfLocksParams) ([]CancelSelfLocksRow, error) {
	rows, err := q.db.Query(ctx, cancelSelfLocks,
		arg.Now,
		arg.Enabled,
		arg.PeriodDays,
		arg.RenewBefore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelSelfLocksRow{}
	for rows.Next() {
		var i CancelSelfLocksRow
		if err := rows.Scan(&i.ID, &i.DeviceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearPresumedSelfLocked = `-- name: ClearPresumedSelfLocked :execrows
UPDATE device_status SET presumed_self_locked_at = NULL
WHERE presumed_self_locked_at IS NOT NULL AND (last_contact_at >= $1::timestamptz OR NOT $2::boolean)
`

type ClearPresumedSelfLockedParams struct {
	SilentSince time.Time
	Enabled     bool
}

func (q *Queries) ClearPresumedSelfLocked(ctx context.Context, arg ClearPresumedSelfLockedParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearPresumedSelfLocked, arg.SilentSince, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDMSSettings = `-- name: GetDMSSettings :one

SELECT organization_id, enabled, period_days, warn_days, updated_at, updated_by FROM organization_dms_settings
`

// Dead man's switch (plan M4c decisions 15–17). Without a row the switch is off with the defaults.
func (q *Queries) GetDMSSettings(ctx context.Context) (OrganizationDmsSetting, error) {
	row := q.db.QueryRow(ctx, getDMSSettings)
	var i OrganizationDmsSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.Enabled,
		&i.PeriodDays,
		&i.WarnDays,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listDevicesWithoutSelfLock = `-- name: ListDevicesWithoutSelfLock :many
SELECT d.id, d.organization_id, d.hostname FROM device d
WHERE d.state = 'active' AND NOT EXISTS (
  SELECT 1 FROM revocation_request r
  WHERE r.device_id = d.id AND r.action = 'self_lock' AND r.status IN ('issued','delivered'))
ORDER BY d.id
LIMIT 500
`

type ListDevicesWithoutSelfLockRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Hostname       string
}

// Active devices without an open self-lock token.
func (q *Queries) ListDevicesWithoutSelfLock(ctx context.Context) ([]ListDevicesWithoutSelfLockRow, error) {
	rows, err := q.db.Query(ctx, listDevicesWithoutSelfLock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesWithoutSelfLockRow{}
	for rows.Next() {
		var i ListDevicesWithoutSelfLockRow
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPresumedSelfLocked = `-- name: MarkPresumedSelfLocked :many
UPDATE device_status SET presumed_self_locked_at = $1::timestamptz
WHERE presumed_self_locked_at IS NULL AND last_contact_at < $2::timestamptz
RETURNING device_id
`

type MarkPresumedSelfLockedParams struct {
	Now         time.Time
	SilentSince time.Time
}

// Devices silent since before silent_since: presumed to have locked themselves (once until their next contact).
func (q *Queries) MarkPresumedSelfLocked(ctx context.Context, arg MarkPresumedSelfLockedParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, markPresumedSelfLocked, arg.Now, arg.SilentSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var device_id uuid.UUID
		if err := rows.Scan(&device_id); err != nil {
			return nil, err
		}
		items = append(items, device_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDMSSettings = `-- name: UpsertDMSSettings :one
INSERT INTO organization_dms_settings (organization_id, enabled, period_days, warn_days, updated_at, updated_by)
VALUES ($1, $2, $3, $4, now(), $5)
ON CONFLICT (organization_id) DO UPDATE
SET enabled = excluded.enabled, period_days = excluded.period_days, warn_days = excluded.warn_days,
    updated_at = excluded.updated_at, updated_by = excluded.updated_by
RETURNING organization_id, enabled, period_days, warn_days, updated_at, updated_by
`

type UpsertDMSSettingsParams struct {
	OrganizationID uuid.UUID
	Enabled        bool
	PeriodDays     int32
	WarnDays       []int32
	UpdatedBy      uuid.NullUUID
}

func (q *Queries) UpsertDMSSettings(ctx context.Context, arg UpsertDMSSettingsParams) (OrganizationDmsSetting, error) {
	row := q.db.QueryRow(ctx, upsertDMSSettings,
		arg.OrganizationID,
		arg.Enabled,
		arg.PeriodDays,
		arg.WarnDays,
		arg.UpdatedBy,
	)
	var i OrganizationDmsSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.Enabled,
		&i.PeriodDays,
		&i.WarnDays,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
