// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment_token.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeEnrollmentTokenUse = `-- name: ConsumeEnrollmentTokenUse :exec
UPDATE enrollment_token SET uses = uses + 1 WHERE id = $1
`

func (q *Queries) ConsumeEnrollmentTokenUse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeEnrollmentTokenUse, id)
	return err
}

const countEnrollmentTokens = `-- name: CountEnrollmentTokens :one
SELECT count(*) FROM (
  SELECT 1 FROM enrollment_token
  WHERE ($1::text IS NULL OR name ILIKE $1::text ESCAPE '\')
  LIMIT $2
) matching
`

type CountEnrollmentTokensParams struct {
	QPattern   *string
	CountLimit int32
}

func (q *Queries) CountEnrollmentTokens(ctx context.Context, arg CountEnrollmentTokensParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnrollmentTokens, arg.QPattern, arg.CountLimit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEnrollmentToken = `-- name: GetEnrollmentToken :one
SELECT id, organization_id, name, secret_sha256, device_group_id, auto_approve, max_uses, uses, expires_at, revoked_at, created_by, created_at FROM enrollment_token WHERE id = $1
`

func (q *Queries) GetEnrollmentToken(ctx context.Context, id uuid.UUID) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, getEnrollmentToken, id)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.SecretSha256,
		&i.DeviceGroupID,
		&i.AutoApprove,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertEnrollmentToken = `-- name: InsertEnrollmentToken :one
INSERT INTO enrollment_token (id, organization_id, name, secret_sha256, device_group_id, auto_approve, max_uses,
                              expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9)
RETURNING id, organization_id, name, secret_sha256, device_group_id, auto_approve, max_uses, uses, expires_at, revoked_at, created_by, created_at
`

type InsertEnrollmentTokenParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	SecretSha256   []byte
	DeviceGroupID  uuid.NullUUID
	AutoApprove    bool
	MaxUses        int32
	ExpiresAt      time.Time
	CreatedBy      uuid.UUID
}

func (q *Queries) InsertEnrollmentToken(ctx context.Context, arg InsertEnrollmentTokenParams) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, insertEnrollmentToken,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.SecretSha256,
		arg.DeviceGroupID,
		arg.AutoApprove,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.SecretSha256,
		&i.DeviceGroupID,
		&i.AutoApprove,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listEnrollmentTokens = `-- name: ListEnrollmentTokens :many

SELECT id, organization_id, name, secret_sha256, device_group_id, auto_approve, max_uses, uses, expires_at, revoked_at, created_by, created_at FROM enrollment_token
WHERE ($1::text IS NULL OR name ILIKE $1::text ESCAPE '\')
ORDER BY
  CASE WHEN $2::text = 'name' THEN name END ASC,
  CASE WHEN $2::text = '-name' THEN name END DESC,
  CASE WHEN $2::text = 'created_at' THEN created_at END ASC,
  CASE WHEN $2::text = '-created_at' THEN created_at END DESC,
  CASE WHEN $2::text = 'expires_at' THEN expires_at END ASC,
  CASE WHEN $2::text = '-expires_at' THEN expires_at END DESC,
  id
LIMIT $4 OFFSET $3
`

type ListEnrollmentTokensParams struct {
	QPattern *string
	Sort     string
	SkipRows int32
	MaxRows  int32
}

// List queries (ADR 0018): see device_group.sql.
func (q *Queries) ListEnrollmentTokens(ctx context.Context, arg ListEnrollmentTokensParams) ([]EnrollmentToken, error) {
	rows, err := q.db.Query(ctx, listEnrollmentTokens,
		arg.QPattern,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentToken{}
	for rows.Next() {
		var i EnrollmentToken
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.SecretSha256,
			&i.DeviceGroupID,
			&i.AutoApprove,
			&i.MaxUses,
			&i.Uses,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveEnrollmentTokens = `-- name: ListLiveEnrollmentTokens :many
SELECT id, organization_id, name, secret_sha256, device_group_id, auto_approve, max_uses, uses, expires_at, revoked_at, created_by, created_at FROM enrollment_token WHERE expires_at > now() ORDER BY id
`

// Worker cache sync: every token of the organization that has not expired yet.
func (q *Queries) ListLiveEnrollmentTokens(ctx context.Context) ([]EnrollmentToken, error) {
	rows, err := q.db.Query(ctx, listLiveEnrollmentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentToken{}
	for rows.Next() {
		var i EnrollmentToken
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.SecretSha256,
			&i.DeviceGroupID,
			&i.AutoApprove,
			&i.MaxUses,
			&i.Uses,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEnrollmentTokenBySecret = `-- name: LockEnrollmentTokenBySecret :one
SELECT id, organization_id, name, secret_sha256, device_group_id, auto_approve, max_uses, uses, expires_at, revoked_at, created_by, created_at FROM enrollment_token WHERE secret_sha256 = $1 FOR UPDATE
`

// Worker: the row lock serializes concurrent enrollments with the same token.
func (q *Queries) LockEnrollmentTokenBySecret(ctx context.Context, secretSha256 []byte) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, lockEnrollmentTokenBySecret, secretSha256)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.SecretSha256,
		&i.DeviceGroupID,
		&i.AutoApprove,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const revokeEnrollmentToken = `-- name: RevokeEnrollmentToken :one
UPDATE enrollment_token SET revoked_at = coalesce(revoked_at, now())
WHERE id = $1
RETURNING id, organization_id, name, secret_sha256, device_group_id, auto_approve, max_uses, uses, expires_at, revoked_at, created_by, created_at
`

// Revoking twice keeps the first revocation time.
func (q *Queries) RevokeEnrollmentToken(ctx context.Context, id uuid.UUID) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, revokeEnrollmentToken, id)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.SecretSha256,
		&i.DeviceGroupID,
		&i.AutoApprove,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
