// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: escrow.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeEscrowGeneration = `-- name: ActiveEscrowGeneration :one
SELECT coalesce(max(generation), 0)::int FROM escrow_secret
WHERE device_id = $1 AND kind = $2 AND status = 'active'
`

type ActiveEscrowGenerationParams struct {
	DeviceID uuid.UUID
	Kind     string
}

func (q *Queries) ActiveEscrowGeneration(ctx context.Context, arg ActiveEscrowGenerationParams) (int32, error) {
	row := q.db.QueryRow(ctx, activeEscrowGeneration, arg.DeviceID, arg.Kind)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getEscrowSecret = `-- name: GetEscrowSecret :one

SELECT id, organization_id, device_id, kind, generation, status, ciphertext, key_version, created_at, activated_at FROM escrow_secret WHERE id = $1
`

// Escrowed secrets (plan M4a decisions 11 and 12).
func (q *Queries) GetEscrowSecret(ctx context.Context, id uuid.UUID) (EscrowSecret, error) {
	row := q.db.QueryRow(ctx, getEscrowSecret, id)
	var i EscrowSecret
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.Kind,
		&i.Generation,
		&i.Status,
		&i.Ciphertext,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const insertEscrowSecret = `-- name: InsertEscrowSecret :execrows
INSERT INTO escrow_secret (id, organization_id, device_id, kind, generation, status, ciphertext, key_version, created_at)
VALUES ($1, $2, $3, $4, $5, 'stored', $6, $7, $8)
ON CONFLICT DO NOTHING
`

type InsertEscrowSecretParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	Kind           string
	Generation     int32
	Ciphertext     []byte
	KeyVersion     int32
	CreatedAt      time.Time
}

// A generation that exists already (another upload of the same generation) is not overwritten.
func (q *Queries) InsertEscrowSecret(ctx context.Context, arg InsertEscrowSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEscrowSecret,
		arg.ID,
		arg.OrganizationID,
		arg.DeviceID,
		arg.Kind,
		arg.Generation,
		arg.Ciphertext,
		arg.KeyVersion,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
