// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteMissingFindings = `-- name: DeleteMissingFindings :exec
DELETE FROM vulnerability_finding f
WHERE f.device_id = $1
  AND (f.cve, f.software_name, f.software_version) NOT IN (
    SELECT unnest($2::text[]), unnest($3::text[]), unnest($4::text[]))
`

type DeleteMissingFindingsParams struct {
	DeviceID uuid.UUID
	Cves     []string
	Names    []string
	Versions []string
}

func (q *Queries) DeleteMissingFindings(ctx context.Context, arg DeleteMissingFindingsParams) error {
	_, err := q.db.Exec(ctx, deleteMissingFindings,
		arg.DeviceID,
		arg.Cves,
		arg.Names,
		arg.Versions,
	)
	return err
}

const deleteMissingPolicyResults = `-- name: DeleteMissingPolicyResults :exec
DELETE FROM inventory_policy_result WHERE device_id = $1 AND NOT (policy_key = ANY($2::text[]))
`

type DeleteMissingPolicyResultsParams struct {
	DeviceID uuid.UUID
	Keys     []string
}

func (q *Queries) DeleteMissingPolicyResults(ctx context.Context, arg DeleteMissingPolicyResultsParams) error {
	_, err := q.db.Exec(ctx, deleteMissingPolicyResults, arg.DeviceID, arg.Keys)
	return err
}

const deleteMissingSoftware = `-- name: DeleteMissingSoftware :exec
DELETE FROM installed_software s
WHERE s.device_id = $1
  AND (s.name, s.version, s.source) NOT IN (
    SELECT unnest($2::text[]), unnest($3::text[]), unnest($4::text[]))
`

type DeleteMissingSoftwareParams struct {
	DeviceID uuid.UUID
	Names    []string
	Versions []string
	Sources  []string
}

func (q *Queries) DeleteMissingSoftware(ctx context.Context, arg DeleteMissingSoftwareParams) error {
	_, err := q.db.Exec(ctx, deleteMissingSoftware,
		arg.DeviceID,
		arg.Names,
		arg.Versions,
		arg.Sources,
	)
	return err
}

const insertInstalledSoftware = `-- name: InsertInstalledSoftware :exec
INSERT INTO installed_software (device_id, organization_id, name, version, source)
SELECT $1, $2, unnest($3::text[]), unnest($4::text[]), unnest($5::text[])
ON CONFLICT DO NOTHING
`

type InsertInstalledSoftwareParams struct {
	DeviceID       uuid.UUID
	OrganizationID uuid.UUID
	Names          []string
	Versions       []string
	Sources        []string
}

func (q *Queries) InsertInstalledSoftware(ctx context.Context, arg InsertInstalledSoftwareParams) error {
	_, err := q.db.Exec(ctx, insertInstalledSoftware,
		arg.DeviceID,
		arg.OrganizationID,
		arg.Names,
		arg.Versions,
		arg.Sources,
	)
	return err
}

const inventoryDevices = `-- name: InventoryDevices :many

SELECT hardware_uuid::text, device_id::uuid, organization_id::uuid FROM paddock_inventory_devices($1::text[])
`

type InventoryDevicesRow struct {
	HardwareUuid   string
	DeviceID       uuid.UUID
	OrganizationID uuid.UUID
}

// Inventory sync of the worker (plan M5a decisions 6 to 8).
// The devices of hardware UUIDs, across organizations (platform pool); ambiguous and unknown UUIDs are missing.
func (q *Queries) InventoryDevices(ctx context.Context, uuids []string) ([]InventoryDevicesRow, error) {
	rows, err := q.db.Query(ctx, inventoryDevices, uuids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryDevicesRow{}
	for rows.Next() {
		var i InventoryDevicesRow
		if err := rows.Scan(&i.HardwareUuid, &i.DeviceID, &i.OrganizationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentNotRunning = `-- name: ListAgentNotRunning :many
SELECT r.device_id, s.last_contact_at
FROM inventory_policy_result r JOIN device d ON d.id = r.device_id LEFT JOIN device_status s ON s.device_id = r.device_id
WHERE d.state = 'active' AND r.policy_key = $1 AND NOT r.passing AND r.alerted_at IS NULL
  AND (s.last_contact_at IS NULL OR s.last_contact_at < $2::timestamptz)
ORDER BY r.device_id
`

type ListAgentNotRunningParams struct {
	PolicyKey string
	Before    time.Time
}

type ListAgentNotRunningRow struct {
	DeviceID      uuid.UUID
	LastContactAt *time.Time
}

// Active devices whose agent-running policy fails, not yet reported, and that have not checked in since before (plan
// M5a decision 8).
func (q *Queries) ListAgentNotRunning(ctx context.Context, arg ListAgentNotRunningParams) ([]ListAgentNotRunningRow, error) {
	rows, err := q.db.Query(ctx, listAgentNotRunning, arg.PolicyKey, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentNotRunningRow{}
	for rows.Next() {
		var i ListAgentNotRunningRow
		if err := rows.Scan(&i.DeviceID, &i.LastContactAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentNotRunningReported = `-- name: MarkAgentNotRunningReported :exec
UPDATE inventory_policy_result SET alerted_at = now() WHERE device_id = $1 AND policy_key = $2
`

type MarkAgentNotRunningReportedParams struct {
	DeviceID  uuid.UUID
	PolicyKey string
}

func (q *Queries) MarkAgentNotRunningReported(ctx context.Context, arg MarkAgentNotRunningReportedParams) error {
	_, err := q.db.Exec(ctx, markAgentNotRunningReported, arg.DeviceID, arg.PolicyKey)
	return err
}

const upsertInventoryRef = `-- name: UpsertInventoryRef :exec
INSERT INTO device_inventory_ref (device_id, organization_id, external_id, last_seen_at, os_version, fleetd_version, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (device_id) DO UPDATE
  SET external_id = EXCLUDED.external_id, last_seen_at = EXCLUDED.last_seen_at, os_version = EXCLUDED.os_version,
      fleetd_version = EXCLUDED.fleetd_version, synced_at = now()
`

type UpsertInventoryRefParams struct {
	DeviceID       uuid.UUID
	OrganizationID uuid.UUID
	ExternalID     string
	LastSeenAt     *time.Time
	OsVersion      string
	FleetdVersion  string
}

func (q *Queries) UpsertInventoryRef(ctx context.Context, arg UpsertInventoryRefParams) error {
	_, err := q.db.Exec(ctx, upsertInventoryRef,
		arg.DeviceID,
		arg.OrganizationID,
		arg.ExternalID,
		arg.LastSeenAt,
		arg.OsVersion,
		arg.FleetdVersion,
	)
	return err
}

const upsertPolicyResult = `-- name: UpsertPolicyResult :exec
INSERT INTO inventory_policy_result (device_id, organization_id, policy_key, passing, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (device_id, policy_key) DO UPDATE
  SET passing = EXCLUDED.passing,
      updated_at = CASE WHEN inventory_policy_result.passing = EXCLUDED.passing THEN inventory_policy_result.updated_at ELSE now() END,
      alerted_at = CASE WHEN EXCLUDED.passing THEN NULL ELSE inventory_policy_result.alerted_at END
`

type UpsertPolicyResultParams struct {
	DeviceID       uuid.UUID
	OrganizationID uuid.UUID
	PolicyKey      string
	Passing        bool
}

// updated_at is when the result last changed; a policy that passes again ends its mutual watch alert.
func (q *Queries) UpsertPolicyResult(ctx context.Context, arg UpsertPolicyResultParams) error {
	_, err := q.db.Exec(ctx, upsertPolicyResult,
		arg.DeviceID,
		arg.OrganizationID,
		arg.PolicyKey,
		arg.Passing,
	)
	return err
}

const upsertVulnerabilityFindings = `-- name: UpsertVulnerabilityFindings :exec
INSERT INTO vulnerability_finding (device_id, organization_id, cve, software_name, software_version, cvss_score, severity, fixed_version)
SELECT $1, $2, k.cve, k.name, k.version, NULLIF(k.cvss, -1)::numeric(3,1), NULLIF(k.severity, ''),
       NULLIF(k.fixed, '')
FROM (SELECT unnest($3::text[]) AS cve, unnest($4::text[]) AS name, unnest($5::text[]) AS version,
             unnest($6::float8[]) AS cvss, unnest($7::text[]) AS severity, unnest($8::text[]) AS fixed) k
ON CONFLICT (device_id, cve, software_name, software_version) DO UPDATE
  SET cvss_score = EXCLUDED.cvss_score, severity = EXCLUDED.severity, fixed_version = EXCLUDED.fixed_version
`

type UpsertVulnerabilityFindingsParams struct {
	DeviceID       uuid.UUID
	OrganizationID uuid.UUID
	Cves           []string
	Names          []string
	Versions       []string
	Cvss           []float64
	Severities     []string
	Fixed          []string
}

// The arrays are parallel; cvss -1 and empty strings stand for unknown values.
func (q *Queries) UpsertVulnerabilityFindings(ctx context.Context, arg UpsertVulnerabilityFindingsParams) error {
	_, err := q.db.Exec(ctx, upsertVulnerabilityFindings,
		arg.DeviceID,
		arg.OrganizationID,
		arg.Cves,
		arg.Names,
		arg.Versions,
		arg.Cvss,
		arg.Severities,
		arg.Fixed,
	)
	return err
}
