// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_settings.sql

package pgstore

import (
	"context"
)

const getLoginSettings = `-- name: GetLoginSettings :one

SELECT organization_id, hello_enabled, hello_pin_min_length, user_lock_session_action, break_glass_accounts, sudoers_d_allowlist, sudo_lecture_text, updated_at, local_admin_username, local_admin_rotation_days, rotate_after_reveal_hours FROM organization_login_settings
`

// Login settings (plan M3a decision 8): one row per organization, created with the defaults by a trigger.
func (q *Queries) GetLoginSettings(ctx context.Context) (OrganizationLoginSetting, error) {
	row := q.db.QueryRow(ctx, getLoginSettings)
	var i OrganizationLoginSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.HelloEnabled,
		&i.HelloPinMinLength,
		&i.UserLockSessionAction,
		&i.BreakGlassAccounts,
		&i.SudoersDAllowlist,
		&i.SudoLectureText,
		&i.UpdatedAt,
		&i.LocalAdminUsername,
		&i.LocalAdminRotationDays,
		&i.RotateAfterRevealHours,
	)
	return i, err
}

const updateLoginSettings = `-- name: UpdateLoginSettings :one
UPDATE organization_login_settings
SET hello_enabled = $1, hello_pin_min_length = $2,
    user_lock_session_action = $3, break_glass_accounts = $4,
    sudoers_d_allowlist = $5, sudo_lecture_text = $6,
    local_admin_username = $7, local_admin_rotation_days = $8,
    rotate_after_reveal_hours = $9, updated_at = now()
RETURNING organization_id, hello_enabled, hello_pin_min_length, user_lock_session_action, break_glass_accounts, sudoers_d_allowlist, sudo_lecture_text, updated_at, local_admin_username, local_admin_rotation_days, rotate_after_reveal_hours
`

type UpdateLoginSettingsParams struct {
	HelloEnabled           bool
	HelloPinMinLength      int32
	UserLockSessionAction  string
	BreakGlassAccounts     []string
	SudoersDAllowlist      []string
	SudoLectureText        string
	LocalAdminUsername     string
	LocalAdminRotationDays int32
	RotateAfterRevealHours *int32
}

func (q *Queries) UpdateLoginSettings(ctx context.Context, arg UpdateLoginSettingsParams) (OrganizationLoginSetting, error) {
	row := q.db.QueryRow(ctx, updateLoginSettings,
		arg.HelloEnabled,
		arg.HelloPinMinLength,
		arg.UserLockSessionAction,
		arg.BreakGlassAccounts,
		arg.SudoersDAllowlist,
		arg.SudoLectureText,
		arg.LocalAdminUsername,
		arg.LocalAdminRotationDays,
		arg.RotateAfterRevealHours,
	)
	var i OrganizationLoginSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.HelloEnabled,
		&i.HelloPinMinLength,
		&i.UserLockSessionAction,
		&i.BreakGlassAccounts,
		&i.SudoersDAllowlist,
		&i.SudoLectureText,
		&i.UpdatedAt,
		&i.LocalAdminUsername,
		&i.LocalAdminRotationDays,
		&i.RotateAfterRevealHours,
	)
	return i, err
}
