// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteDeviceLoginAssignments = `-- name: DeleteDeviceLoginAssignments :exec
DELETE FROM device_login_assignment WHERE device_id = $1
`

func (q *Queries) DeleteDeviceLoginAssignments(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeviceLoginAssignments, deviceID)
	return err
}

const deleteLoginAssignmentsOfSubject = `-- name: DeleteLoginAssignmentsOfSubject :many
DELETE FROM device_login_assignment WHERE subject_id = $1 RETURNING device_id
`

// A deleted user or group leaves every login assignment (the subject has no foreign key, plan M3a decision 9).
func (q *Queries) DeleteLoginAssignmentsOfSubject(ctx context.Context, subjectID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteLoginAssignmentsOfSubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var device_id uuid.UUID
		if err := rows.Scan(&device_id); err != nil {
			return nil, err
		}
		items = append(items, device_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDeviceLoginAssignment = `-- name: InsertDeviceLoginAssignment :exec
INSERT INTO device_login_assignment (organization_id, device_id, subject_type, subject_id)
VALUES ($1, $2, $3, $4)
`

type InsertDeviceLoginAssignmentParams struct {
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	SubjectType    string
	SubjectID      uuid.UUID
}

func (q *Queries) InsertDeviceLoginAssignment(ctx context.Context, arg InsertDeviceLoginAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertDeviceLoginAssignment,
		arg.OrganizationID,
		arg.DeviceID,
		arg.SubjectType,
		arg.SubjectID,
	)
	return err
}

const listAllDeviceGroupMembers = `-- name: ListAllDeviceGroupMembers :many
SELECT device_id, device_group_id FROM device_group_member ORDER BY device_id, device_group_id
`

type ListAllDeviceGroupMembersRow struct {
	DeviceID      uuid.UUID
	DeviceGroupID uuid.UUID
}

// Device groups of every device, for the effective profiles of the organization.
func (q *Queries) ListAllDeviceGroupMembers(ctx context.Context) ([]ListAllDeviceGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listAllDeviceGroupMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllDeviceGroupMembersRow{}
	for rows.Next() {
		var i ListAllDeviceGroupMembersRow
		if err := rows.Scan(&i.DeviceID, &i.DeviceGroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDeviceLoginAssignments = `-- name: ListAllDeviceLoginAssignments :many
SELECT organization_id, device_id, subject_type, subject_id FROM device_login_assignment ORDER BY device_id, subject_type, subject_id
`

func (q *Queries) ListAllDeviceLoginAssignments(ctx context.Context) ([]DeviceLoginAssignment, error) {
	rows, err := q.db.Query(ctx, listAllDeviceLoginAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceLoginAssignment{}
	for rows.Next() {
		var i DeviceLoginAssignment
		if err := rows.Scan(
			&i.OrganizationID,
			&i.DeviceID,
			&i.SubjectType,
			&i.SubjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceLoginAssignments = `-- name: ListDeviceLoginAssignments :many

SELECT organization_id, device_id, subject_type, subject_id FROM device_login_assignment WHERE device_id = $1 ORDER BY subject_type, subject_id
`

// Login assignment, suspension and session reports (plan M3a decisions 9–11).
func (q *Queries) ListDeviceLoginAssignments(ctx context.Context, deviceID uuid.UUID) ([]DeviceLoginAssignment, error) {
	rows, err := q.db.Query(ctx, listDeviceLoginAssignments, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceLoginAssignment{}
	for rows.Next() {
		var i DeviceLoginAssignment
		if err := rows.Scan(
			&i.OrganizationID,
			&i.DeviceID,
			&i.SubjectType,
			&i.SubjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceUsersSeenSince = `-- name: ListDeviceUsersSeenSince :many
SELECT device_id, username FROM device_user_seen WHERE last_seen_at >= $1 ORDER BY device_id, username
`

type ListDeviceUsersSeenSinceRow struct {
	DeviceID uuid.UUID
	Username string
}

func (q *Queries) ListDeviceUsersSeenSince(ctx context.Context, since time.Time) ([]ListDeviceUsersSeenSinceRow, error) {
	rows, err := q.db.Query(ctx, listDeviceUsersSeenSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceUsersSeenSinceRow{}
	for rows.Next() {
		var i ListDeviceUsersSeenSinceRow
		if err := rows.Scan(&i.DeviceID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceLoginsSuspended = `-- name: SetDeviceLoginsSuspended :one
UPDATE device SET logins_suspended = $1 WHERE id = $2 RETURNING id, organization_id, hostname, state, bundle_seq, hardware_uuid, machine_id, os_release, enrollment_token_id, enrolled_at, state_changed_at, logins_suspended
`

type SetDeviceLoginsSuspendedParams struct {
	LoginsSuspended bool
	ID              uuid.UUID
}

func (q *Queries) SetDeviceLoginsSuspended(ctx context.Context, arg SetDeviceLoginsSuspendedParams) (Device, error) {
	row := q.db.QueryRow(ctx, setDeviceLoginsSuspended, arg.LoginsSuspended, arg.ID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Hostname,
		&i.State,
		&i.BundleSeq,
		&i.HardwareUuid,
		&i.MachineID,
		&i.OsRelease,
		&i.EnrollmentTokenID,
		&i.EnrolledAt,
		&i.StateChangedAt,
		&i.LoginsSuspended,
	)
	return i, err
}

const upsertDeviceUserSeen = `-- name: UpsertDeviceUserSeen :exec
INSERT INTO device_user_seen (organization_id, device_id, username, last_seen_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (device_id, username) DO UPDATE SET last_seen_at = greatest(device_user_seen.last_seen_at, EXCLUDED.last_seen_at)
`

type UpsertDeviceUserSeenParams struct {
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	Username       string
	LastSeenAt     time.Time
}

// Worker: a session.login event of the agent (no audit event per login).
func (q *Queries) UpsertDeviceUserSeen(ctx context.Context, arg UpsertDeviceUserSeenParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceUserSeen,
		arg.OrganizationID,
		arg.DeviceID,
		arg.Username,
		arg.LastSeenAt,
	)
	return err
}
