// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: managed_config.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const countManagedFiles = `-- name: CountManagedFiles :one
SELECT count(*) FROM (
  SELECT 1 FROM managed_file
  WHERE ($1::text IS NULL OR path ILIKE $1::text ESCAPE '\')
    AND ($2::uuid IS NULL OR device_group_id = $2::uuid)
  LIMIT $3
) matching
`

type CountManagedFilesParams struct {
	QPattern      *string
	DeviceGroupID uuid.NullUUID
	CountLimit    int32
}

func (q *Queries) CountManagedFiles(ctx context.Context, arg CountManagedFilesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countManagedFiles, arg.QPattern, arg.DeviceGroupID, arg.CountLimit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countManagedUnits = `-- name: CountManagedUnits :one
SELECT count(*) FROM (
  SELECT 1 FROM managed_unit
  WHERE ($1::text IS NULL OR unit ILIKE $1::text ESCAPE '\')
    AND ($2::uuid IS NULL OR device_group_id = $2::uuid)
  LIMIT $3
) matching
`

type CountManagedUnitsParams struct {
	QPattern      *string
	DeviceGroupID uuid.NullUUID
	CountLimit    int32
}

func (q *Queries) CountManagedUnits(ctx context.Context, arg CountManagedUnitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countManagedUnits, arg.QPattern, arg.DeviceGroupID, arg.CountLimit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteManagedFile = `-- name: DeleteManagedFile :execrows
DELETE FROM managed_file WHERE id = $1
`

func (q *Queries) DeleteManagedFile(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteManagedFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteManagedUnit = `-- name: DeleteManagedUnit :execrows
DELETE FROM managed_unit WHERE id = $1
`

func (q *Queries) DeleteManagedUnit(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteManagedUnit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getManagedFile = `-- name: GetManagedFile :one
SELECT id, organization_id, device_group_id, path, mode, owner, grp, content, created_at, updated_at FROM managed_file WHERE id = $1
`

func (q *Queries) GetManagedFile(ctx context.Context, id uuid.UUID) (ManagedFile, error) {
	row := q.db.QueryRow(ctx, getManagedFile, id)
	var i ManagedFile
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceGroupID,
		&i.Path,
		&i.Mode,
		&i.Owner,
		&i.Grp,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagedUnit = `-- name: GetManagedUnit :one
SELECT id, organization_id, device_group_id, unit, enabled, active, created_at, updated_at FROM managed_unit WHERE id = $1
`

func (q *Queries) GetManagedUnit(ctx context.Context, id uuid.UUID) (ManagedUnit, error) {
	row := q.db.QueryRow(ctx, getManagedUnit, id)
	var i ManagedUnit
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceGroupID,
		&i.Unit,
		&i.Enabled,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertManagedFile = `-- name: InsertManagedFile :one
INSERT INTO managed_file (id, organization_id, device_group_id, path, mode, owner, grp, content)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, device_group_id, path, mode, owner, grp, content, created_at, updated_at
`

type InsertManagedFileParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceGroupID  uuid.NullUUID
	Path           string
	Mode           string
	Owner          string
	Grp            string
	Content        string
}

func (q *Queries) InsertManagedFile(ctx context.Context, arg InsertManagedFileParams) (ManagedFile, error) {
	row := q.db.QueryRow(ctx, insertManagedFile,
		arg.ID,
		arg.OrganizationID,
		arg.DeviceGroupID,
		arg.Path,
		arg.Mode,
		arg.Owner,
		arg.Grp,
		arg.Content,
	)
	var i ManagedFile
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceGroupID,
		&i.Path,
		&i.Mode,
		&i.Owner,
		&i.Grp,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertManagedUnit = `-- name: InsertManagedUnit :one
INSERT INTO managed_unit (id, organization_id, device_group_id, unit, enabled, active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, device_group_id, unit, enabled, active, created_at, updated_at
`

type InsertManagedUnitParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceGroupID  uuid.NullUUID
	Unit           string
	Enabled        bool
	Active         bool
}

func (q *Queries) InsertManagedUnit(ctx context.Context, arg InsertManagedUnitParams) (ManagedUnit, error) {
	row := q.db.QueryRow(ctx, insertManagedUnit,
		arg.ID,
		arg.OrganizationID,
		arg.DeviceGroupID,
		arg.Unit,
		arg.Enabled,
		arg.Active,
	)
	var i ManagedUnit
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceGroupID,
		&i.Unit,
		&i.Enabled,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllManagedFiles = `-- name: ListAllManagedFiles :many
SELECT id, organization_id, device_group_id, path, mode, owner, grp, content, created_at, updated_at FROM managed_file ORDER BY id
`

func (q *Queries) ListAllManagedFiles(ctx context.Context) ([]ManagedFile, error) {
	rows, err := q.db.Query(ctx, listAllManagedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagedFile{}
	for rows.Next() {
		var i ManagedFile
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeviceGroupID,
			&i.Path,
			&i.Mode,
			&i.Owner,
			&i.Grp,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllManagedUnits = `-- name: ListAllManagedUnits :many
SELECT id, organization_id, device_group_id, unit, enabled, active, created_at, updated_at FROM managed_unit ORDER BY id
`

func (q *Queries) ListAllManagedUnits(ctx context.Context) ([]ManagedUnit, error) {
	rows, err := q.db.Query(ctx, listAllManagedUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagedUnit{}
	for rows.Next() {
		var i ManagedUnit
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeviceGroupID,
			&i.Unit,
			&i.Enabled,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedFiles = `-- name: ListManagedFiles :many

SELECT id, organization_id, device_group_id, path, mode, owner, grp, content, created_at, updated_at FROM managed_file
WHERE ($1::text IS NULL OR path ILIKE $1::text ESCAPE '\')
  AND ($2::uuid IS NULL OR device_group_id = $2::uuid)
ORDER BY
  CASE WHEN $3::text = 'path' THEN path END ASC,
  CASE WHEN $3::text = '-path' THEN path END DESC,
  CASE WHEN $3::text = 'created_at' THEN created_at END ASC,
  CASE WHEN $3::text = '-created_at' THEN created_at END DESC,
  CASE WHEN $3::text = 'updated_at' THEN updated_at END ASC,
  CASE WHEN $3::text = '-updated_at' THEN updated_at END DESC,
  id
LIMIT $5 OFFSET $4
`

type ListManagedFilesParams struct {
	QPattern      *string
	DeviceGroupID uuid.NullUUID
	Sort          string
	SkipRows      int32
	MaxRows       int32
}

// List queries (ADR 0018): see device_group.sql.
func (q *Queries) ListManagedFiles(ctx context.Context, arg ListManagedFilesParams) ([]ManagedFile, error) {
	rows, err := q.db.Query(ctx, listManagedFiles,
		arg.QPattern,
		arg.DeviceGroupID,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagedFile{}
	for rows.Next() {
		var i ManagedFile
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeviceGroupID,
			&i.Path,
			&i.Mode,
			&i.Owner,
			&i.Grp,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedUnits = `-- name: ListManagedUnits :many
SELECT id, organization_id, device_group_id, unit, enabled, active, created_at, updated_at FROM managed_unit
WHERE ($1::text IS NULL OR unit ILIKE $1::text ESCAPE '\')
  AND ($2::uuid IS NULL OR device_group_id = $2::uuid)
ORDER BY
  CASE WHEN $3::text = 'unit' THEN unit END ASC,
  CASE WHEN $3::text = '-unit' THEN unit END DESC,
  CASE WHEN $3::text = 'created_at' THEN created_at END ASC,
  CASE WHEN $3::text = '-created_at' THEN created_at END DESC,
  CASE WHEN $3::text = 'updated_at' THEN updated_at END ASC,
  CASE WHEN $3::text = '-updated_at' THEN updated_at END DESC,
  id
LIMIT $5 OFFSET $4
`

type ListManagedUnitsParams struct {
	QPattern      *string
	DeviceGroupID uuid.NullUUID
	Sort          string
	SkipRows      int32
	MaxRows       int32
}

func (q *Queries) ListManagedUnits(ctx context.Context, arg ListManagedUnitsParams) ([]ManagedUnit, error) {
	rows, err := q.db.Query(ctx, listManagedUnits,
		arg.QPattern,
		arg.DeviceGroupID,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagedUnit{}
	for rows.Next() {
		var i ManagedUnit
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeviceGroupID,
			&i.Unit,
			&i.Enabled,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateManagedFile = `-- name: UpdateManagedFile :one
UPDATE managed_file SET path = $1, mode = $2, owner = $3, grp = $4, content = $5, updated_at = now()
WHERE id = $6
RETURNING id, organization_id, device_group_id, path, mode, owner, grp, content, created_at, updated_at
`

type UpdateManagedFileParams struct {
	Path    string
	Mode    string
	Owner   string
	Grp     string
	Content string
	ID      uuid.UUID
}

func (q *Queries) UpdateManagedFile(ctx context.Context, arg UpdateManagedFileParams) (ManagedFile, error) {
	row := q.db.QueryRow(ctx, updateManagedFile,
		arg.Path,
		arg.Mode,
		arg.Owner,
		arg.Grp,
		arg.Content,
		arg.ID,
	)
	var i ManagedFile
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceGroupID,
		&i.Path,
		&i.Mode,
		&i.Owner,
		&i.Grp,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateManagedUnit = `-- name: UpdateManagedUnit :one
UPDATE managed_unit SET unit = $1, enabled = $2, active = $3, updated_at = now()
WHERE id = $4
RETURNING id, organization_id, device_group_id, unit, enabled, active, created_at, updated_at
`

type UpdateManagedUnitParams struct {
	Unit    string
	Enabled bool
	Active  bool
	ID      uuid.UUID
}

func (q *Queries) UpdateManagedUnit(ctx context.Context, arg UpdateManagedUnitParams) (ManagedUnit, error) {
	row := q.db.QueryRow(ctx, updateManagedUnit,
		arg.Unit,
		arg.Enabled,
		arg.Active,
		arg.ID,
	)
	var i ManagedUnit
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceGroupID,
		&i.Unit,
		&i.Enabled,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
