// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Action struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Code           string
	Status         string
	Outcome        *string
	Actor          json.RawMessage
	Target         json.RawMessage
	Params         json.RawMessage
	ErrorCode      *string
	CorrelationID  string
	StartedAt      time.Time
	FinishedAt     *time.Time
}

type AdminAccount struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	AuthentikSub   string
	Username       string
	DisplayName    string
	Role           string
	Locale         string
	LastLoginAt    *time.Time
}

type AgentArtifact struct {
	Version   string
	Arch      string
	Sha256    string
	Size      int64
	Minisig   string
	ObjectKey string
	CreatedAt time.Time
}

type AgentPackage struct {
	Version        string
	Name           string
	Arch           string
	Sha256         string
	Size           int64
	Minisig        string
	ObjectKey      string
	CreatedAt      time.Time
	PackageVersion *string
}

type AgentRelease struct {
	Version     string
	Status      string
	CreatedBy   string
	CreatedAt   time.Time
	PublishedAt *time.Time
}

type AgentRollout struct {
	Version                 string
	Waves                   []int32
	CurrentWaveIndex        int32
	WaveStartedAt           time.Time
	MinWaveMinutes          int32
	FailureThresholdPercent int32
	FailureThresholdMin     int32
	Status                  string
	HaltedReason            *string
	StartedBy               string
	StartedAt               time.Time
	UpdatedAt               time.Time
	CompletedAt             *time.Time
	EvaluationSince         time.Time
}

type AgentUpdateReport struct {
	DeviceID       uuid.UUID
	OrganizationID uuid.UUID
	Version        string
	Outcome        string
	ReportedAt     time.Time
}

type AppUser struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	AuthentikPk    string
	Username       string
	DisplayName    string
	Email          string
	Source         string
	Locked         bool
	LockedAt       *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LockIncomplete bool
	LockReactivate *bool
}

type Bundle struct {
	DeviceID       uuid.UUID
	Version        int64
	OrganizationID uuid.UUID
	ContentSha256  []byte
	EnvelopeSha256 []byte
	ObjectKey      string
	CreatedAt      time.Time
	SchemaVersion  int32
}

type Device struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	Hostname          string
	State             string
	BundleSeq         int64
	HardwareUuid      *string
	MachineID         *string
	OsRelease         json.RawMessage
	EnrollmentTokenID uuid.NullUUID
	EnrolledAt        time.Time
	StateChangedAt    time.Time
	LoginsSuspended   bool
}

type DeviceCommand struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	Type           string
	Params         json.RawMessage
	Status         string
	IssuedBy       uuid.NullUUID
	IssuedAt       time.Time
	ExpiresAt      time.Time
	NotBefore      *time.Time
	DeliveredAt    *time.Time
	FinishedAt     *time.Time
	Result         json.RawMessage
}

type DeviceEventSeen struct {
	DeviceID       uuid.UUID
	EventSeq       int64
	OrganizationID uuid.UUID
}

type DeviceGroup struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type DeviceGroupMember struct {
	OrganizationID uuid.UUID
	DeviceGroupID  uuid.UUID
	DeviceID       uuid.UUID
}

type DeviceIdentityKey struct {
	KeyID          string
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	PublicKey      []byte
	KeyProtection  string
	Status         string
	CreatedAt      time.Time
}

type DeviceLoginAssignment struct {
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	SubjectType    string
	SubjectID      uuid.UUID
}

type DeviceStatus struct {
	DeviceID             uuid.UUID
	OrganizationID       uuid.UUID
	LastContactAt        *time.Time
	AppliedBundleVersion *int64
	AgentVersion         *string
	LastSeq              int64
	Health               json.RawMessage
	SchemaVersions       []int32
	LoginState           json.RawMessage
	PresumedSelfLockedAt *time.Time
}

type DeviceUserSeen struct {
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	Username       string
	LastSeenAt     time.Time
}

type EnrollmentToken struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	SecretSha256   []byte
	DeviceGroupID  uuid.NullUUID
	AutoApprove    bool
	MaxUses        int32
	Uses           int32
	ExpiresAt      time.Time
	RevokedAt      *time.Time
	CreatedBy      uuid.UUID
	CreatedAt      time.Time
}

type EscrowSecret struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	Kind           string
	Generation     int32
	Status         string
	Ciphertext     []byte
	KeyVersion     int32
	CreatedAt      time.Time
	ActivatedAt    *time.Time
	ObjectKey      *string
	WrappedDek     []byte
	Nonce          []byte
	Sha256         *string
	Size           *int64
}

type ManagedFile struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceGroupID  uuid.NullUUID
	Path           string
	Mode           string
	Owner          string
	Grp            string
	Content        string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ManagedUnit struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceGroupID  uuid.NullUUID
	Unit           string
	Enabled        bool
	Active         bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Organization struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	Domains   []string
}

type OrganizationDmsSetting struct {
	OrganizationID uuid.UUID
	Enabled        bool
	PeriodDays     int32
	WarnDays       []int32
	UpdatedAt      time.Time
	UpdatedBy      uuid.NullUUID
}

type OrganizationLoginSetting struct {
	OrganizationID         uuid.UUID
	HelloEnabled           bool
	HelloPinMinLength      int32
	UserLockSessionAction  string
	BreakGlassAccounts     []string
	SudoersDAllowlist      []string
	SudoLectureText        string
	UpdatedAt              time.Time
	LocalAdminUsername     string
	LocalAdminRotationDays int32
	RotateAfterRevealHours *int32
	NoticeText             string
	BootPinMinLength       int32
}

type Outbox struct {
	ID             int64
	OrganizationID uuid.UUID
	Subject        string
	MsgID          string
	Payload        json.RawMessage
	CreatedAt      time.Time
	PublishedAt    *time.Time
}

type PermissionProfile struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	Name                string
	Class               string
	Commands            []string
	RequirePassword     bool
	TimestampTimeoutMin int32
	Lecture             string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type PlatformAdmin struct {
	ID           uuid.UUID
	AuthentikSub string
	Username     string
	DisplayName  string
	Locale       string
	LastLoginAt  *time.Time
}

type ProfileAssignment struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ProfileID      uuid.UUID
	SubjectType    string
	SubjectID      uuid.NullUUID
	DeviceGroupID  uuid.NullUUID
	CreatedAt      time.Time
}

type RevocationApproval struct {
	RequestID      uuid.UUID
	OrganizationID uuid.UUID
	Role           string
	AdminID        uuid.UUID
	Subject        string
	StepupJti      string
	StepupIDToken  *string
	ApprovedAt     time.Time
}

type RevocationFreeze struct {
	OrganizationID uuid.UUID
	AdminID        uuid.UUID
	RequestID      uuid.UUID
	FrozenAt       time.Time
	FrozenUntil    time.Time
}

type RevocationRequest struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	Action         string
	Status         string
	RequestedBy    uuid.NullUUID
	RequestedAt    time.Time
	Reason         string
	ApprovedAt     *time.Time
	IssuedAt       *time.Time
	ExpiresAt      *time.Time
	Envelope       []byte
	PeriodDays     *int32
	DeliveredAt    *time.Time
	ConfirmedAt    *time.Time
	FinishedAt     *time.Time
	Rejection      *string
	Result         json.RawMessage
}

type UserGroup struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	Slug                string
	Name                string
	Source              string
	UpstreamAuthentikPk *string
	AuthentikPk         string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type UserGroupMember struct {
	OrganizationID uuid.UUID
	GroupID        uuid.UUID
	UserID         uuid.UUID
}
