// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Action struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Code           string
	Status         string
	Outcome        *string
	Actor          json.RawMessage
	Target         json.RawMessage
	Params         json.RawMessage
	ErrorCode      *string
	CorrelationID  string
	StartedAt      time.Time
	FinishedAt     *time.Time
}

type AdminAccount struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	AuthentikSub   string
	Username       string
	DisplayName    string
	Role           string
	Locale         string
	LastLoginAt    *time.Time
}

type AgentArtifact struct {
	Version   string
	Arch      string
	Sha256    string
	Size      int64
	Minisig   string
	ObjectKey string
	CreatedAt time.Time
}

type AgentRelease struct {
	Version     string
	Status      string
	CreatedBy   string
	CreatedAt   time.Time
	PublishedAt *time.Time
}

type AgentRollout struct {
	Version                 string
	Waves                   []int32
	CurrentWaveIndex        int32
	WaveStartedAt           time.Time
	MinWaveMinutes          int32
	FailureThresholdPercent int32
	FailureThresholdMin     int32
	Status                  string
	HaltedReason            *string
	StartedBy               string
	StartedAt               time.Time
	UpdatedAt               time.Time
	CompletedAt             *time.Time
	EvaluationSince         time.Time
}

type AgentUpdateReport struct {
	DeviceID       uuid.UUID
	OrganizationID uuid.UUID
	Version        string
	Outcome        string
	ReportedAt     time.Time
}

type Bundle struct {
	DeviceID       uuid.UUID
	Version        int64
	OrganizationID uuid.UUID
	ContentSha256  []byte
	EnvelopeSha256 []byte
	ObjectKey      string
	CreatedAt      time.Time
}

type Device struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	Hostname          string
	State             string
	BundleSeq         int64
	HardwareUuid      *string
	MachineID         *string
	OsRelease         json.RawMessage
	EnrollmentTokenID uuid.NullUUID
	EnrolledAt        time.Time
	StateChangedAt    time.Time
}

type DeviceEventSeen struct {
	DeviceID       uuid.UUID
	EventSeq       int64
	OrganizationID uuid.UUID
}

type DeviceGroup struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type DeviceGroupMember struct {
	OrganizationID uuid.UUID
	DeviceGroupID  uuid.UUID
	DeviceID       uuid.UUID
}

type DeviceIdentityKey struct {
	KeyID          string
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	PublicKey      []byte
	KeyProtection  string
	Status         string
	CreatedAt      time.Time
}

type DeviceStatus struct {
	DeviceID             uuid.UUID
	OrganizationID       uuid.UUID
	LastContactAt        *time.Time
	AppliedBundleVersion *int64
	AgentVersion         *string
	LastSeq              int64
	Health               json.RawMessage
}

type EnrollmentToken struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	SecretSha256   []byte
	DeviceGroupID  uuid.NullUUID
	AutoApprove    bool
	MaxUses        int32
	Uses           int32
	ExpiresAt      time.Time
	RevokedAt      *time.Time
	CreatedBy      uuid.UUID
	CreatedAt      time.Time
}

type ManagedFile struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceGroupID  uuid.NullUUID
	Path           string
	Mode           string
	Owner          string
	Grp            string
	Content        string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ManagedUnit struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceGroupID  uuid.NullUUID
	Unit           string
	Enabled        bool
	Active         bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Organization struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Outbox struct {
	ID             int64
	OrganizationID uuid.UUID
	Subject        string
	MsgID          string
	Payload        json.RawMessage
	CreatedAt      time.Time
	PublishedAt    *time.Time
}

type PlatformAdmin struct {
	ID           uuid.UUID
	AuthentikSub string
	Username     string
	DisplayName  string
	Locale       string
	LastLoginAt  *time.Time
}
