// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Action struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Code           string
	Status         string
	Outcome        *string
	Actor          json.RawMessage
	Target         json.RawMessage
	Params         json.RawMessage
	ErrorCode      *string
	CorrelationID  string
	StartedAt      time.Time
	FinishedAt     *time.Time
}

type AdminAccount struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	AuthentikSub   string
	Username       string
	DisplayName    string
	Role           string
	Locale         string
	LastLoginAt    *time.Time
}

type DeviceGroup struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Organization struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Outbox struct {
	ID             int64
	OrganizationID uuid.UUID
	Subject        string
	MsgID          string
	Payload        json.RawMessage
	CreatedAt      time.Time
	PublishedAt    *time.Time
}

type PlatformAdmin struct {
	ID           uuid.UUID
	AuthentikSub string
	Username     string
	DisplayName  string
	Locale       string
	LastLoginAt  *time.Time
}
