// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT count(*) FROM (
  SELECT 1 FROM organization
  WHERE ($1::text IS NULL
         OR slug ILIKE $1::text ESCAPE '\'
         OR name ILIKE $1::text ESCAPE '\')
    AND ($2::text[] IS NULL OR status = ANY($2::text[]))
  LIMIT $3
) matching
`

type CountOrganizationsParams struct {
	QPattern   *string
	Statuses   []string
	CountLimit int32
}

func (q *Queries) CountOrganizations(ctx context.Context, arg CountOrganizationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations, arg.QPattern, arg.Statuses, arg.CountLimit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, slug, name, status, created_at, updated_at, domains FROM organization WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Domains,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, slug, name, status, created_at, updated_at, domains FROM organization WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Domains,
	)
	return i, err
}

const insertOrganization = `-- name: InsertOrganization :one
INSERT INTO organization (id, slug, name, status)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, status, created_at, updated_at, domains
`

type InsertOrganizationParams struct {
	ID     uuid.UUID
	Slug   string
	Name   string
	Status string
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, insertOrganization,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Status,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Domains,
	)
	return i, err
}

const listOrganizationIDs = `-- name: ListOrganizationIDs :many
SELECT id::uuid FROM paddock_organization_ids() AS id
`

// Worker and compiler loops: organization IDs without an organization context (SECURITY DEFINER function).
func (q *Queries) ListOrganizationIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOrganizationIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many

SELECT id, slug, name, status, created_at, updated_at, domains FROM organization
WHERE ($1::text IS NULL
       OR slug ILIKE $1::text ESCAPE '\'
       OR name ILIKE $1::text ESCAPE '\')
  AND ($2::text[] IS NULL OR status = ANY($2::text[]))
ORDER BY
  CASE WHEN $3::text = 'slug' THEN slug END ASC,
  CASE WHEN $3::text = '-slug' THEN slug END DESC,
  CASE WHEN $3::text = 'name' THEN name END ASC,
  CASE WHEN $3::text = '-name' THEN name END DESC,
  CASE WHEN $3::text = 'created_at' THEN created_at END ASC,
  CASE WHEN $3::text = '-created_at' THEN created_at END DESC,
  CASE WHEN $3::text = 'status' THEN status END ASC,
  CASE WHEN $3::text = '-status' THEN status END DESC,
  id
LIMIT $5 OFFSET $4
`

type ListOrganizationsParams struct {
	QPattern *string
	Statuses []string
	Sort     string
	SkipRows int32
	MaxRows  int32
}

// List queries (ADR 0018): see device_group.sql.
func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations,
		arg.QPattern,
		arg.Statuses,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Domains,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationIDBySlug = `-- name: OrganizationIDBySlug :one
SELECT coalesce(paddock_org_id_by_slug($1), '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS id
`

// Returns uuid.Nil when no active organization has this slug.
func (q *Queries) OrganizationIDBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, organizationIDBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateOrganizationStatus = `-- name: UpdateOrganizationStatus :one
UPDATE organization SET status = $1, name = $2, updated_at = now()
WHERE id = $3
RETURNING id, slug, name, status, created_at, updated_at, domains
`

type UpdateOrganizationStatusParams struct {
	Status string
	Name   string
	ID     uuid.UUID
}

func (q *Queries) UpdateOrganizationStatus(ctx context.Context, arg UpdateOrganizationStatusParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationStatus, arg.Status, arg.Name, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Domains,
	)
	return i, err
}
