// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: osv.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteOSVBinaries = `-- name: DeleteOSVBinaries :exec
DELETE FROM osv_ubuntu_binary
`

func (q *Queries) DeleteOSVBinaries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOSVBinaries)
	return err
}

const deleteOSVData = `-- name: DeleteOSVData :exec
DELETE FROM osv_ubuntu
`

func (q *Queries) DeleteOSVData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOSVData)
	return err
}

const enrichFindings = `-- name: EnrichFindings :execrows
UPDATE vulnerability_finding f
SET severity = m.severity, fixed_version = m.fixed_version, cvss_vector = m.cvss_vector
FROM (
  SELECT g.device_id, g.cve, g.software_name, g.software_version, coalesce(x.osv_severity, g.fleet_severity) AS severity,
         coalesce(x.osv_fixed, g.fleet_fixed_version) AS fixed_version, x.osv_vector AS cvss_vector
  FROM vulnerability_finding g
  JOIN device_inventory_ref r ON r.device_id = g.device_id
  LEFT JOIN LATERAL paddock_osv_match(substring(r.os_version from '[0-9]{2}\.[0-9]{2}'), g.cve, g.software_name)
    AS x(osv_severity, osv_fixed, osv_vector) ON true
  WHERE $1::uuid IS NULL OR g.device_id = $1::uuid
) m
WHERE f.device_id = m.device_id AND f.cve = m.cve AND f.software_name = m.software_name
  AND f.software_version = m.software_version
  AND (f.severity, f.fixed_version, f.cvss_vector) IS DISTINCT FROM (m.severity, m.fixed_version, m.cvss_vector)
`

// Enrichment (plan M5c decision 2): every finding of the organization, or of one device, gets Ubuntu's severity, fixed
// version and CVSS vector for the release of the device's OS. A finding Ubuntu has no priority or no entry for (any
// more) shows the inventory system's own severity and fixed version. Only changed rows are written.
func (q *Queries) EnrichFindings(ctx context.Context, deviceID uuid.NullUUID) (int64, error) {
	result, err := q.db.Exec(ctx, enrichFindings, deviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOSVSyncState = `-- name: GetOSVSyncState :one

SELECT etag, data_version, entries, last_success_at, last_attempt_at, last_error, stale_alerted_at, created_at
FROM osv_sync_state WHERE source = 'ubuntu'
`

type GetOSVSyncStateRow struct {
	Etag           string
	DataVersion    int64
	Entries        int32
	LastSuccessAt  *time.Time
	LastAttemptAt  *time.Time
	LastError      string
	StaleAlertedAt *time.Time
	CreatedAt      time.Time
}

// Ubuntu's OSV data (plan M5c decisions 1, 2 and 4): the import replaces the platform tables in one transaction
// (platform pool); the enrichment updates the findings of an organization (worker pool).
func (q *Queries) GetOSVSyncState(ctx context.Context) (GetOSVSyncStateRow, error) {
	row := q.db.QueryRow(ctx, getOSVSyncState)
	var i GetOSVSyncStateRow
	err := row.Scan(
		&i.Etag,
		&i.DataVersion,
		&i.Entries,
		&i.LastSuccessAt,
		&i.LastAttemptAt,
		&i.LastError,
		&i.StaleAlertedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertOSVBinaries = `-- name: InsertOSVBinaries :exec
INSERT INTO osv_ubuntu_binary (release, binary_name, package)
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::text[])
ON CONFLICT DO NOTHING
`

type InsertOSVBinariesParams struct {
	Releases []string
	Binaries []string
	Packages []string
}

func (q *Queries) InsertOSVBinaries(ctx context.Context, arg InsertOSVBinariesParams) error {
	_, err := q.db.Exec(ctx, insertOSVBinaries, arg.Releases, arg.Binaries, arg.Packages)
	return err
}

const insertOSVEntries = `-- name: InsertOSVEntries :exec
INSERT INTO osv_ubuntu (cve, release, package, priority, fixed_version, cvss_vector, modified)
SELECT k.cve, k.release, k.package, k.priority, NULLIF(k.fixed, ''), NULLIF(k.vector, ''), k.modified
FROM (SELECT unnest($1::text[]) AS cve, unnest($2::text[]) AS release, unnest($3::text[]) AS package,
             unnest($4::text[]) AS priority, unnest($5::text[]) AS fixed, unnest($6::text[]) AS vector,
             unnest($7::timestamptz[]) AS modified) k
`

type InsertOSVEntriesParams struct {
	Cves       []string
	Releases   []string
	Packages   []string
	Priorities []string
	Fixed      []string
	Vectors    []string
	Modified   []time.Time
}

// The arrays are parallel; empty strings stand for unknown values.
func (q *Queries) InsertOSVEntries(ctx context.Context, arg InsertOSVEntriesParams) error {
	_, err := q.db.Exec(ctx, insertOSVEntries,
		arg.Cves,
		arg.Releases,
		arg.Packages,
		arg.Priorities,
		arg.Fixed,
		arg.Vectors,
		arg.Modified,
	)
	return err
}

const markOSVFailed = `-- name: MarkOSVFailed :exec
UPDATE osv_sync_state SET last_attempt_at = now(), last_error = $1 WHERE source = 'ubuntu'
`

func (q *Queries) MarkOSVFailed(ctx context.Context, lastError string) error {
	_, err := q.db.Exec(ctx, markOSVFailed, lastError)
	return err
}

const markOSVImported = `-- name: MarkOSVImported :exec
UPDATE osv_sync_state
SET etag = $1, data_version = data_version + 1, entries = $2, last_success_at = now(), last_attempt_at = now(),
    last_error = '', stale_alerted_at = NULL
WHERE source = 'ubuntu'
`

type MarkOSVImportedParams struct {
	Etag    string
	Entries int32
}

func (q *Queries) MarkOSVImported(ctx context.Context, arg MarkOSVImportedParams) error {
	_, err := q.db.Exec(ctx, markOSVImported, arg.Etag, arg.Entries)
	return err
}

const markOSVNotModified = `-- name: MarkOSVNotModified :exec
UPDATE osv_sync_state SET last_success_at = now(), last_attempt_at = now(), last_error = '', stale_alerted_at = NULL
WHERE source = 'ubuntu'
`

// A 304 confirms the data: a success without a new import.
func (q *Queries) MarkOSVNotModified(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markOSVNotModified)
	return err
}

const markOSVStaleAlerted = `-- name: MarkOSVStaleAlerted :exec
UPDATE osv_sync_state SET stale_alerted_at = now() WHERE source = 'ubuntu'
`

func (q *Queries) MarkOSVStaleAlerted(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markOSVStaleAlerted)
	return err
}
