// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package pgstore

import (
	"context"
	"time"
)

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
SELECT id, organization_id, subject, msg_id, payload, created_at, published_at FROM outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimOutboxBatch(ctx context.Context, maxRows int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Subject,
			&i.MsgID,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnpublishedOutbox = `-- name: CountUnpublishedOutbox :one
SELECT count(*) FROM outbox WHERE published_at IS NULL
`

func (q *Queries) CountUnpublishedOutbox(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnpublishedOutbox)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePublishedOutbox = `-- name: DeletePublishedOutbox :execrows
DELETE FROM outbox WHERE published_at IS NOT NULL AND published_at < $1
`

func (q *Queries) DeletePublishedOutbox(ctx context.Context, publishedBefore *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublishedOutbox, publishedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :execrows
UPDATE outbox SET published_at = now() WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, ids []int64) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxPublished, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
