// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privilege.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const countPermissionProfiles = `-- name: CountPermissionProfiles :one
SELECT count(*) FROM (
  SELECT 1 FROM permission_profile
  WHERE ($1::text IS NULL OR name ILIKE $1::text ESCAPE '\')
    AND ($2::text[] IS NULL OR class = ANY($2::text[]))
  LIMIT $3
) matching
`

type CountPermissionProfilesParams struct {
	QPattern   *string
	Classes    []string
	CountLimit int32
}

func (q *Queries) CountPermissionProfiles(ctx context.Context, arg CountPermissionProfilesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPermissionProfiles, arg.QPattern, arg.Classes, arg.CountLimit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProfileAssignments = `-- name: CountProfileAssignments :one
SELECT count(*) FROM (
  SELECT 1 FROM profile_assignment
  WHERE ($1::text IS NULL OR EXISTS (
          SELECT 1 FROM permission_profile p
          WHERE p.id = profile_assignment.profile_id AND p.name ILIKE $1::text ESCAPE '\'))
    AND ($2::uuid IS NULL OR profile_id = $2::uuid)
    AND ($3::text[] IS NULL OR subject_type = ANY($3::text[]))
    AND ($4::uuid IS NULL OR subject_id = $4::uuid)
    AND ($5::uuid IS NULL OR device_group_id = $5::uuid)
  LIMIT $6
) matching
`

type CountProfileAssignmentsParams struct {
	QPattern      *string
	ProfileID     uuid.NullUUID
	SubjectTypes  []string
	SubjectID     uuid.NullUUID
	DeviceGroupID uuid.NullUUID
	CountLimit    int32
}

func (q *Queries) CountProfileAssignments(ctx context.Context, arg CountProfileAssignmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProfileAssignments,
		arg.QPattern,
		arg.ProfileID,
		arg.SubjectTypes,
		arg.SubjectID,
		arg.DeviceGroupID,
		arg.CountLimit,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProfileAssignmentsOfProfile = `-- name: CountProfileAssignmentsOfProfile :one
SELECT count(*) FROM profile_assignment WHERE profile_id = $1
`

func (q *Queries) CountProfileAssignmentsOfProfile(ctx context.Context, profileID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProfileAssignmentsOfProfile, profileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePermissionProfile = `-- name: DeletePermissionProfile :execrows
DELETE FROM permission_profile WHERE id = $1
`

func (q *Queries) DeletePermissionProfile(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePermissionProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProfileAssignment = `-- name: DeleteProfileAssignment :execrows
DELETE FROM profile_assignment WHERE id = $1
`

func (q *Queries) DeleteProfileAssignment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfileAssignment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProfileAssignmentsOfSubject = `-- name: DeleteProfileAssignmentsOfSubject :execrows
DELETE FROM profile_assignment WHERE subject_id = $1
`

// A deleted user or group takes its assignments (the subject has no foreign key, plan M3a decision 12).
func (q *Queries) DeleteProfileAssignmentsOfSubject(ctx context.Context, subjectID uuid.NullUUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfileAssignmentsOfSubject, subjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPermissionProfile = `-- name: GetPermissionProfile :one
SELECT id, organization_id, name, class, commands, require_password, timestamp_timeout_min, lecture, created_at, updated_at FROM permission_profile WHERE id = $1
`

func (q *Queries) GetPermissionProfile(ctx context.Context, id uuid.UUID) (PermissionProfile, error) {
	row := q.db.QueryRow(ctx, getPermissionProfile, id)
	var i PermissionProfile
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Class,
		&i.Commands,
		&i.RequirePassword,
		&i.TimestampTimeoutMin,
		&i.Lecture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileAssignment = `-- name: GetProfileAssignment :one
SELECT id, organization_id, profile_id, subject_type, subject_id, device_group_id, created_at FROM profile_assignment WHERE id = $1
`

func (q *Queries) GetProfileAssignment(ctx context.Context, id uuid.UUID) (ProfileAssignment, error) {
	row := q.db.QueryRow(ctx, getProfileAssignment, id)
	var i ProfileAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProfileID,
		&i.SubjectType,
		&i.SubjectID,
		&i.DeviceGroupID,
		&i.CreatedAt,
	)
	return i, err
}

const insertPermissionProfile = `-- name: InsertPermissionProfile :one

INSERT INTO permission_profile (id, organization_id, name, class, commands, require_password, timestamp_timeout_min, lecture)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, name, class, commands, require_password, timestamp_timeout_min, lecture, created_at, updated_at
`

type InsertPermissionProfileParams struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	Name                string
	Class               string
	Commands            []string
	RequirePassword     bool
	TimestampTimeoutMin int32
	Lecture             string
}

// Permission profiles and their assignments (plan M3a decisions 12–14).
func (q *Queries) InsertPermissionProfile(ctx context.Context, arg InsertPermissionProfileParams) (PermissionProfile, error) {
	row := q.db.QueryRow(ctx, insertPermissionProfile,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Class,
		arg.Commands,
		arg.RequirePassword,
		arg.TimestampTimeoutMin,
		arg.Lecture,
	)
	var i PermissionProfile
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Class,
		&i.Commands,
		&i.RequirePassword,
		&i.TimestampTimeoutMin,
		&i.Lecture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProfileAssignment = `-- name: InsertProfileAssignment :one
INSERT INTO profile_assignment (id, organization_id, profile_id, subject_type, subject_id, device_group_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, profile_id, subject_type, subject_id, device_group_id, created_at
`

type InsertProfileAssignmentParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ProfileID      uuid.UUID
	SubjectType    string
	SubjectID      uuid.NullUUID
	DeviceGroupID  uuid.NullUUID
}

func (q *Queries) InsertProfileAssignment(ctx context.Context, arg InsertProfileAssignmentParams) (ProfileAssignment, error) {
	row := q.db.QueryRow(ctx, insertProfileAssignment,
		arg.ID,
		arg.OrganizationID,
		arg.ProfileID,
		arg.SubjectType,
		arg.SubjectID,
		arg.DeviceGroupID,
	)
	var i ProfileAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProfileID,
		&i.SubjectType,
		&i.SubjectID,
		&i.DeviceGroupID,
		&i.CreatedAt,
	)
	return i, err
}

const listAllPermissionProfiles = `-- name: ListAllPermissionProfiles :many
SELECT id, organization_id, name, class, commands, require_password, timestamp_timeout_min, lecture, created_at, updated_at FROM permission_profile ORDER BY id
`

func (q *Queries) ListAllPermissionProfiles(ctx context.Context) ([]PermissionProfile, error) {
	rows, err := q.db.Query(ctx, listAllPermissionProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionProfile{}
	for rows.Next() {
		var i PermissionProfile
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Class,
			&i.Commands,
			&i.RequirePassword,
			&i.TimestampTimeoutMin,
			&i.Lecture,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProfileAssignments = `-- name: ListAllProfileAssignments :many
SELECT id, organization_id, profile_id, subject_type, subject_id, device_group_id, created_at FROM profile_assignment ORDER BY id
`

func (q *Queries) ListAllProfileAssignments(ctx context.Context) ([]ProfileAssignment, error) {
	rows, err := q.db.Query(ctx, listAllProfileAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileAssignment{}
	for rows.Next() {
		var i ProfileAssignment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProfileID,
			&i.SubjectType,
			&i.SubjectID,
			&i.DeviceGroupID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionProfiles = `-- name: ListPermissionProfiles :many

SELECT id, organization_id, name, class, commands, require_password, timestamp_timeout_min, lecture, created_at, updated_at FROM permission_profile
WHERE ($1::text IS NULL OR name ILIKE $1::text ESCAPE '\')
  AND ($2::text[] IS NULL OR class = ANY($2::text[]))
ORDER BY
  CASE WHEN $3::text = 'name' THEN name END ASC,
  CASE WHEN $3::text = '-name' THEN name END DESC,
  CASE WHEN $3::text = 'class' THEN class END ASC,
  CASE WHEN $3::text = '-class' THEN class END DESC,
  CASE WHEN $3::text = 'created_at' THEN created_at END ASC,
  CASE WHEN $3::text = '-created_at' THEN created_at END DESC,
  CASE WHEN $3::text = 'updated_at' THEN updated_at END ASC,
  CASE WHEN $3::text = '-updated_at' THEN updated_at END DESC,
  id
LIMIT $5 OFFSET $4
`

type ListPermissionProfilesParams struct {
	QPattern *string
	Classes  []string
	Sort     string
	SkipRows int32
	MaxRows  int32
}

// List queries (ADR 0018): see device_group.sql.
func (q *Queries) ListPermissionProfiles(ctx context.Context, arg ListPermissionProfilesParams) ([]PermissionProfile, error) {
	rows, err := q.db.Query(ctx, listPermissionProfiles,
		arg.QPattern,
		arg.Classes,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionProfile{}
	for rows.Next() {
		var i PermissionProfile
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Class,
			&i.Commands,
			&i.RequirePassword,
			&i.TimestampTimeoutMin,
			&i.Lecture,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileAssignments = `-- name: ListProfileAssignments :many
SELECT id, organization_id, profile_id, subject_type, subject_id, device_group_id, created_at FROM profile_assignment
WHERE ($1::text IS NULL OR EXISTS (
        SELECT 1 FROM permission_profile p
        WHERE p.id = profile_assignment.profile_id AND p.name ILIKE $1::text ESCAPE '\'))
  AND ($2::uuid IS NULL OR profile_id = $2::uuid)
  AND ($3::text[] IS NULL OR subject_type = ANY($3::text[]))
  AND ($4::uuid IS NULL OR subject_id = $4::uuid)
  AND ($5::uuid IS NULL OR device_group_id = $5::uuid)
ORDER BY
  CASE WHEN $6::text = 'created_at' THEN created_at END ASC,
  CASE WHEN $6::text = '-created_at' THEN created_at END DESC,
  CASE WHEN $6::text = 'subject_type' THEN subject_type END ASC,
  CASE WHEN $6::text = '-subject_type' THEN subject_type END DESC,
  id
LIMIT $8 OFFSET $7
`

type ListProfileAssignmentsParams struct {
	QPattern      *string
	ProfileID     uuid.NullUUID
	SubjectTypes  []string
	SubjectID     uuid.NullUUID
	DeviceGroupID uuid.NullUUID
	Sort          string
	SkipRows      int32
	MaxRows       int32
}

// The search matches the profile's name.
func (q *Queries) ListProfileAssignments(ctx context.Context, arg ListProfileAssignmentsParams) ([]ProfileAssignment, error) {
	rows, err := q.db.Query(ctx, listProfileAssignments,
		arg.QPattern,
		arg.ProfileID,
		arg.SubjectTypes,
		arg.SubjectID,
		arg.DeviceGroupID,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileAssignment{}
	for rows.Next() {
		var i ProfileAssignment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProfileID,
			&i.SubjectType,
			&i.SubjectID,
			&i.DeviceGroupID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermissionProfile = `-- name: UpdatePermissionProfile :one
UPDATE permission_profile
SET name = $1, class = $2, commands = $3, require_password = $4,
    timestamp_timeout_min = $5, lecture = $6, updated_at = now()
WHERE id = $7
RETURNING id, organization_id, name, class, commands, require_password, timestamp_timeout_min, lecture, created_at, updated_at
`

type UpdatePermissionProfileParams struct {
	Name                string
	Class               string
	Commands            []string
	RequirePassword     bool
	TimestampTimeoutMin int32
	Lecture             string
	ID                  uuid.UUID
}

func (q *Queries) UpdatePermissionProfile(ctx context.Context, arg UpdatePermissionProfileParams) (PermissionProfile, error) {
	row := q.db.QueryRow(ctx, updatePermissionProfile,
		arg.Name,
		arg.Class,
		arg.Commands,
		arg.RequirePassword,
		arg.TimestampTimeoutMin,
		arg.Lecture,
		arg.ID,
	)
	var i PermissionProfile
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Class,
		&i.Commands,
		&i.RequirePassword,
		&i.TimestampTimeoutMin,
		&i.Lecture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfileAssignmentScope = `-- name: UpdateProfileAssignmentScope :one
UPDATE profile_assignment SET device_group_id = $1 WHERE id = $2 RETURNING id, organization_id, profile_id, subject_type, subject_id, device_group_id, created_at
`

type UpdateProfileAssignmentScopeParams struct {
	DeviceGroupID uuid.NullUUID
	ID            uuid.UUID
}

func (q *Queries) UpdateProfileAssignmentScope(ctx context.Context, arg UpdateProfileAssignmentScopeParams) (ProfileAssignment, error) {
	row := q.db.QueryRow(ctx, updateProfileAssignmentScope, arg.DeviceGroupID, arg.ID)
	var i ProfileAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProfileID,
		&i.SubjectType,
		&i.SubjectID,
		&i.DeviceGroupID,
		&i.CreatedAt,
	)
	return i, err
}
