// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revocation.sql

package pgstore

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const activeRevocationFreeze = `-- name: ActiveRevocationFreeze :one
SELECT frozen_until FROM revocation_freeze
WHERE admin_id = $1 AND frozen_until > $2::timestamptz
ORDER BY frozen_until DESC LIMIT 1
`

type ActiveRevocationFreezeParams struct {
	AdminID uuid.UUID
	Now     time.Time
}

// The latest end of a freeze of the administrator that is still running at now (no rows if none).
func (q *Queries) ActiveRevocationFreeze(ctx context.Context, arg ActiveRevocationFreezeParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, activeRevocationFreeze, arg.AdminID, arg.Now)
	var frozen_until time.Time
	err := row.Scan(&frozen_until)
	return frozen_until, err
}

const approveRevocationRequest = `-- name: ApproveRevocationRequest :one
UPDATE revocation_request SET status = 'approved', approved_at = $1::timestamptz
WHERE id = $2 AND status = 'requested'
RETURNING id, organization_id, device_id, action, status, requested_by, requested_at, reason, approved_at, issued_at, expires_at, envelope, period_days, delivered_at, confirmed_at, finished_at, rejection, result, volumes
`

type ApproveRevocationRequestParams struct {
	ApprovedAt time.Time
	ID         uuid.UUID
}

// A Destroy's second approval, or a Lock's own: approved, handed to the issuer.
func (q *Queries) ApproveRevocationRequest(ctx context.Context, arg ApproveRevocationRequestParams) (RevocationRequest, error) {
	row := q.db.QueryRow(ctx, approveRevocationRequest, arg.ApprovedAt, arg.ID)
	var i RevocationRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.Action,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Reason,
		&i.ApprovedAt,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Envelope,
		&i.PeriodDays,
		&i.DeliveredAt,
		&i.ConfirmedAt,
		&i.FinishedAt,
		&i.Rejection,
		&i.Result,
		&i.Volumes,
	)
	return i, err
}

const clearRevocationStepUpTokens = `-- name: ClearRevocationStepUpTokens :execrows
UPDATE revocation_approval a SET stepup_id_token = NULL
FROM revocation_request r
WHERE r.id = a.request_id AND a.stepup_id_token IS NOT NULL AND r.finished_at < $1::timestamptz
`

// Raw step-up tokens are deleted 30 days after their request reached a final state (plan M4c decision 5).
func (q *Queries) ClearRevocationStepUpTokens(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, clearRevocationStepUpTokens, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeRevocationRequest = `-- name: CloseRevocationRequest :one
UPDATE revocation_request SET status = $1, finished_at = $2::timestamptz,
  rejection = $3
WHERE id = $4 AND status IN ('requested','approved')
RETURNING id, organization_id, device_id, action, status, requested_by, requested_at, reason, approved_at, issued_at, expires_at, envelope, period_days, delivered_at, confirmed_at, finished_at, rejection, result, volumes
`

type CloseRevocationRequestParams struct {
	Status     string
	FinishedAt time.Time
	Rejection  *string
	ID         uuid.UUID
}

// Reject or cancel a request before issuance.
func (q *Queries) CloseRevocationRequest(ctx context.Context, arg CloseRevocationRequestParams) (RevocationRequest, error) {
	row := q.db.QueryRow(ctx, closeRevocationRequest,
		arg.Status,
		arg.FinishedAt,
		arg.Rejection,
		arg.ID,
	)
	var i RevocationRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.Action,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Reason,
		&i.ApprovedAt,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Envelope,
		&i.PeriodDays,
		&i.DeliveredAt,
		&i.ConfirmedAt,
		&i.FinishedAt,
		&i.Rejection,
		&i.Result,
		&i.Volumes,
	)
	return i, err
}

const countIssuedRevocations = `-- name: CountIssuedRevocations :one
SELECT count(*) FROM revocation_request
WHERE action IN ('lock','destroy') AND issued_at > $1::timestamptz
`

// Issued Lock and Destroy requests of the organization since a moment.
func (q *Queries) CountIssuedRevocations(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuedRevocations, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuedRevocationsByAdmin = `-- name: CountIssuedRevocationsByAdmin :one
SELECT count(*) FROM revocation_request
WHERE requested_by = $1 AND action IN ('lock','destroy') AND issued_at > $2::timestamptz
`

type CountIssuedRevocationsByAdminParams struct {
	AdminID uuid.NullUUID
	Since   time.Time
}

// Issued Lock and Destroy requests of an administrator since a moment (ADR 0014 sliding windows).
func (q *Queries) CountIssuedRevocationsByAdmin(ctx context.Context, arg CountIssuedRevocationsByAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuedRevocationsByAdmin, arg.AdminID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRevocationRequests = `-- name: CountRevocationRequests :one
SELECT count(*) FROM (
  SELECT 1 FROM revocation_request JOIN device ON device.id = revocation_request.device_id
  WHERE ($1::text IS NULL
         OR device.hostname ILIKE $1::text ESCAPE '\'
         OR revocation_request.reason ILIKE $1::text ESCAPE '\')
    AND ($2::text[] IS NULL OR revocation_request.status = ANY($2::text[]))
    AND ($3::text[] IS NULL OR revocation_request.action = ANY($3::text[]))
    AND ($4::uuid IS NULL OR revocation_request.device_id = $4::uuid)
  LIMIT $5
) matching
`

type CountRevocationRequestsParams struct {
	QPattern   *string
	Statuses   []string
	Actions    []string
	DeviceID   uuid.NullUUID
	CountLimit int32
}

func (q *Queries) CountRevocationRequests(ctx context.Context, arg CountRevocationRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRevocationRequests,
		arg.QPattern,
		arg.Statuses,
		arg.Actions,
		arg.DeviceID,
		arg.CountLimit,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeviceLUKSEscrows = `-- name: DeleteDeviceLUKSEscrows :many
DELETE FROM escrow_secret WHERE device_id = $1 AND kind IN ('luks_recovery_key','luks_header')
RETURNING kind
`

// Crypto-shredding of a Destroy (plan M4c decision 9): every recovery key and header generation of the device.
func (q *Queries) DeleteDeviceLUKSEscrows(ctx context.Context, deviceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteDeviceLUKSEscrows, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var kind string
		if err := rows.Scan(&kind); err != nil {
			return nil, err
		}
		items = append(items, kind)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deviceEscrowDestroyed = `-- name: DeviceEscrowDestroyed :one
SELECT EXISTS (SELECT 1 FROM revocation_request
               WHERE device_id = $1 AND action = 'destroy' AND status IN ('issued','delivered','confirmed','expired'))
`

// Whether a Destroy of the device was issued: its escrow is gone for good.
func (q *Queries) DeviceEscrowDestroyed(ctx context.Context, deviceID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, deviceEscrowDestroyed, deviceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deviceRevokeCapable = `-- name: DeviceRevokeCapable :one
SELECT coalesce((SELECT (health -> 'revoke_capabilities') ? 'volumes' FROM device_status WHERE device_id = $1),
                false)::boolean
`

// Whether the device's paddock-revoke reported that it understands the volumes of a token (revoke_capabilities in
// the check-in health); builds before PDK-009 refuse such tokens.
func (q *Queries) DeviceRevokeCapable(ctx context.Context, deviceID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, deviceRevokeCapable, deviceID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const expireRevocations = `-- name: ExpireRevocations :many
UPDATE revocation_request SET status = 'expired', finished_at = $1::timestamptz
WHERE status IN ('issued','delivered') AND expires_at <= $1::timestamptz
RETURNING id, device_id
`

type ExpireRevocationsRow struct {
	ID       uuid.UUID
	DeviceID uuid.UUID
}

func (q *Queries) ExpireRevocations(ctx context.Context, now time.Time) ([]ExpireRevocationsRow, error) {
	rows, err := q.db.Query(ctx, expireRevocations, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireRevocationsRow{}
	for rows.Next() {
		var i ExpireRevocationsRow
		if err := rows.Scan(&i.ID, &i.DeviceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishRevocation = `-- name: FinishRevocation :one
UPDATE revocation_request SET status = $1, result = $2, confirmed_at = $3::timestamptz,
  finished_at = $3::timestamptz, delivered_at = coalesce(delivered_at, $3::timestamptz)
WHERE id = $4 AND device_id = $5 AND status IN ('issued','delivered')
RETURNING id, organization_id, device_id, action, status, requested_by, requested_at, reason, approved_at, issued_at, expires_at, envelope, period_days, delivered_at, confirmed_at, finished_at, rejection, result, volumes
`

type FinishRevocationParams struct {
	Status      string
	Result      json.RawMessage
	ConfirmedAt time.Time
	ID          uuid.UUID
	DeviceID    uuid.UUID
}

// The device's confirmation: the first result counts.
func (q *Queries) FinishRevocation(ctx context.Context, arg FinishRevocationParams) (RevocationRequest, error) {
	row := q.db.QueryRow(ctx, finishRevocation,
		arg.Status,
		arg.Result,
		arg.ConfirmedAt,
		arg.ID,
		arg.DeviceID,
	)
	var i RevocationRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.Action,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Reason,
		&i.ApprovedAt,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Envelope,
		&i.PeriodDays,
		&i.DeliveredAt,
		&i.ConfirmedAt,
		&i.FinishedAt,
		&i.Rejection,
		&i.Result,
		&i.Volumes,
	)
	return i, err
}

const getRevocationRequest = `-- name: GetRevocationRequest :one
SELECT id, organization_id, device_id, action, status, requested_by, requested_at, reason, approved_at, issued_at, expires_at, envelope, period_days, delivered_at, confirmed_at, finished_at, rejection, result, volumes FROM revocation_request WHERE id = $1
`

func (q *Queries) GetRevocationRequest(ctx context.Context, id uuid.UUID) (RevocationRequest, error) {
	row := q.db.QueryRow(ctx, getRevocationRequest, id)
	var i RevocationRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.Action,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Reason,
		&i.ApprovedAt,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Envelope,
		&i.PeriodDays,
		&i.DeliveredAt,
		&i.ConfirmedAt,
		&i.FinishedAt,
		&i.Rejection,
		&i.Result,
		&i.Volumes,
	)
	return i, err
}

const getRevocationRequestForUpdate = `-- name: GetRevocationRequestForUpdate :one
SELECT id, organization_id, device_id, action, status, requested_by, requested_at, reason, approved_at, issued_at, expires_at, envelope, period_days, delivered_at, confirmed_at, finished_at, rejection, result, volumes FROM revocation_request WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRevocationRequestForUpdate(ctx context.Context, id uuid.UUID) (RevocationRequest, error) {
	row := q.db.QueryRow(ctx, getRevocationRequestForUpdate, id)
	var i RevocationRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.Action,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Reason,
		&i.ApprovedAt,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Envelope,
		&i.PeriodDays,
		&i.DeliveredAt,
		&i.ConfirmedAt,
		&i.FinishedAt,
		&i.Rejection,
		&i.Result,
		&i.Volumes,
	)
	return i, err
}

const getRevocationRequestRow = `-- name: GetRevocationRequestRow :one
SELECT revocation_request.id, revocation_request.organization_id, revocation_request.device_id, revocation_request.action, revocation_request.status, revocation_request.requested_by, revocation_request.requested_at, revocation_request.reason, revocation_request.approved_at, revocation_request.issued_at, revocation_request.expires_at, revocation_request.envelope, revocation_request.period_days, revocation_request.delivered_at, revocation_request.confirmed_at, revocation_request.finished_at, revocation_request.rejection, revocation_request.result, revocation_request.volumes, device.hostname, coalesce(ac.username, '')::text AS requested_by_username
FROM revocation_request JOIN device ON device.id = revocation_request.device_id
LEFT JOIN admin_account ac ON ac.id = revocation_request.requested_by
WHERE revocation_request.id = $1
`

type GetRevocationRequestRowRow struct {
	RevocationRequest   RevocationRequest
	Hostname            string
	RequestedByUsername string
}

func (q *Queries) GetRevocationRequestRow(ctx context.Context, id uuid.UUID) (GetRevocationRequestRowRow, error) {
	row := q.db.QueryRow(ctx, getRevocationRequestRow, id)
	var i GetRevocationRequestRowRow
	err := row.Scan(
		&i.RevocationRequest.ID,
		&i.RevocationRequest.OrganizationID,
		&i.RevocationRequest.DeviceID,
		&i.RevocationRequest.Action,
		&i.RevocationRequest.Status,
		&i.RevocationRequest.RequestedBy,
		&i.RevocationRequest.RequestedAt,
		&i.RevocationRequest.Reason,
		&i.RevocationRequest.ApprovedAt,
		&i.RevocationRequest.IssuedAt,
		&i.RevocationRequest.ExpiresAt,
		&i.RevocationRequest.Envelope,
		&i.RevocationRequest.PeriodDays,
		&i.RevocationRequest.DeliveredAt,
		&i.RevocationRequest.ConfirmedAt,
		&i.RevocationRequest.FinishedAt,
		&i.RevocationRequest.Rejection,
		&i.RevocationRequest.Result,
		&i.RevocationRequest.Volumes,
		&i.Hostname,
		&i.RequestedByUsername,
	)
	return i, err
}

const insertRevocationApproval = `-- name: InsertRevocationApproval :exec
INSERT INTO revocation_approval (request_id, organization_id, role, admin_id, subject, stepup_jti, stepup_id_token,
                                 approved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRevocationApprovalParams struct {
	RequestID      uuid.UUID
	OrganizationID uuid.UUID
	Role           string
	AdminID        uuid.UUID
	Subject        string
	StepupJti      string
	StepupIDToken  *string
	ApprovedAt     time.Time
}

func (q *Queries) InsertRevocationApproval(ctx context.Context, arg InsertRevocationApprovalParams) error {
	_, err := q.db.Exec(ctx, insertRevocationApproval,
		arg.RequestID,
		arg.OrganizationID,
		arg.Role,
		arg.AdminID,
		arg.Subject,
		arg.StepupJti,
		arg.StepupIDToken,
		arg.ApprovedAt,
	)
	return err
}

const insertRevocationFreeze = `-- name: InsertRevocationFreeze :exec
INSERT INTO revocation_freeze (organization_id, admin_id, request_id, frozen_at, frozen_until)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertRevocationFreezeParams struct {
	OrganizationID uuid.UUID
	AdminID        uuid.UUID
	RequestID      uuid.UUID
	FrozenAt       time.Time
	FrozenUntil    time.Time
}

func (q *Queries) InsertRevocationFreeze(ctx context.Context, arg InsertRevocationFreezeParams) error {
	_, err := q.db.Exec(ctx, insertRevocationFreeze,
		arg.OrganizationID,
		arg.AdminID,
		arg.RequestID,
		arg.FrozenAt,
		arg.FrozenUntil,
	)
	return err
}

const insertRevocationRequest = `-- name: InsertRevocationRequest :one

INSERT INTO revocation_request (id, organization_id, device_id, action, status, requested_by, requested_at, reason,
                                approved_at, period_days)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10)
RETURNING id, organization_id, device_id, action, status, requested_by, requested_at, reason, approved_at, issued_at, expires_at, envelope, period_days, delivered_at, confirmed_at, finished_at, rejection, result, volumes
`

type InsertRevocationRequestParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	Action         string
	Status         string
	RequestedBy    uuid.NullUUID
	RequestedAt    time.Time
	Reason         string
	ApprovedAt     *time.Time
	PeriodDays     *int32
}

// Revocation requests and approvals (plan M4c decisions 5, 7–10). The raw step-up ID token is read only by the
// issuer (ListRevocationApprovalTokens); every other query leaves it out.
func (q *Queries) InsertRevocationRequest(ctx context.Context, arg InsertRevocationRequestParams) (RevocationRequest, error) {
	row := q.db.QueryRow(ctx, insertRevocationRequest,
		arg.ID,
		arg.OrganizationID,
		arg.DeviceID,
		arg.Action,
		arg.Status,
		arg.RequestedBy,
		arg.RequestedAt,
		arg.Reason,
		arg.ApprovedAt,
		arg.PeriodDays,
	)
	var i RevocationRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.Action,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Reason,
		&i.ApprovedAt,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Envelope,
		&i.PeriodDays,
		&i.DeliveredAt,
		&i.ConfirmedAt,
		&i.FinishedAt,
		&i.Rejection,
		&i.Result,
		&i.Volumes,
	)
	return i, err
}

const insertSelfLock = `-- name: InsertSelfLock :one
INSERT INTO revocation_request (id, organization_id, device_id, action, status, requested_at, approved_at, issued_at,
                                expires_at, envelope, period_days, volumes)
VALUES ($1, $2, $3, 'self_lock', 'issued', $4, $4, $4, $5,
        $6, $7, $8::uuid[])
RETURNING id, organization_id, device_id, action, status, requested_by, requested_at, reason, approved_at, issued_at, expires_at, envelope, period_days, delivered_at, confirmed_at, finished_at, rejection, result, volumes
`

type InsertSelfLockParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	IssuedAt       time.Time
	ExpiresAt      *time.Time
	Envelope       []byte
	PeriodDays     *int32
	Volumes        []uuid.UUID
}

// A self-lock token of the dead man's switch: no approvals, no limits (plan M4c decision 15).
func (q *Queries) InsertSelfLock(ctx context.Context, arg InsertSelfLockParams) (RevocationRequest, error) {
	row := q.db.QueryRow(ctx, insertSelfLock,
		arg.ID,
		arg.OrganizationID,
		arg.DeviceID,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.Envelope,
		arg.PeriodDays,
		arg.Volumes,
	)
	var i RevocationRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.Action,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Reason,
		&i.ApprovedAt,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Envelope,
		&i.PeriodDays,
		&i.DeliveredAt,
		&i.ConfirmedAt,
		&i.FinishedAt,
		&i.Rejection,
		&i.Result,
		&i.Volumes,
	)
	return i, err
}

const issueRevocationRequest = `-- name: IssueRevocationRequest :one
UPDATE revocation_request SET status = 'issued', issued_at = $1::timestamptz,
  expires_at = $2::timestamptz, envelope = $3, volumes = $4::uuid[]
WHERE id = $5 AND status = 'approved'
RETURNING id, organization_id, device_id, action, status, requested_by, requested_at, reason, approved_at, issued_at, expires_at, envelope, period_days, delivered_at, confirmed_at, finished_at, rejection, result, volumes
`

type IssueRevocationRequestParams struct {
	IssuedAt  time.Time
	ExpiresAt time.Time
	Envelope  []byte
	Volumes   []uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) IssueRevocationRequest(ctx context.Context, arg IssueRevocationRequestParams) (RevocationRequest, error) {
	row := q.db.QueryRow(ctx, issueRevocationRequest,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.Envelope,
		arg.Volumes,
		arg.ID,
	)
	var i RevocationRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.Action,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Reason,
		&i.ApprovedAt,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Envelope,
		&i.PeriodDays,
		&i.DeliveredAt,
		&i.ConfirmedAt,
		&i.FinishedAt,
		&i.Rejection,
		&i.Result,
		&i.Volumes,
	)
	return i, err
}

const listApprovedRevocationRequests = `-- name: ListApprovedRevocationRequests :many
SELECT id FROM revocation_request WHERE status = 'approved' ORDER BY approved_at, id LIMIT 100
`

// Approved requests the issuer has not handled yet (a lost message, a failed attempt).
func (q *Queries) ListApprovedRevocationRequests(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listApprovedRevocationRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfirmedHeaderVolumes = `-- name: ListConfirmedHeaderVolumes :many
SELECT DISTINCT volume::uuid AS volume FROM escrow_secret
WHERE device_id = $1 AND kind = 'luks_header' AND status = 'stored' AND volume IS NOT NULL
ORDER BY 1
`

// The volumes of a device with a stored header (PDK-009 decision 6), sorted: a Lock erases exactly these besides the
// root volume. Headers without a volume (before PDK-009) are the root volume's, which a Lock erases anyway.
func (q *Queries) ListConfirmedHeaderVolumes(ctx context.Context, deviceID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listConfirmedHeaderVolumes, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var volume uuid.UUID
		if err := rows.Scan(&volume); err != nil {
			return nil, err
		}
		items = append(items, volume)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenRevocationTokens = `-- name: ListOpenRevocationTokens :many
SELECT id, device_id, expires_at::timestamptz AS expires_at, envelope FROM revocation_request
WHERE status IN ('issued','delivered') AND expires_at > $1::timestamptz
ORDER BY issued_at, id
`

type ListOpenRevocationTokensRow struct {
	ID        uuid.UUID
	DeviceID  uuid.UUID
	ExpiresAt time.Time
	Envelope  []byte
}

// Issued, unexpired tokens: the issuer makes sure each is in cmd:<device_id>.
func (q *Queries) ListOpenRevocationTokens(ctx context.Context, now time.Time) ([]ListOpenRevocationTokensRow, error) {
	rows, err := q.db.Query(ctx, listOpenRevocationTokens, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenRevocationTokensRow{}
	for rows.Next() {
		var i ListOpenRevocationTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.ExpiresAt,
			&i.Envelope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevocationApprovalTokens = `-- name: ListRevocationApprovalTokens :many
SELECT role, admin_id, subject, stepup_jti, coalesce(stepup_id_token, '')::text AS stepup_id_token, approved_at
FROM revocation_approval WHERE request_id = $1 ORDER BY approved_at
`

type ListRevocationApprovalTokensRow struct {
	Role          string
	AdminID       uuid.UUID
	Subject       string
	StepupJti     string
	StepupIDToken string
	ApprovedAt    time.Time
}

// The issuer's view: the raw step-up ID token of every approval of a request.
func (q *Queries) ListRevocationApprovalTokens(ctx context.Context, requestID uuid.UUID) ([]ListRevocationApprovalTokensRow, error) {
	rows, err := q.db.Query(ctx, listRevocationApprovalTokens, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevocationApprovalTokensRow{}
	for rows.Next() {
		var i ListRevocationApprovalTokensRow
		if err := rows.Scan(
			&i.Role,
			&i.AdminID,
			&i.Subject,
			&i.StepupJti,
			&i.StepupIDToken,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevocationApprovals = `-- name: ListRevocationApprovals :many
SELECT a.request_id, a.role, a.admin_id, a.subject, a.approved_at, coalesce(ac.username, '')::text AS username
FROM revocation_approval a LEFT JOIN admin_account ac ON ac.id = a.admin_id
WHERE a.request_id = ANY($1::uuid[])
ORDER BY a.request_id, a.approved_at
`

type ListRevocationApprovalsRow struct {
	RequestID  uuid.UUID
	Role       string
	AdminID    uuid.UUID
	Subject    string
	ApprovedAt time.Time
	Username   string
}

func (q *Queries) ListRevocationApprovals(ctx context.Context, requestIds []uuid.UUID) ([]ListRevocationApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listRevocationApprovals, requestIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevocationApprovalsRow{}
	for rows.Next() {
		var i ListRevocationApprovalsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.Role,
			&i.AdminID,
			&i.Subject,
			&i.ApprovedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevocationRequests = `-- name: ListRevocationRequests :many

SELECT revocation_request.id, revocation_request.organization_id, revocation_request.device_id, revocation_request.action, revocation_request.status, revocation_request.requested_by, revocation_request.requested_at, revocation_request.reason, revocation_request.approved_at, revocation_request.issued_at, revocation_request.expires_at, revocation_request.envelope, revocation_request.period_days, revocation_request.delivered_at, revocation_request.confirmed_at, revocation_request.finished_at, revocation_request.rejection, revocation_request.result, revocation_request.volumes, device.hostname, coalesce(ac.username, '')::text AS requested_by_username
FROM revocation_request JOIN device ON device.id = revocation_request.device_id
LEFT JOIN admin_account ac ON ac.id = revocation_request.requested_by
WHERE ($1::text IS NULL
       OR device.hostname ILIKE $1::text ESCAPE '\'
       OR revocation_request.reason ILIKE $1::text ESCAPE '\')
  AND ($2::text[] IS NULL OR revocation_request.status = ANY($2::text[]))
  AND ($3::text[] IS NULL OR revocation_request.action = ANY($3::text[]))
  AND ($4::uuid IS NULL OR revocation_request.device_id = $4::uuid)
ORDER BY
  CASE WHEN $5::text = 'requested_at' THEN requested_at END ASC,
  CASE WHEN $5::text = '-requested_at' THEN requested_at END DESC,
  CASE WHEN $5::text = 'status' THEN status END ASC,
  CASE WHEN $5::text = '-status' THEN status END DESC,
  CASE WHEN $5::text = 'action' THEN action END ASC,
  CASE WHEN $5::text = '-action' THEN action END DESC,
  CASE WHEN $5::text = 'hostname' THEN hostname END ASC,
  CASE WHEN $5::text = '-hostname' THEN hostname END DESC,
  revocation_request.id
LIMIT $7 OFFSET $6
`

type ListRevocationRequestsParams struct {
	QPattern *string
	Statuses []string
	Actions  []string
	DeviceID uuid.NullUUID
	Sort     string
	SkipRows int32
	MaxRows  int32
}

type ListRevocationRequestsRow struct {
	RevocationRequest   RevocationRequest
	Hostname            string
	RequestedByUsername string
}

// List queries (ADR 0018): see device_group.sql.
func (q *Queries) ListRevocationRequests(ctx context.Context, arg ListRevocationRequestsParams) ([]ListRevocationRequestsRow, error) {
	rows, err := q.db.Query(ctx, listRevocationRequests,
		arg.QPattern,
		arg.Statuses,
		arg.Actions,
		arg.DeviceID,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevocationRequestsRow{}
	for rows.Next() {
		var i ListRevocationRequestsRow
		if err := rows.Scan(
			&i.RevocationRequest.ID,
			&i.RevocationRequest.OrganizationID,
			&i.RevocationRequest.DeviceID,
			&i.RevocationRequest.Action,
			&i.RevocationRequest.Status,
			&i.RevocationRequest.RequestedBy,
			&i.RevocationRequest.RequestedAt,
			&i.RevocationRequest.Reason,
			&i.RevocationRequest.ApprovedAt,
			&i.RevocationRequest.IssuedAt,
			&i.RevocationRequest.ExpiresAt,
			&i.RevocationRequest.Envelope,
			&i.RevocationRequest.PeriodDays,
			&i.RevocationRequest.DeliveredAt,
			&i.RevocationRequest.ConfirmedAt,
			&i.RevocationRequest.FinishedAt,
			&i.RevocationRequest.Rejection,
			&i.RevocationRequest.Result,
			&i.RevocationRequest.Volumes,
			&i.Hostname,
			&i.RequestedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRevocationsDelivered = `-- name: MarkRevocationsDelivered :execrows
UPDATE revocation_request SET status = 'delivered', delivered_at = $1::timestamptz
WHERE device_id = $2 AND id = ANY($3::uuid[]) AND status = 'issued'
`

type MarkRevocationsDeliveredParams struct {
	DeliveredAt time.Time
	DeviceID    uuid.UUID
	Ids         []uuid.UUID
}

func (q *Queries) MarkRevocationsDelivered(ctx context.Context, arg MarkRevocationsDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRevocationsDelivered, arg.DeliveredAt, arg.DeviceID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stepUpUsedForRevocation = `-- name: StepUpUsedForRevocation :one
SELECT EXISTS (SELECT 1 FROM revocation_approval WHERE stepup_jti = $1)
`

// Whether a step-up token was used for an approval already: one token per approval (plan M4c decision 8).
func (q *Queries) StepUpUsedForRevocation(ctx context.Context, stepupJti string) (bool, error) {
	row := q.db.QueryRow(ctx, stepUpUsedForRevocation, stepupJti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
