// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staleness.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearDeviceAlerts = `-- name: ClearDeviceAlerts :execrows
UPDATE device_alert SET cleared_at = $1::timestamptz WHERE device_id = $2 AND cleared_at IS NULL
`

type ClearDeviceAlertsParams struct {
	Now      time.Time
	DeviceID uuid.UUID
}

func (q *Queries) ClearDeviceAlerts(ctx context.Context, arg ClearDeviceAlertsParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearDeviceAlerts, arg.Now, arg.DeviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearPresumedLost = `-- name: ClearPresumedLost :exec
UPDATE device_status SET presumed_lost_at = NULL WHERE device_id = $1 AND presumed_lost_at IS NOT NULL
`

func (q *Queries) ClearPresumedLost(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPresumedLost, deviceID)
	return err
}

const getDeviceLastContact = `-- name: GetDeviceLastContact :one
SELECT last_contact_at FROM device_status WHERE device_id = $1
`

func (q *Queries) GetDeviceLastContact(ctx context.Context, deviceID uuid.UUID) (*time.Time, error) {
	row := q.db.QueryRow(ctx, getDeviceLastContact, deviceID)
	var last_contact_at *time.Time
	err := row.Scan(&last_contact_at)
	return last_contact_at, err
}

const getOpenDeviceAlertKind = `-- name: GetOpenDeviceAlertKind :one
SELECT kind FROM device_alert WHERE device_id = $1 AND cleared_at IS NULL
`

func (q *Queries) GetOpenDeviceAlertKind(ctx context.Context, deviceID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getOpenDeviceAlertKind, deviceID)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const listStalenessCandidates = `-- name: ListStalenessCandidates :many

SELECT d.id, d.state, s.last_contact_at, a.kind AS open_kind
FROM device d
LEFT JOIN device_status s ON s.device_id = d.id
LEFT JOIN device_alert a ON a.device_id = d.id AND a.cleared_at IS NULL
WHERE d.state = 'active' OR a.id IS NOT NULL
ORDER BY d.id
`

type ListStalenessCandidatesRow struct {
	ID            uuid.UUID
	State         string
	LastContactAt *time.Time
	OpenKind      *string
}

// Staleness alerts (plan M5b decision 10): at most one open alert per device.
// Active devices with their last contact and open alert, and devices that are no longer active but still have one.
func (q *Queries) ListStalenessCandidates(ctx context.Context) ([]ListStalenessCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listStalenessCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStalenessCandidatesRow{}
	for rows.Next() {
		var i ListStalenessCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.LastContactAt,
			&i.OpenKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const raiseDeviceAlert = `-- name: RaiseDeviceAlert :execrows
INSERT INTO device_alert (id, organization_id, device_id, kind, raised_at)
VALUES ($1, $2, $3, $4, $5::timestamptz)
ON CONFLICT (device_id) WHERE cleared_at IS NULL DO NOTHING
`

type RaiseDeviceAlertParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceID       uuid.UUID
	Kind           string
	Now            time.Time
}

func (q *Queries) RaiseDeviceAlert(ctx context.Context, arg RaiseDeviceAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, raiseDeviceAlert,
		arg.ID,
		arg.OrganizationID,
		arg.DeviceID,
		arg.Kind,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPresumedLost = `-- name: SetPresumedLost :exec
UPDATE device_status SET presumed_lost_at = $1::timestamptz WHERE device_id = $2 AND presumed_lost_at IS NULL
`

type SetPresumedLostParams struct {
	Now      time.Time
	DeviceID uuid.UUID
}

func (q *Queries) SetPresumedLost(ctx context.Context, arg SetPresumedLostParams) error {
	_, err := q.db.Exec(ctx, setPresumedLost, arg.Now, arg.DeviceID)
	return err
}
