// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updates.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const countPackageHolds = `-- name: CountPackageHolds :one
SELECT count(*) FROM (
  SELECT 1 FROM package_hold
  WHERE ($1::text IS NULL OR package ILIKE $1::text ESCAPE '\')
    AND ($2::uuid IS NULL OR device_group_id = $2::uuid)
  LIMIT $3
) matching
`

type CountPackageHoldsParams struct {
	QPattern      *string
	DeviceGroupID uuid.NullUUID
	CountLimit    int32
}

func (q *Queries) CountPackageHolds(ctx context.Context, arg CountPackageHoldsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPackageHolds, arg.QPattern, arg.DeviceGroupID, arg.CountLimit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePackageHold = `-- name: DeletePackageHold :execrows
DELETE FROM package_hold WHERE id = $1
`

func (q *Queries) DeletePackageHold(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePackageHold, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPackageHold = `-- name: GetPackageHold :one
SELECT id, organization_id, device_group_id, package, version, reason, created_by, created_at, updated_at FROM package_hold WHERE id = $1
`

func (q *Queries) GetPackageHold(ctx context.Context, id uuid.UUID) (PackageHold, error) {
	row := q.db.QueryRow(ctx, getPackageHold, id)
	var i PackageHold
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceGroupID,
		&i.Package,
		&i.Version,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUpdateSettings = `-- name: GetUpdateSettings :one

SELECT organization_id, security_daily_at, regular_schedule, regular_updates_enabled, max_random_delay_min, staleness_warning_h, staleness_critical_h, updated_at, updated_by FROM organization_update_settings
`

// Update management (plan M5b decisions 1–4 and 9). Without a settings row the defaults apply.
func (q *Queries) GetUpdateSettings(ctx context.Context) (OrganizationUpdateSetting, error) {
	row := q.db.QueryRow(ctx, getUpdateSettings)
	var i OrganizationUpdateSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.SecurityDailyAt,
		&i.RegularSchedule,
		&i.RegularUpdatesEnabled,
		&i.MaxRandomDelayMin,
		&i.StalenessWarningH,
		&i.StalenessCriticalH,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const insertPackageHold = `-- name: InsertPackageHold :one
INSERT INTO package_hold (id, organization_id, device_group_id, package, version, reason, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, device_group_id, package, version, reason, created_by, created_at, updated_at
`

type InsertPackageHoldParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DeviceGroupID  uuid.NullUUID
	Package        string
	Version        *string
	Reason         string
	CreatedBy      uuid.NullUUID
}

func (q *Queries) InsertPackageHold(ctx context.Context, arg InsertPackageHoldParams) (PackageHold, error) {
	row := q.db.QueryRow(ctx, insertPackageHold,
		arg.ID,
		arg.OrganizationID,
		arg.DeviceGroupID,
		arg.Package,
		arg.Version,
		arg.Reason,
		arg.CreatedBy,
	)
	var i PackageHold
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceGroupID,
		&i.Package,
		&i.Version,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPackageHolds = `-- name: ListAllPackageHolds :many
SELECT id, organization_id, device_group_id, package, version, reason, created_by, created_at, updated_at FROM package_hold ORDER BY package, device_group_id NULLS FIRST, id
`

// Every hold of the organization (compiler), in a stable order.
func (q *Queries) ListAllPackageHolds(ctx context.Context) ([]PackageHold, error) {
	rows, err := q.db.Query(ctx, listAllPackageHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageHold{}
	for rows.Next() {
		var i PackageHold
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeviceGroupID,
			&i.Package,
			&i.Version,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceHolds = `-- name: ListDeviceHolds :many
SELECT h.id, h.organization_id, h.device_group_id, h.package, h.version, h.reason, h.created_by, h.created_at, h.updated_at FROM package_hold h
WHERE h.device_group_id IS NULL
   OR h.device_group_id IN (SELECT m.device_group_id FROM device_group_member m WHERE m.device_id = $1)
ORDER BY h.package, h.device_group_id NULLS FIRST, h.id
`

// The holds that apply to a device: organization-wide and those of its device groups.
func (q *Queries) ListDeviceHolds(ctx context.Context, deviceID uuid.UUID) ([]PackageHold, error) {
	rows, err := q.db.Query(ctx, listDeviceHolds, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageHold{}
	for rows.Next() {
		var i PackageHold
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeviceGroupID,
			&i.Package,
			&i.Version,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembersHolds = `-- name: ListGroupMembersHolds :many
SELECT h.id, h.organization_id, h.device_group_id, h.package, h.version, h.reason, h.created_by, h.created_at, h.updated_at FROM package_hold h
WHERE h.device_group_id IS NULL
   OR h.device_group_id IN (
     SELECT m2.device_group_id FROM device_group_member m
     JOIN device d ON d.id = m.device_id AND d.state = 'active'
     JOIN device_group_member m2 ON m2.device_id = m.device_id
     WHERE m.device_group_id = $1)
ORDER BY h.package, h.id
`

// The holds that apply to any active member of a device group: organization-wide and those of every group of a
// member.
func (q *Queries) ListGroupMembersHolds(ctx context.Context, deviceGroupID uuid.UUID) ([]PackageHold, error) {
	rows, err := q.db.Query(ctx, listGroupMembersHolds, deviceGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageHold{}
	for rows.Next() {
		var i PackageHold
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeviceGroupID,
			&i.Package,
			&i.Version,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageHolds = `-- name: ListPackageHolds :many
SELECT id, organization_id, device_group_id, package, version, reason, created_by, created_at, updated_at FROM package_hold
WHERE ($1::text IS NULL OR package ILIKE $1::text ESCAPE '\')
  AND ($2::uuid IS NULL OR device_group_id = $2::uuid)
ORDER BY
  CASE WHEN $3::text = 'package' THEN package END ASC,
  CASE WHEN $3::text = '-package' THEN package END DESC,
  CASE WHEN $3::text = 'created_at' THEN created_at END ASC,
  CASE WHEN $3::text = '-created_at' THEN created_at END DESC,
  CASE WHEN $3::text = 'updated_at' THEN updated_at END ASC,
  CASE WHEN $3::text = '-updated_at' THEN updated_at END DESC,
  id
LIMIT $5 OFFSET $4
`

type ListPackageHoldsParams struct {
	QPattern      *string
	DeviceGroupID uuid.NullUUID
	Sort          string
	SkipRows      int32
	MaxRows       int32
}

func (q *Queries) ListPackageHolds(ctx context.Context, arg ListPackageHoldsParams) ([]PackageHold, error) {
	rows, err := q.db.Query(ctx, listPackageHolds,
		arg.QPattern,
		arg.DeviceGroupID,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageHold{}
	for rows.Next() {
		var i PackageHold
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeviceGroupID,
			&i.Package,
			&i.Version,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackageHold = `-- name: UpdatePackageHold :one
UPDATE package_hold SET version = $1, reason = $2, updated_at = now()
WHERE id = $3
RETURNING id, organization_id, device_group_id, package, version, reason, created_by, created_at, updated_at
`

type UpdatePackageHoldParams struct {
	Version *string
	Reason  string
	ID      uuid.UUID
}

func (q *Queries) UpdatePackageHold(ctx context.Context, arg UpdatePackageHoldParams) (PackageHold, error) {
	row := q.db.QueryRow(ctx, updatePackageHold, arg.Version, arg.Reason, arg.ID)
	var i PackageHold
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceGroupID,
		&i.Package,
		&i.Version,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUpdateSettings = `-- name: UpsertUpdateSettings :one
INSERT INTO organization_update_settings (organization_id, security_daily_at, regular_schedule, regular_updates_enabled,
  max_random_delay_min, staleness_warning_h, staleness_critical_h, updated_at, updated_by)
VALUES ($1, $2, $3, $4, $5,
  $6, $7, now(), $8)
ON CONFLICT (organization_id) DO UPDATE
SET security_daily_at = excluded.security_daily_at, regular_schedule = excluded.regular_schedule,
    regular_updates_enabled = excluded.regular_updates_enabled, max_random_delay_min = excluded.max_random_delay_min,
    staleness_warning_h = excluded.staleness_warning_h, staleness_critical_h = excluded.staleness_critical_h,
    updated_at = excluded.updated_at, updated_by = excluded.updated_by
RETURNING organization_id, security_daily_at, regular_schedule, regular_updates_enabled, max_random_delay_min, staleness_warning_h, staleness_critical_h, updated_at, updated_by
`

type UpsertUpdateSettingsParams struct {
	OrganizationID        uuid.UUID
	SecurityDailyAt       string
	RegularSchedule       string
	RegularUpdatesEnabled bool
	MaxRandomDelayMin     int32
	StalenessWarningH     int32
	StalenessCriticalH    int32
	UpdatedBy             uuid.NullUUID
}

func (q *Queries) UpsertUpdateSettings(ctx context.Context, arg UpsertUpdateSettingsParams) (OrganizationUpdateSetting, error) {
	row := q.db.QueryRow(ctx, upsertUpdateSettings,
		arg.OrganizationID,
		arg.SecurityDailyAt,
		arg.RegularSchedule,
		arg.RegularUpdatesEnabled,
		arg.MaxRandomDelayMin,
		arg.StalenessWarningH,
		arg.StalenessCriticalH,
		arg.UpdatedBy,
	)
	var i OrganizationUpdateSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.SecurityDailyAt,
		&i.RegularSchedule,
		&i.RegularUpdatesEnabled,
		&i.MaxRandomDelayMin,
		&i.StalenessWarningH,
		&i.StalenessCriticalH,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
