// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const countAppUsers = `-- name: CountAppUsers :one
SELECT count(*) FROM (
  SELECT 1 FROM app_user
  WHERE ($1::text IS NULL
         OR username ILIKE $1::text ESCAPE '\'
         OR display_name ILIKE $1::text ESCAPE '\'
         OR email ILIKE $1::text ESCAPE '\')
    AND ($2::text[] IS NULL OR source = ANY($2::text[]))
    AND ($3::boolean IS NULL OR locked = $3::boolean)
    AND ($4::uuid IS NULL OR EXISTS (
          SELECT 1 FROM user_group_member m WHERE m.user_id = app_user.id AND m.group_id = $4::uuid))
  LIMIT $5
) matching
`

type CountAppUsersParams struct {
	QPattern   *string
	Sources    []string
	Locked     *bool
	GroupID    uuid.NullUUID
	CountLimit int32
}

func (q *Queries) CountAppUsers(ctx context.Context, arg CountAppUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppUsers,
		arg.QPattern,
		arg.Sources,
		arg.Locked,
		arg.GroupID,
		arg.CountLimit,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserGroups = `-- name: CountUserGroups :one
SELECT count(*) FROM (
  SELECT 1 FROM user_group
  WHERE ($1::text IS NULL
         OR slug ILIKE $1::text ESCAPE '\'
         OR name ILIKE $1::text ESCAPE '\')
    AND ($2::text[] IS NULL OR source = ANY($2::text[]))
  LIMIT $3
) matching
`

type CountUserGroupsParams struct {
	QPattern   *string
	Sources    []string
	CountLimit int32
}

func (q *Queries) CountUserGroups(ctx context.Context, arg CountUserGroupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserGroups, arg.QPattern, arg.Sources, arg.CountLimit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAppUser = `-- name: DeleteAppUser :execrows
DELETE FROM app_user WHERE id = $1
`

func (q *Queries) DeleteAppUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserGroup = `-- name: DeleteUserGroup :execrows
DELETE FROM user_group WHERE id = $1
`

func (q *Queries) DeleteUserGroup(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserGroupMember = `-- name: DeleteUserGroupMember :execrows
DELETE FROM user_group_member WHERE group_id = $1 AND user_id = $2
`

type DeleteUserGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteUserGroupMember(ctx context.Context, arg DeleteUserGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserGroupMember, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppUser = `-- name: GetAppUser :one
SELECT id, organization_id, authentik_pk, username, display_name, email, source, locked, locked_at, created_at, updated_at FROM app_user WHERE id = $1
`

func (q *Queries) GetAppUser(ctx context.Context, id uuid.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUser, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthentikPk,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Source,
		&i.Locked,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserGroup = `-- name: GetUserGroup :one
SELECT id, organization_id, slug, name, source, upstream_authentik_pk, authentik_pk, created_at, updated_at FROM user_group WHERE id = $1
`

func (q *Queries) GetUserGroup(ctx context.Context, id uuid.UUID) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getUserGroup, id)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.Source,
		&i.UpstreamAuthentikPk,
		&i.AuthentikPk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAppUser = `-- name: InsertAppUser :one

INSERT INTO app_user (id, organization_id, authentik_pk, username, display_name, email, source)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, authentik_pk, username, display_name, email, source, locked, locked_at, created_at, updated_at
`

type InsertAppUserParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	AuthentikPk    string
	Username       string
	DisplayName    string
	Email          string
	Source         string
}

// Users and user groups of an organization (plan M3a decisions 2–4).
func (q *Queries) InsertAppUser(ctx context.Context, arg InsertAppUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, insertAppUser,
		arg.ID,
		arg.OrganizationID,
		arg.AuthentikPk,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Source,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthentikPk,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Source,
		&i.Locked,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserGroup = `-- name: InsertUserGroup :one
INSERT INTO user_group (id, organization_id, slug, name, source, upstream_authentik_pk)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, slug, name, source, upstream_authentik_pk, authentik_pk, created_at, updated_at
`

type InsertUserGroupParams struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	Slug                string
	Name                string
	Source              string
	UpstreamAuthentikPk *string
}

func (q *Queries) InsertUserGroup(ctx context.Context, arg InsertUserGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, insertUserGroup,
		arg.ID,
		arg.OrganizationID,
		arg.Slug,
		arg.Name,
		arg.Source,
		arg.UpstreamAuthentikPk,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.Source,
		&i.UpstreamAuthentikPk,
		&i.AuthentikPk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserGroupMember = `-- name: InsertUserGroupMember :execrows
INSERT INTO user_group_member (organization_id, group_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertUserGroupMemberParams struct {
	OrganizationID uuid.UUID
	GroupID        uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) InsertUserGroupMember(ctx context.Context, arg InsertUserGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUserGroupMember, arg.OrganizationID, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAllAppUsers = `-- name: ListAllAppUsers :many
SELECT id, organization_id, authentik_pk, username, display_name, email, source, locked, locked_at, created_at, updated_at FROM app_user ORDER BY id
`

func (q *Queries) ListAllAppUsers(ctx context.Context) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, listAllAppUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUser{}
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AuthentikPk,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Source,
			&i.Locked,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUserGroupMembers = `-- name: ListAllUserGroupMembers :many
SELECT group_id, user_id FROM user_group_member ORDER BY group_id, user_id
`

type ListAllUserGroupMembersRow struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) ListAllUserGroupMembers(ctx context.Context) ([]ListAllUserGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listAllUserGroupMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllUserGroupMembersRow{}
	for rows.Next() {
		var i ListAllUserGroupMembersRow
		if err := rows.Scan(&i.GroupID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUserGroups = `-- name: ListAllUserGroups :many
SELECT id, organization_id, slug, name, source, upstream_authentik_pk, authentik_pk, created_at, updated_at FROM user_group ORDER BY id
`

func (q *Queries) ListAllUserGroups(ctx context.Context) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listAllUserGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserGroup{}
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Slug,
			&i.Name,
			&i.Source,
			&i.UpstreamAuthentikPk,
			&i.AuthentikPk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppUsers = `-- name: ListAppUsers :many

SELECT id, organization_id, authentik_pk, username, display_name, email, source, locked, locked_at, created_at, updated_at FROM app_user
WHERE ($1::text IS NULL
       OR username ILIKE $1::text ESCAPE '\'
       OR display_name ILIKE $1::text ESCAPE '\'
       OR email ILIKE $1::text ESCAPE '\')
  AND ($2::text[] IS NULL OR source = ANY($2::text[]))
  AND ($3::boolean IS NULL OR locked = $3::boolean)
  AND ($4::uuid IS NULL OR EXISTS (
        SELECT 1 FROM user_group_member m WHERE m.user_id = app_user.id AND m.group_id = $4::uuid))
ORDER BY
  CASE WHEN $5::text = 'username' THEN username END ASC,
  CASE WHEN $5::text = '-username' THEN username END DESC,
  CASE WHEN $5::text = 'display_name' THEN display_name END ASC,
  CASE WHEN $5::text = '-display_name' THEN display_name END DESC,
  CASE WHEN $5::text = 'created_at' THEN created_at END ASC,
  CASE WHEN $5::text = '-created_at' THEN created_at END DESC,
  id
LIMIT $7 OFFSET $6
`

type ListAppUsersParams struct {
	QPattern *string
	Sources  []string
	Locked   *bool
	GroupID  uuid.NullUUID
	Sort     string
	SkipRows int32
	MaxRows  int32
}

// List queries (ADR 0018): see device_group.sql. group_id limits the list to the members of one group.
func (q *Queries) ListAppUsers(ctx context.Context, arg ListAppUsersParams) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, listAppUsers,
		arg.QPattern,
		arg.Sources,
		arg.Locked,
		arg.GroupID,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUser{}
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AuthentikPk,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Source,
			&i.Locked,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsOfUser = `-- name: ListGroupsOfUser :many
SELECT g.id, g.organization_id, g.slug, g.name, g.source, g.upstream_authentik_pk, g.authentik_pk, g.created_at, g.updated_at FROM user_group g JOIN user_group_member m ON m.group_id = g.id
WHERE m.user_id = $1
ORDER BY g.name, g.id
`

func (q *Queries) ListGroupsOfUser(ctx context.Context, userID uuid.UUID) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserGroup{}
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Slug,
			&i.Name,
			&i.Source,
			&i.UpstreamAuthentikPk,
			&i.AuthentikPk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroupMemberIDs = `-- name: ListUserGroupMemberIDs :many
SELECT user_id FROM user_group_member WHERE group_id = $1 ORDER BY user_id
`

func (q *Queries) ListUserGroupMemberIDs(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserGroupMemberIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT id, organization_id, slug, name, source, upstream_authentik_pk, authentik_pk, created_at, updated_at FROM user_group
WHERE ($1::text IS NULL
       OR slug ILIKE $1::text ESCAPE '\'
       OR name ILIKE $1::text ESCAPE '\')
  AND ($2::text[] IS NULL OR source = ANY($2::text[]))
ORDER BY
  CASE WHEN $3::text = 'name' THEN name END ASC,
  CASE WHEN $3::text = '-name' THEN name END DESC,
  CASE WHEN $3::text = 'slug' THEN slug END ASC,
  CASE WHEN $3::text = '-slug' THEN slug END DESC,
  CASE WHEN $3::text = 'created_at' THEN created_at END ASC,
  CASE WHEN $3::text = '-created_at' THEN created_at END DESC,
  id
LIMIT $5 OFFSET $4
`

type ListUserGroupsParams struct {
	QPattern *string
	Sources  []string
	Sort     string
	SkipRows int32
	MaxRows  int32
}

func (q *Queries) ListUserGroups(ctx context.Context, arg ListUserGroupsParams) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listUserGroups,
		arg.QPattern,
		arg.Sources,
		arg.Sort,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserGroup{}
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Slug,
			&i.Name,
			&i.Source,
			&i.UpstreamAuthentikPk,
			&i.AuthentikPk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAppUser = `-- name: LockAppUser :one
SELECT id, organization_id, authentik_pk, username, display_name, email, source, locked, locked_at, created_at, updated_at FROM app_user WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAppUser(ctx context.Context, id uuid.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, lockAppUser, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthentikPk,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Source,
		&i.Locked,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAppUserAuthentikPK = `-- name: SetAppUserAuthentikPK :exec
UPDATE app_user SET authentik_pk = $1, updated_at = now() WHERE id = $2
`

type SetAppUserAuthentikPKParams struct {
	AuthentikPk string
	ID          uuid.UUID
}

func (q *Queries) SetAppUserAuthentikPK(ctx context.Context, arg SetAppUserAuthentikPKParams) error {
	_, err := q.db.Exec(ctx, setAppUserAuthentikPK, arg.AuthentikPk, arg.ID)
	return err
}

const setAppUserLocked = `-- name: SetAppUserLocked :one
UPDATE app_user SET locked = $1, locked_at = CASE WHEN $1::boolean THEN coalesce(locked_at, now()) END,
  updated_at = now()
WHERE id = $2
RETURNING id, organization_id, authentik_pk, username, display_name, email, source, locked, locked_at, created_at, updated_at
`

type SetAppUserLockedParams struct {
	Locked bool
	ID     uuid.UUID
}

func (q *Queries) SetAppUserLocked(ctx context.Context, arg SetAppUserLockedParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, setAppUserLocked, arg.Locked, arg.ID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthentikPk,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Source,
		&i.Locked,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserGroupAuthentikPK = `-- name: SetUserGroupAuthentikPK :exec
UPDATE user_group SET authentik_pk = $1, updated_at = now() WHERE id = $2
`

type SetUserGroupAuthentikPKParams struct {
	AuthentikPk string
	ID          uuid.UUID
}

func (q *Queries) SetUserGroupAuthentikPK(ctx context.Context, arg SetUserGroupAuthentikPKParams) error {
	_, err := q.db.Exec(ctx, setUserGroupAuthentikPK, arg.AuthentikPk, arg.ID)
	return err
}

const updateAppUser = `-- name: UpdateAppUser :one
UPDATE app_user SET display_name = $1, email = $2, updated_at = now()
WHERE id = $3
RETURNING id, organization_id, authentik_pk, username, display_name, email, source, locked, locked_at, created_at, updated_at
`

type UpdateAppUserParams struct {
	DisplayName string
	Email       string
	ID          uuid.UUID
}

func (q *Queries) UpdateAppUser(ctx context.Context, arg UpdateAppUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateAppUser, arg.DisplayName, arg.Email, arg.ID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthentikPk,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Source,
		&i.Locked,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSyncedAppUser = `-- name: UpdateSyncedAppUser :exec
UPDATE app_user SET username = $1, display_name = $2, email = $3, updated_at = now()
WHERE id = $4 AND source = 'synced'
`

type UpdateSyncedAppUserParams struct {
	Username    string
	DisplayName string
	Email       string
	ID          uuid.UUID
}

// Worker synchronization of a synced user's upstream attributes.
func (q *Queries) UpdateSyncedAppUser(ctx context.Context, arg UpdateSyncedAppUserParams) error {
	_, err := q.db.Exec(ctx, updateSyncedAppUser,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.ID,
	)
	return err
}

const updateUserGroupName = `-- name: UpdateUserGroupName :one
UPDATE user_group SET name = $1, updated_at = now() WHERE id = $2 RETURNING id, organization_id, slug, name, source, upstream_authentik_pk, authentik_pk, created_at, updated_at
`

type UpdateUserGroupNameParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) UpdateUserGroupName(ctx context.Context, arg UpdateUserGroupNameParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, updateUserGroupName, arg.Name, arg.ID)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.Source,
		&i.UpstreamAuthentikPk,
		&i.AuthentikPk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
