//go:build go1.22

// Package adminapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package adminapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuditActorType.
const (
	AuditActorTypeAdmin         AuditActorType = "admin"
	AuditActorTypeAnonymous     AuditActorType = "anonymous"
	AuditActorTypePlatformAdmin AuditActorType = "platform_admin"
	AuditActorTypeSystem        AuditActorType = "system"
)

// Valid indicates whether the value is a known member of the AuditActorType enum.
func (e AuditActorType) Valid() bool {
	switch e {
	case AuditActorTypeAdmin:
		return true
	case AuditActorTypeAnonymous:
		return true
	case AuditActorTypePlatformAdmin:
		return true
	case AuditActorTypeSystem:
		return true
	default:
		return false
	}
}

// Defines values for AuditOutcome.
const (
	Denied  AuditOutcome = "denied"
	Failure AuditOutcome = "failure"
	Success AuditOutcome = "success"
	Unknown AuditOutcome = "unknown"
)

// Valid indicates whether the value is a known member of the AuditOutcome enum.
func (e AuditOutcome) Valid() bool {
	switch e {
	case Denied:
		return true
	case Failure:
		return true
	case Success:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for MeLocale.
const (
	MeLocaleEn MeLocale = "en"
)

// Valid indicates whether the value is a known member of the MeLocale enum.
func (e MeLocale) Valid() bool {
	switch e {
	case MeLocaleEn:
		return true
	default:
		return false
	}
}

// Defines values for MeRole.
const (
	MeRoleOrgAdmin      MeRole = "org_admin"
	MeRoleOrgAuditor    MeRole = "org_auditor"
	MeRoleOrgOperator   MeRole = "org_operator"
	MeRolePlatformAdmin MeRole = "platform_admin"
)

// Valid indicates whether the value is a known member of the MeRole enum.
func (e MeRole) Valid() bool {
	switch e {
	case MeRoleOrgAdmin:
		return true
	case MeRoleOrgAuditor:
		return true
	case MeRoleOrgOperator:
		return true
	case MeRolePlatformAdmin:
		return true
	default:
		return false
	}
}

// Defines values for MeUpdateLocale.
const (
	MeUpdateLocaleEn MeUpdateLocale = "en"
)

// Valid indicates whether the value is a known member of the MeUpdateLocale enum.
func (e MeUpdateLocale) Valid() bool {
	switch e {
	case MeUpdateLocaleEn:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationStatus.
const (
	Active             OrganizationStatus = "active"
	Provisioning       OrganizationStatus = "provisioning"
	ProvisioningFailed OrganizationStatus = "provisioning_failed"
	Suspended          OrganizationStatus = "suspended"
)

// Valid indicates whether the value is a known member of the OrganizationStatus enum.
func (e OrganizationStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Provisioning:
		return true
	case ProvisioningFailed:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// Defines values for AuditEventSort.
const (
	AuditEventSortCode            AuditEventSort = "code"
	AuditEventSortMinusCode       AuditEventSort = "-code"
	AuditEventSortMinusOccurredAt AuditEventSort = "-occurred_at"
	AuditEventSortMinusOutcome    AuditEventSort = "-outcome"
	AuditEventSortOccurredAt      AuditEventSort = "occurred_at"
	AuditEventSortOutcome         AuditEventSort = "outcome"
)

// Valid indicates whether the value is a known member of the AuditEventSort enum.
func (e AuditEventSort) Valid() bool {
	switch e {
	case AuditEventSortCode:
		return true
	case AuditEventSortMinusCode:
		return true
	case AuditEventSortMinusOccurredAt:
		return true
	case AuditEventSortMinusOutcome:
		return true
	case AuditEventSortOccurredAt:
		return true
	case AuditEventSortOutcome:
		return true
	default:
		return false
	}
}

// Defines values for Csrf.
const (
	CsrfN1 Csrf = "1"
)

// Valid indicates whether the value is a known member of the Csrf enum.
func (e Csrf) Valid() bool {
	switch e {
	case CsrfN1:
		return true
	default:
		return false
	}
}

// Defines values for DeviceGroupSort.
const (
	DeviceGroupSortCreatedAt      DeviceGroupSort = "created_at"
	DeviceGroupSortMinusCreatedAt DeviceGroupSort = "-created_at"
	DeviceGroupSortMinusName      DeviceGroupSort = "-name"
	DeviceGroupSortMinusUpdatedAt DeviceGroupSort = "-updated_at"
	DeviceGroupSortName           DeviceGroupSort = "name"
	DeviceGroupSortUpdatedAt      DeviceGroupSort = "updated_at"
)

// Valid indicates whether the value is a known member of the DeviceGroupSort enum.
func (e DeviceGroupSort) Valid() bool {
	switch e {
	case DeviceGroupSortCreatedAt:
		return true
	case DeviceGroupSortMinusCreatedAt:
		return true
	case DeviceGroupSortMinusName:
		return true
	case DeviceGroupSortMinusUpdatedAt:
		return true
	case DeviceGroupSortName:
		return true
	case DeviceGroupSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationSort.
const (
	OrganizationSortCreatedAt      OrganizationSort = "created_at"
	OrganizationSortMinusCreatedAt OrganizationSort = "-created_at"
	OrganizationSortMinusName      OrganizationSort = "-name"
	OrganizationSortMinusSlug      OrganizationSort = "-slug"
	OrganizationSortMinusStatus    OrganizationSort = "-status"
	OrganizationSortName           OrganizationSort = "name"
	OrganizationSortSlug           OrganizationSort = "slug"
	OrganizationSortStatus         OrganizationSort = "status"
)

// Valid indicates whether the value is a known member of the OrganizationSort enum.
func (e OrganizationSort) Valid() bool {
	switch e {
	case OrganizationSortCreatedAt:
		return true
	case OrganizationSortMinusCreatedAt:
		return true
	case OrganizationSortMinusName:
		return true
	case OrganizationSortMinusSlug:
		return true
	case OrganizationSortMinusStatus:
		return true
	case OrganizationSortName:
		return true
	case OrganizationSortSlug:
		return true
	case OrganizationSortStatus:
		return true
	default:
		return false
	}
}

// Defines values for PageSize.
const (
	PageSizeN10  PageSize = 10
	PageSizeN100 PageSize = 100
	PageSizeN25  PageSize = 25
	PageSizeN50  PageSize = 50
)

// Valid indicates whether the value is a known member of the PageSize enum.
func (e PageSize) Valid() bool {
	switch e {
	case PageSizeN10:
		return true
	case PageSizeN100:
		return true
	case PageSizeN25:
		return true
	case PageSizeN50:
		return true
	default:
		return false
	}
}

// Defines values for ListOrganizationsParamsPageSize.
const (
	ListOrganizationsParamsPageSizeN10  ListOrganizationsParamsPageSize = 10
	ListOrganizationsParamsPageSizeN100 ListOrganizationsParamsPageSize = 100
	ListOrganizationsParamsPageSizeN25  ListOrganizationsParamsPageSize = 25
	ListOrganizationsParamsPageSizeN50  ListOrganizationsParamsPageSize = 50
)

// Valid indicates whether the value is a known member of the ListOrganizationsParamsPageSize enum.
func (e ListOrganizationsParamsPageSize) Valid() bool {
	switch e {
	case ListOrganizationsParamsPageSizeN10:
		return true
	case ListOrganizationsParamsPageSizeN100:
		return true
	case ListOrganizationsParamsPageSizeN25:
		return true
	case ListOrganizationsParamsPageSizeN50:
		return true
	default:
		return false
	}
}

// Defines values for ListOrganizationsParamsSort.
const (
	ListOrganizationsParamsSortCreatedAt      ListOrganizationsParamsSort = "created_at"
	ListOrganizationsParamsSortMinusCreatedAt ListOrganizationsParamsSort = "-created_at"
	ListOrganizationsParamsSortMinusName      ListOrganizationsParamsSort = "-name"
	ListOrganizationsParamsSortMinusSlug      ListOrganizationsParamsSort = "-slug"
	ListOrganizationsParamsSortMinusStatus    ListOrganizationsParamsSort = "-status"
	ListOrganizationsParamsSortName           ListOrganizationsParamsSort = "name"
	ListOrganizationsParamsSortSlug           ListOrganizationsParamsSort = "slug"
	ListOrganizationsParamsSortStatus         ListOrganizationsParamsSort = "status"
)

// Valid indicates whether the value is a known member of the ListOrganizationsParamsSort enum.
func (e ListOrganizationsParamsSort) Valid() bool {
	switch e {
	case ListOrganizationsParamsSortCreatedAt:
		return true
	case ListOrganizationsParamsSortMinusCreatedAt:
		return true
	case ListOrganizationsParamsSortMinusName:
		return true
	case ListOrganizationsParamsSortMinusSlug:
		return true
	case ListOrganizationsParamsSortMinusStatus:
		return true
	case ListOrganizationsParamsSortName:
		return true
	case ListOrganizationsParamsSortSlug:
		return true
	case ListOrganizationsParamsSortStatus:
		return true
	default:
		return false
	}
}

// Defines values for CreateOrganizationParamsXPaddockCSRF.
const (
	CreateOrganizationParamsXPaddockCSRFN1 CreateOrganizationParamsXPaddockCSRF = "1"
)

// Valid indicates whether the value is a known member of the CreateOrganizationParamsXPaddockCSRF enum.
func (e CreateOrganizationParamsXPaddockCSRF) Valid() bool {
	switch e {
	case CreateOrganizationParamsXPaddockCSRFN1:
		return true
	default:
		return false
	}
}

// Defines values for ListAuditEventsParamsPageSize.
const (
	ListAuditEventsParamsPageSizeN10  ListAuditEventsParamsPageSize = 10
	ListAuditEventsParamsPageSizeN100 ListAuditEventsParamsPageSize = 100
	ListAuditEventsParamsPageSizeN25  ListAuditEventsParamsPageSize = 25
	ListAuditEventsParamsPageSizeN50  ListAuditEventsParamsPageSize = 50
)

// Valid indicates whether the value is a known member of the ListAuditEventsParamsPageSize enum.
func (e ListAuditEventsParamsPageSize) Valid() bool {
	switch e {
	case ListAuditEventsParamsPageSizeN10:
		return true
	case ListAuditEventsParamsPageSizeN100:
		return true
	case ListAuditEventsParamsPageSizeN25:
		return true
	case ListAuditEventsParamsPageSizeN50:
		return true
	default:
		return false
	}
}

// Defines values for ListAuditEventsParamsSort.
const (
	ListAuditEventsParamsSortCode            ListAuditEventsParamsSort = "code"
	ListAuditEventsParamsSortMinusCode       ListAuditEventsParamsSort = "-code"
	ListAuditEventsParamsSortMinusOccurredAt ListAuditEventsParamsSort = "-occurred_at"
	ListAuditEventsParamsSortMinusOutcome    ListAuditEventsParamsSort = "-outcome"
	ListAuditEventsParamsSortOccurredAt      ListAuditEventsParamsSort = "occurred_at"
	ListAuditEventsParamsSortOutcome         ListAuditEventsParamsSort = "outcome"
)

// Valid indicates whether the value is a known member of the ListAuditEventsParamsSort enum.
func (e ListAuditEventsParamsSort) Valid() bool {
	switch e {
	case ListAuditEventsParamsSortCode:
		return true
	case ListAuditEventsParamsSortMinusCode:
		return true
	case ListAuditEventsParamsSortMinusOccurredAt:
		return true
	case ListAuditEventsParamsSortMinusOutcome:
		return true
	case ListAuditEventsParamsSortOccurredAt:
		return true
	case ListAuditEventsParamsSortOutcome:
		return true
	default:
		return false
	}
}

// Defines values for ListDeviceGroupsParamsPageSize.
const (
	ListDeviceGroupsParamsPageSizeN10  ListDeviceGroupsParamsPageSize = 10
	ListDeviceGroupsParamsPageSizeN100 ListDeviceGroupsParamsPageSize = 100
	ListDeviceGroupsParamsPageSizeN25  ListDeviceGroupsParamsPageSize = 25
	ListDeviceGroupsParamsPageSizeN50  ListDeviceGroupsParamsPageSize = 50
)

// Valid indicates whether the value is a known member of the ListDeviceGroupsParamsPageSize enum.
func (e ListDeviceGroupsParamsPageSize) Valid() bool {
	switch e {
	case ListDeviceGroupsParamsPageSizeN10:
		return true
	case ListDeviceGroupsParamsPageSizeN100:
		return true
	case ListDeviceGroupsParamsPageSizeN25:
		return true
	case ListDeviceGroupsParamsPageSizeN50:
		return true
	default:
		return false
	}
}

// Defines values for ListDeviceGroupsParamsSort.
const (
	ListDeviceGroupsParamsSortCreatedAt      ListDeviceGroupsParamsSort = "created_at"
	ListDeviceGroupsParamsSortMinusCreatedAt ListDeviceGroupsParamsSort = "-created_at"
	ListDeviceGroupsParamsSortMinusName      ListDeviceGroupsParamsSort = "-name"
	ListDeviceGroupsParamsSortMinusUpdatedAt ListDeviceGroupsParamsSort = "-updated_at"
	ListDeviceGroupsParamsSortName           ListDeviceGroupsParamsSort = "name"
	ListDeviceGroupsParamsSortUpdatedAt      ListDeviceGroupsParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListDeviceGroupsParamsSort enum.
func (e ListDeviceGroupsParamsSort) Valid() bool {
	switch e {
	case ListDeviceGroupsParamsSortCreatedAt:
		return true
	case ListDeviceGroupsParamsSortMinusCreatedAt:
		return true
	case ListDeviceGroupsParamsSortMinusName:
		return true
	case ListDeviceGroupsParamsSortMinusUpdatedAt:
		return true
	case ListDeviceGroupsParamsSortName:
		return true
	case ListDeviceGroupsParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for CreateDeviceGroupParamsXPaddockCSRF.
const (
	CreateDeviceGroupParamsXPaddockCSRFN1 CreateDeviceGroupParamsXPaddockCSRF = "1"
)

// Valid indicates whether the value is a known member of the CreateDeviceGroupParamsXPaddockCSRF enum.
func (e CreateDeviceGroupParamsXPaddockCSRF) Valid() bool {
	switch e {
	case CreateDeviceGroupParamsXPaddockCSRFN1:
		return true
	default:
		return false
	}
}

// Defines values for DeleteDeviceGroupParamsXPaddockCSRF.
const (
	DeleteDeviceGroupParamsXPaddockCSRFN1 DeleteDeviceGroupParamsXPaddockCSRF = "1"
)

// Valid indicates whether the value is a known member of the DeleteDeviceGroupParamsXPaddockCSRF enum.
func (e DeleteDeviceGroupParamsXPaddockCSRF) Valid() bool {
	switch e {
	case DeleteDeviceGroupParamsXPaddockCSRFN1:
		return true
	default:
		return false
	}
}

// Defines values for UpdateDeviceGroupParamsXPaddockCSRF.
const (
	UpdateDeviceGroupParamsXPaddockCSRFN1 UpdateDeviceGroupParamsXPaddockCSRF = "1"
)

// Valid indicates whether the value is a known member of the UpdateDeviceGroupParamsXPaddockCSRF enum.
func (e UpdateDeviceGroupParamsXPaddockCSRF) Valid() bool {
	switch e {
	case UpdateDeviceGroupParamsXPaddockCSRFN1:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMeParamsXPaddockCSRF.
const (
	UpdateMeParamsXPaddockCSRFN1 UpdateMeParamsXPaddockCSRF = "1"
)

// Valid indicates whether the value is a known member of the UpdateMeParamsXPaddockCSRF enum.
func (e UpdateMeParamsXPaddockCSRF) Valid() bool {
	switch e {
	case UpdateMeParamsXPaddockCSRFN1:
		return true
	default:
		return false
	}
}

// AuditActor defines model for AuditActor.
type AuditActor struct {
	Display *string `json:"display,omitempty"`
	Id      *string `json:"id,omitempty"`
	Ip      *string `json:"ip,omitempty"`
	StepUp  bool    `json:"step_up"`
	Type    string  `json:"type"`
}

// AuditActorType defines model for AuditActorType.
type AuditActorType string

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Actor         AuditActor             `json:"actor"`
	Code          string                 `json:"code"`
	CorrelationId string                 `json:"correlation_id"`
	ErrorCode     *string                `json:"error_code,omitempty"`
	EventId       openapi_types.UUID     `json:"event_id"`
	OccurredAt    time.Time              `json:"occurred_at"`
	Outcome       AuditOutcome           `json:"outcome"`
	Params        map[string]interface{} `json:"params"`
	RecordedAt    time.Time              `json:"recorded_at"`
	Source        string                 `json:"source"`
	Target        *AuditTarget           `json:"target"`
}

// AuditEventPage defines model for AuditEventPage.
type AuditEventPage struct {
	Items    []AuditEvent `json:"items"`
	Page     int          `json:"page"`
	PageSize int          `json:"page_size"`

	// Sort Applied sort.
	Sort string `json:"sort"`

	// Total Matching items, counted up to 10000.
	Total int `json:"total"`

	// TotalCapped More than 10000 items match; total is 10000.
	TotalCapped bool `json:"total_capped"`
}

// AuditOutcome defines model for AuditOutcome.
type AuditOutcome string

// AuditTarget defines model for AuditTarget.
type AuditTarget struct {
	Display *string `json:"display,omitempty"`
	Id      string  `json:"id"`
	Type    string  `json:"type"`
}

// DeviceGroup defines model for DeviceGroup.
type DeviceGroup struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// DeviceGroupCreate defines model for DeviceGroupCreate.
type DeviceGroupCreate struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// DeviceGroupPage defines model for DeviceGroupPage.
type DeviceGroupPage struct {
	Items    []DeviceGroup `json:"items"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`

	// Sort Applied sort.
	Sort string `json:"sort"`

	// Total Matching items, counted up to 10000.
	Total int `json:"total"`

	// TotalCapped More than 10000 items match; total is 10000.
	TotalCapped bool `json:"total_capped"`
}

// DeviceGroupUpdate defines model for DeviceGroupUpdate.
type DeviceGroupUpdate struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// Me defines model for Me.
type Me struct {
	DisplayName  string             `json:"display_name"`
	Id           openapi_types.UUID `json:"id"`
	Locale       MeLocale           `json:"locale"`
	Organization *MeOrganization    `json:"organization"`
	Role         MeRole             `json:"role"`
	Username     string             `json:"username"`
}

// MeLocale defines model for Me.Locale.
type MeLocale string

// MeRole defines model for Me.Role.
type MeRole string

// MeOrganization defines model for MeOrganization.
type MeOrganization struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Slug string             `json:"slug"`
}

// MeUpdate defines model for MeUpdate.
type MeUpdate struct {
	Locale MeUpdateLocale `json:"locale"`
}

// MeUpdateLocale defines model for MeUpdate.Locale.
type MeUpdateLocale string

// Organization defines model for Organization.
type Organization struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    OrganizationStatus `json:"status"`
}

// OrganizationCreate defines model for OrganizationCreate.
type OrganizationCreate struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// OrganizationPage defines model for OrganizationPage.
type OrganizationPage struct {
	Items    []Organization `json:"items"`
	Page     int            `json:"page"`
	PageSize int            `json:"page_size"`

	// Sort Applied sort.
	Sort string `json:"sort"`

	// Total Matching items, counted up to 10000.
	Total int `json:"total"`

	// TotalCapped More than 10000 items match; total is 10000.
	TotalCapped bool `json:"total_capped"`
}

// OrganizationStatus defines model for OrganizationStatus.
type OrganizationStatus string

// Problem defines model for Problem.
type Problem struct {
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`

	// Instance Request ID
	Instance string `json:"instance"`
	Status   int    `json:"status"`
	Title    string `json:"title"`

	// Type urn:paddock:problem:<code>
	Type string `json:"type"`
}

// AuditEventSort defines model for AuditEventSort.
type AuditEventSort string

// Csrf defines model for Csrf.
type Csrf string

// DeviceGroupSort defines model for DeviceGroupSort.
type DeviceGroupSort string

// Id defines model for Id.
type Id = openapi_types.UUID

// OrganizationSort defines model for OrganizationSort.
type OrganizationSort string

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize int

// Search defines model for Search.
type Search = string

// ListOrganizationsParams defines parameters for ListOrganizations.
type ListOrganizationsParams struct {
	// Page Page number. page × page_size may not exceed 10000 (400 page_out_of_range).
	Page     *Page                            `form:"page,omitempty" json:"page,omitempty"`
	PageSize *ListOrganizationsParamsPageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Sort Sort field; "-" prefix sorts descending. The id is the tie-breaker.
	Sort *ListOrganizationsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Q Case-insensitive substring search over the fields listed in x-paddock-list.search.
	Q *Search `form:"q,omitempty" json:"q,omitempty"`

	// Status Repeatable.
	Status *[]OrganizationStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListOrganizationsParamsPageSize defines parameters for ListOrganizations.
type ListOrganizationsParamsPageSize int

// ListOrganizationsParamsSort defines parameters for ListOrganizations.
type ListOrganizationsParamsSort string

// CreateOrganizationParams defines parameters for CreateOrganization.
type CreateOrganizationParams struct {
	XPaddockCSRF CreateOrganizationParamsXPaddockCSRF `json:"X-Paddock-CSRF"`
}

// CreateOrganizationParamsXPaddockCSRF defines parameters for CreateOrganization.
type CreateOrganizationParamsXPaddockCSRF string

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	// Page Page number. page × page_size may not exceed 10000 (400 page_out_of_range).
	Page     *Page                          `form:"page,omitempty" json:"page,omitempty"`
	PageSize *ListAuditEventsParamsPageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Sort Sort field; "-" prefix sorts descending. The event_id is the tie-breaker.
	Sort *ListAuditEventsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Q Case-insensitive substring search over the fields listed in x-paddock-list.search.
	Q *Search `form:"q,omitempty" json:"q,omitempty"`

	// From RFC 3339; default to - 7 days.
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To RFC 3339; default now. The range may span at most 92 days (400 range_too_large).
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Code Exact event code; repeatable.
	Code *[]string `form:"code,omitempty" json:"code,omitempty"`

	// Outcome Repeatable.
	Outcome *[]AuditOutcome `form:"outcome,omitempty" json:"outcome,omitempty"`

	// ActorType Repeatable.
	ActorType *[]AuditActorType `form:"actor_type,omitempty" json:"actor_type,omitempty"`
}

// ListAuditEventsParamsPageSize defines parameters for ListAuditEvents.
type ListAuditEventsParamsPageSize int

// ListAuditEventsParamsSort defines parameters for ListAuditEvents.
type ListAuditEventsParamsSort string

// ListDeviceGroupsParams defines parameters for ListDeviceGroups.
type ListDeviceGroupsParams struct {
	// Page Page number. page × page_size may not exceed 10000 (400 page_out_of_range).
	Page     *Page                           `form:"page,omitempty" json:"page,omitempty"`
	PageSize *ListDeviceGroupsParamsPageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Sort Sort field; "-" prefix sorts descending. The id is the tie-breaker.
	Sort *ListDeviceGroupsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Q Case-insensitive substring search over the fields listed in x-paddock-list.search.
	Q *Search `form:"q,omitempty" json:"q,omitempty"`
}

// ListDeviceGroupsParamsPageSize defines parameters for ListDeviceGroups.
type ListDeviceGroupsParamsPageSize int

// ListDeviceGroupsParamsSort defines parameters for ListDeviceGroups.
type ListDeviceGroupsParamsSort string

// CreateDeviceGroupParams defines parameters for CreateDeviceGroup.
type CreateDeviceGroupParams struct {
	XPaddockCSRF CreateDeviceGroupParamsXPaddockCSRF `json:"X-Paddock-CSRF"`
}

// CreateDeviceGroupParamsXPaddockCSRF defines parameters for CreateDeviceGroup.
type CreateDeviceGroupParamsXPaddockCSRF string

// DeleteDeviceGroupParams defines parameters for DeleteDeviceGroup.
type DeleteDeviceGroupParams struct {
	XPaddockCSRF DeleteDeviceGroupParamsXPaddockCSRF `json:"X-Paddock-CSRF"`
}

// DeleteDeviceGroupParamsXPaddockCSRF defines parameters for DeleteDeviceGroup.
type DeleteDeviceGroupParamsXPaddockCSRF string

// UpdateDeviceGroupParams defines parameters for UpdateDeviceGroup.
type UpdateDeviceGroupParams struct {
	XPaddockCSRF UpdateDeviceGroupParamsXPaddockCSRF `json:"X-Paddock-CSRF"`
}

// UpdateDeviceGroupParamsXPaddockCSRF defines parameters for UpdateDeviceGroup.
type UpdateDeviceGroupParamsXPaddockCSRF string

// UpdateMeParams defines parameters for UpdateMe.
type UpdateMeParams struct {
	XPaddockCSRF UpdateMeParamsXPaddockCSRF `json:"X-Paddock-CSRF"`
}

// UpdateMeParamsXPaddockCSRF defines parameters for UpdateMe.
type UpdateMeParamsXPaddockCSRF string

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = OrganizationCreate

// CreateDeviceGroupJSONRequestBody defines body for CreateDeviceGroup for application/json ContentType.
type CreateDeviceGroupJSONRequestBody = DeviceGroupCreate

// UpdateDeviceGroupJSONRequestBody defines body for UpdateDeviceGroup for application/json ContentType.
type UpdateDeviceGroupJSONRequestBody = DeviceGroupUpdate

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = MeUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/platform/v1/organizations)
	ListOrganizations(w http.ResponseWriter, r *http.Request, params ListOrganizationsParams)

	// (POST /api/platform/v1/organizations)
	CreateOrganization(w http.ResponseWriter, r *http.Request, params CreateOrganizationParams)

	// (GET /api/platform/v1/organizations/{id})
	GetOrganization(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/v1/audit-events)
	ListAuditEvents(w http.ResponseWriter, r *http.Request, params ListAuditEventsParams)

	// (GET /api/v1/device-groups)
	ListDeviceGroups(w http.ResponseWriter, r *http.Request, params ListDeviceGroupsParams)

	// (POST /api/v1/device-groups)
	CreateDeviceGroup(w http.ResponseWriter, r *http.Request, params CreateDeviceGroupParams)

	// (DELETE /api/v1/device-groups/{id})
	DeleteDeviceGroup(w http.ResponseWriter, r *http.Request, id Id, params DeleteDeviceGroupParams)

	// (GET /api/v1/device-groups/{id})
	GetDeviceGroup(w http.ResponseWriter, r *http.Request, id Id)

	// (PATCH /api/v1/device-groups/{id})
	UpdateDeviceGroup(w http.ResponseWriter, r *http.Request, id Id, params UpdateDeviceGroupParams)

	// (GET /api/v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (PATCH /api/v1/me)
	UpdateMe(w http.ResponseWriter, r *http.Request, params UpdateMeParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListOrganizations operation middleware
func (siw *ServerInterfaceWrapper) ListOrganizations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrganizationsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrganizations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrganization operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganization(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOrganizationParams

	headers := r.Header

	// ------------- Required header parameter "X-Paddock-CSRF" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paddock-CSRF")]; found {
		var XPaddockCSRF CreateOrganizationParamsXPaddockCSRF
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Paddock-CSRF", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Paddock-CSRF", valueList[0], &XPaddockCSRF, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Paddock-CSRF", Err: err})
			return
		}

		params.XPaddockCSRF = XPaddockCSRF

	} else {
		err := fmt.Errorf("Header parameter X-Paddock-CSRF is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Paddock-CSRF", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrganization(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetOrganization(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrganization(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) ListAuditEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditEventsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "outcome" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "outcome", r.URL.Query(), &params.Outcome, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "outcome"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "outcome", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "actor_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "actor_type", r.URL.Query(), &params.ActorType, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "actor_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actor_type", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuditEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDeviceGroups operation middleware
func (siw *ServerInterfaceWrapper) ListDeviceGroups(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDeviceGroupsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeviceGroups(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDeviceGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateDeviceGroup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateDeviceGroupParams

	headers := r.Header

	// ------------- Required header parameter "X-Paddock-CSRF" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paddock-CSRF")]; found {
		var XPaddockCSRF CreateDeviceGroupParamsXPaddockCSRF
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Paddock-CSRF", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Paddock-CSRF", valueList[0], &XPaddockCSRF, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Paddock-CSRF", Err: err})
			return
		}

		params.XPaddockCSRF = XPaddockCSRF

	} else {
		err := fmt.Errorf("Header parameter X-Paddock-CSRF is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Paddock-CSRF", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDeviceGroup(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDeviceGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteDeviceGroup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteDeviceGroupParams

	headers := r.Header

	// ------------- Required header parameter "X-Paddock-CSRF" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paddock-CSRF")]; found {
		var XPaddockCSRF DeleteDeviceGroupParamsXPaddockCSRF
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Paddock-CSRF", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Paddock-CSRF", valueList[0], &XPaddockCSRF, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Paddock-CSRF", Err: err})
			return
		}

		params.XPaddockCSRF = XPaddockCSRF

	} else {
		err := fmt.Errorf("Header parameter X-Paddock-CSRF is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Paddock-CSRF", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDeviceGroup(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeviceGroup operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceGroup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeviceGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateDeviceGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateDeviceGroup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateDeviceGroupParams

	headers := r.Header

	// ------------- Required header parameter "X-Paddock-CSRF" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paddock-CSRF")]; found {
		var XPaddockCSRF UpdateDeviceGroupParamsXPaddockCSRF
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Paddock-CSRF", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Paddock-CSRF", valueList[0], &XPaddockCSRF, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Paddock-CSRF", Err: err})
			return
		}

		params.XPaddockCSRF = XPaddockCSRF

	} else {
		err := fmt.Errorf("Header parameter X-Paddock-CSRF is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Paddock-CSRF", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDeviceGroup(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateMeParams

	headers := r.Header

	// ------------- Required header parameter "X-Paddock-CSRF" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paddock-CSRF")]; found {
		var XPaddockCSRF UpdateMeParamsXPaddockCSRF
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Paddock-CSRF", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Paddock-CSRF", valueList[0], &XPaddockCSRF, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Paddock-CSRF", Err: err})
			return
		}

		params.XPaddockCSRF = XPaddockCSRF

	} else {
		err := fmt.Errorf("Header parameter X-Paddock-CSRF is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Paddock-CSRF", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/me", wrapper.UpdateMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/device-groups", wrapper.ListDeviceGroups)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/device-groups", wrapper.CreateDeviceGroup)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/device-groups/{id}", wrapper.DeleteDeviceGroup)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/device-groups/{id}", wrapper.GetDeviceGroup)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/device-groups/{id}", wrapper.UpdateDeviceGroup)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/audit-events", wrapper.ListAuditEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/platform/v1/organizations", wrapper.ListOrganizations)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/platform/v1/organizations", wrapper.CreateOrganization)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/platform/v1/organizations/{id}", wrapper.GetOrganization)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type ListOrganizationsRequestObject struct {
	Params ListOrganizationsParams
}

type ListOrganizationsResponseObject interface {
	VisitListOrganizationsResponse(w http.ResponseWriter) error
}

type ListOrganizations200JSONResponse OrganizationPage

func (response ListOrganizations200JSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizations400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response ListOrganizations400ApplicationProblemPlusJSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizations401ApplicationProblemPlusJSONResponse Problem

func (response ListOrganizations401ApplicationProblemPlusJSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizations403ApplicationProblemPlusJSONResponse Problem

func (response ListOrganizations403ApplicationProblemPlusJSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationRequestObject struct {
	Params CreateOrganizationParams
	Body   *CreateOrganizationJSONRequestBody
}

type CreateOrganizationResponseObject interface {
	VisitCreateOrganizationResponse(w http.ResponseWriter) error
}

type CreateOrganization200JSONResponse Organization

func (response CreateOrganization200JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization201ResponseHeaders struct {
	Location *string
}

type CreateOrganization201JSONResponse struct {
	Body    Organization
	Headers CreateOrganization201ResponseHeaders
}

func (response CreateOrganization201JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganization400ApplicationProblemPlusJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization401ApplicationProblemPlusJSONResponse Problem

func (response CreateOrganization401ApplicationProblemPlusJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization403ApplicationProblemPlusJSONResponse Problem

func (response CreateOrganization403ApplicationProblemPlusJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization409ApplicationProblemPlusJSONResponse Problem

func (response CreateOrganization409ApplicationProblemPlusJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization502ApplicationProblemPlusJSONResponse Problem

func (response CreateOrganization502ApplicationProblemPlusJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganizationRequestObject struct {
	Id Id `json:"id"`
}

type GetOrganizationResponseObject interface {
	VisitGetOrganizationResponse(w http.ResponseWriter) error
}

type GetOrganization200JSONResponse Organization

func (response GetOrganization200JSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganization400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetOrganization400ApplicationProblemPlusJSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganization401ApplicationProblemPlusJSONResponse Problem

func (response GetOrganization401ApplicationProblemPlusJSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganization403ApplicationProblemPlusJSONResponse Problem

func (response GetOrganization403ApplicationProblemPlusJSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganization404ApplicationProblemPlusJSONResponse Problem

func (response GetOrganization404ApplicationProblemPlusJSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEventsRequestObject struct {
	Params ListAuditEventsParams
}

type ListAuditEventsResponseObject interface {
	VisitListAuditEventsResponse(w http.ResponseWriter) error
}

type ListAuditEvents200JSONResponse AuditEventPage

func (response ListAuditEvents200JSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response ListAuditEvents400ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents401ApplicationProblemPlusJSONResponse Problem

func (response ListAuditEvents401ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents403ApplicationProblemPlusJSONResponse Problem

func (response ListAuditEvents403ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeviceGroupsRequestObject struct {
	Params ListDeviceGroupsParams
}

type ListDeviceGroupsResponseObject interface {
	VisitListDeviceGroupsResponse(w http.ResponseWriter) error
}

type ListDeviceGroups200JSONResponse DeviceGroupPage

func (response ListDeviceGroups200JSONResponse) VisitListDeviceGroupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeviceGroups400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response ListDeviceGroups400ApplicationProblemPlusJSONResponse) VisitListDeviceGroupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeviceGroups401ApplicationProblemPlusJSONResponse Problem

func (response ListDeviceGroups401ApplicationProblemPlusJSONResponse) VisitListDeviceGroupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeviceGroups403ApplicationProblemPlusJSONResponse Problem

func (response ListDeviceGroups403ApplicationProblemPlusJSONResponse) VisitListDeviceGroupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeviceGroupRequestObject struct {
	Params CreateDeviceGroupParams
	Body   *CreateDeviceGroupJSONRequestBody
}

type CreateDeviceGroupResponseObject interface {
	VisitCreateDeviceGroupResponse(w http.ResponseWriter) error
}

type CreateDeviceGroup201ResponseHeaders struct {
	Location *string
}

type CreateDeviceGroup201JSONResponse struct {
	Body    DeviceGroup
	Headers CreateDeviceGroup201ResponseHeaders
}

func (response CreateDeviceGroup201JSONResponse) VisitCreateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeviceGroup400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CreateDeviceGroup400ApplicationProblemPlusJSONResponse) VisitCreateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeviceGroup401ApplicationProblemPlusJSONResponse Problem

func (response CreateDeviceGroup401ApplicationProblemPlusJSONResponse) VisitCreateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeviceGroup403ApplicationProblemPlusJSONResponse Problem

func (response CreateDeviceGroup403ApplicationProblemPlusJSONResponse) VisitCreateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeviceGroup409ApplicationProblemPlusJSONResponse Problem

func (response CreateDeviceGroup409ApplicationProblemPlusJSONResponse) VisitCreateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDeviceGroupRequestObject struct {
	Id     Id `json:"id"`
	Params DeleteDeviceGroupParams
}

type DeleteDeviceGroupResponseObject interface {
	VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error
}

type DeleteDeviceGroup204Response struct {
}

func (response DeleteDeviceGroup204Response) VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDeviceGroup400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response DeleteDeviceGroup400ApplicationProblemPlusJSONResponse) VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDeviceGroup401ApplicationProblemPlusJSONResponse Problem

func (response DeleteDeviceGroup401ApplicationProblemPlusJSONResponse) VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDeviceGroup403ApplicationProblemPlusJSONResponse Problem

func (response DeleteDeviceGroup403ApplicationProblemPlusJSONResponse) VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDeviceGroup404ApplicationProblemPlusJSONResponse Problem

func (response DeleteDeviceGroup404ApplicationProblemPlusJSONResponse) VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceGroupRequestObject struct {
	Id Id `json:"id"`
}

type GetDeviceGroupResponseObject interface {
	VisitGetDeviceGroupResponse(w http.ResponseWriter) error
}

type GetDeviceGroup200JSONResponse DeviceGroup

func (response GetDeviceGroup200JSONResponse) VisitGetDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceGroup400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetDeviceGroup400ApplicationProblemPlusJSONResponse) VisitGetDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceGroup401ApplicationProblemPlusJSONResponse Problem

func (response GetDeviceGroup401ApplicationProblemPlusJSONResponse) VisitGetDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceGroup403ApplicationProblemPlusJSONResponse Problem

func (response GetDeviceGroup403ApplicationProblemPlusJSONResponse) VisitGetDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceGroup404ApplicationProblemPlusJSONResponse Problem

func (response GetDeviceGroup404ApplicationProblemPlusJSONResponse) VisitGetDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroupRequestObject struct {
	Id     Id `json:"id"`
	Params UpdateDeviceGroupParams
	Body   *UpdateDeviceGroupJSONRequestBody
}

type UpdateDeviceGroupResponseObject interface {
	VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error
}

type UpdateDeviceGroup200JSONResponse DeviceGroup

func (response UpdateDeviceGroup200JSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroup400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response UpdateDeviceGroup400ApplicationProblemPlusJSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroup401ApplicationProblemPlusJSONResponse Problem

func (response UpdateDeviceGroup401ApplicationProblemPlusJSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroup403ApplicationProblemPlusJSONResponse Problem

func (response UpdateDeviceGroup403ApplicationProblemPlusJSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroup404ApplicationProblemPlusJSONResponse Problem

func (response UpdateDeviceGroup404ApplicationProblemPlusJSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroup409ApplicationProblemPlusJSONResponse Problem

func (response UpdateDeviceGroup409ApplicationProblemPlusJSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMeRequestObject struct {
	Params UpdateMeParams
	Body   *UpdateMeJSONRequestBody
}

type UpdateMeResponseObject interface {
	VisitUpdateMeResponse(w http.ResponseWriter) error
}

type UpdateMe200JSONResponse Me

func (response UpdateMe200JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response UpdateMe400ApplicationProblemPlusJSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe401ApplicationProblemPlusJSONResponse Problem

func (response UpdateMe401ApplicationProblemPlusJSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe403ApplicationProblemPlusJSONResponse Problem

func (response UpdateMe403ApplicationProblemPlusJSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/platform/v1/organizations)
	ListOrganizations(ctx context.Context, request ListOrganizationsRequestObject) (ListOrganizationsResponseObject, error)

	// (POST /api/platform/v1/organizations)
	CreateOrganization(ctx context.Context, request CreateOrganizationRequestObject) (CreateOrganizationResponseObject, error)

	// (GET /api/platform/v1/organizations/{id})
	GetOrganization(ctx context.Context, request GetOrganizationRequestObject) (GetOrganizationResponseObject, error)

	// (GET /api/v1/audit-events)
	ListAuditEvents(ctx context.Context, request ListAuditEventsRequestObject) (ListAuditEventsResponseObject, error)

	// (GET /api/v1/device-groups)
	ListDeviceGroups(ctx context.Context, request ListDeviceGroupsRequestObject) (ListDeviceGroupsResponseObject, error)

	// (POST /api/v1/device-groups)
	CreateDeviceGroup(ctx context.Context, request CreateDeviceGroupRequestObject) (CreateDeviceGroupResponseObject, error)

	// (DELETE /api/v1/device-groups/{id})
	DeleteDeviceGroup(ctx context.Context, request DeleteDeviceGroupRequestObject) (DeleteDeviceGroupResponseObject, error)

	// (GET /api/v1/device-groups/{id})
	GetDeviceGroup(ctx context.Context, request GetDeviceGroupRequestObject) (GetDeviceGroupResponseObject, error)

	// (PATCH /api/v1/device-groups/{id})
	UpdateDeviceGroup(ctx context.Context, request UpdateDeviceGroupRequestObject) (UpdateDeviceGroupResponseObject, error)

	// (GET /api/v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)

	// (PATCH /api/v1/me)
	UpdateMe(ctx context.Context, request UpdateMeRequestObject) (UpdateMeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListOrganizations operation middleware
func (sh *strictHandler) ListOrganizations(w http.ResponseWriter, r *http.Request, params ListOrganizationsParams) {
	var request ListOrganizationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrganizations(ctx, request.(ListOrganizationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrganizations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrganizationsResponseObject); ok {
		if err := validResponse.VisitListOrganizationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrganization operation middleware
func (sh *strictHandler) CreateOrganization(w http.ResponseWriter, r *http.Request, params CreateOrganizationParams) {
	var request CreateOrganizationRequestObject

	request.Params = params

	var body CreateOrganizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrganization(ctx, request.(CreateOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrganizationResponseObject); ok {
		if err := validResponse.VisitCreateOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrganization operation middleware
func (sh *strictHandler) GetOrganization(w http.ResponseWriter, r *http.Request, id Id) {
	var request GetOrganizationRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrganization(ctx, request.(GetOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrganizationResponseObject); ok {
		if err := validResponse.VisitGetOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAuditEvents operation middleware
func (sh *strictHandler) ListAuditEvents(w http.ResponseWriter, r *http.Request, params ListAuditEventsParams) {
	var request ListAuditEventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuditEvents(ctx, request.(ListAuditEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuditEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAuditEventsResponseObject); ok {
		if err := validResponse.VisitListAuditEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDeviceGroups operation middleware
func (sh *strictHandler) ListDeviceGroups(w http.ResponseWriter, r *http.Request, params ListDeviceGroupsParams) {
	var request ListDeviceGroupsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDeviceGroups(ctx, request.(ListDeviceGroupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDeviceGroups")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDeviceGroupsResponseObject); ok {
		if err := validResponse.VisitListDeviceGroupsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDeviceGroup operation middleware
func (sh *strictHandler) CreateDeviceGroup(w http.ResponseWriter, r *http.Request, params CreateDeviceGroupParams) {
	var request CreateDeviceGroupRequestObject

	request.Params = params

	var body CreateDeviceGroupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDeviceGroup(ctx, request.(CreateDeviceGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDeviceGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDeviceGroupResponseObject); ok {
		if err := validResponse.VisitCreateDeviceGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDeviceGroup operation middleware
func (sh *strictHandler) DeleteDeviceGroup(w http.ResponseWriter, r *http.Request, id Id, params DeleteDeviceGroupParams) {
	var request DeleteDeviceGroupRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDeviceGroup(ctx, request.(DeleteDeviceGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDeviceGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDeviceGroupResponseObject); ok {
		if err := validResponse.VisitDeleteDeviceGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeviceGroup operation middleware
func (sh *strictHandler) GetDeviceGroup(w http.ResponseWriter, r *http.Request, id Id) {
	var request GetDeviceGroupRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeviceGroup(ctx, request.(GetDeviceGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeviceGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceGroupResponseObject); ok {
		if err := validResponse.VisitGetDeviceGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateDeviceGroup operation middleware
func (sh *strictHandler) UpdateDeviceGroup(w http.ResponseWriter, r *http.Request, id Id, params UpdateDeviceGroupParams) {
	var request UpdateDeviceGroupRequestObject

	request.Id = id
	request.Params = params

	var body UpdateDeviceGroupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateDeviceGroup(ctx, request.(UpdateDeviceGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateDeviceGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateDeviceGroupResponseObject); ok {
		if err := validResponse.VisitUpdateDeviceGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMe operation middleware
func (sh *strictHandler) UpdateMe(w http.ResponseWriter, r *http.Request, params UpdateMeParams) {
	var request UpdateMeRequestObject

	request.Params = params

	var body UpdateMeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMe(ctx, request.(UpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMeResponseObject); ok {
		if err := validResponse.VisitUpdateMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FvvbtvIEX+VAXtAbZSSKdu5uyi4D2mSC4Ke4SBJ0QKxK67JkbRnapfZXSpRDAF9h37oI/Q92jfpkxSz",
	"S1JLirKkxMm5h/tkcbncnZ2d+c1f3wSJnOVSoDA6GN4EOVNshgaVfXpcpNw8m6Mwr6UyNJKiThTPDZci",
	"GAY0CmOOWfoILoLeRQC5wjH/AFoqo4Emo0i5mPThzRQBaaURT4FrMFMEw7F3pZBdo+oHYcBpyXcFqkUQ",
	"BoLNMBgGtFAQBjqZ4ow5AsasyEwwDHoySQqlMB0xmoKimAXDt0FztDUpkSnSaPlXFiaRMztS/bwMA7PI",
	"7dZGcTEJlssweKLVmDa3FE6RpahWJP6195KlqUyue09ev/oxCAOF7wquMA2GRhXoE1/ROOje5inOeYLP",
	"lSzyO+H3XXHazlhxuHzslX8ThczU/G48FXnqvfKeOo//Iq15nDMzXZHG01u5OpZqxojOorAz11c+VxMm",
	"+EdGbLxXnNVZMfE4Wz72yr+7M1obZgptP3W/Ohn8kk1w/eg0CqKYXaHqQ04P//mn/TvS/CPCjC1ASAP4",
	"IUFMYRBFUQQHp1Hk5sjCjOR4pJiY4OEmDtDMbg4MwmDGBZ/R+Qc1zVwYnKCqiX7NP2ItGx1rW0q7Nzh+",
	"ULN3EIXHD8IHUTiIosvOvV4jU8l0nUVPmMYeFxqF5obPEXRx5fgK2n4Cco7KyoOVIQ0Z1wZT4AI+9PIS",
	"Hmis7+ZvYtS7xiFm7MNPKCZmGgwHUWQ5VT0fr9/vknRE51JotOD9UsmrDGf0M5HCoLBiz/I844nVhKPc",
	"zfjDz5pOeePt/I3CcTAMfne0sg5H7q0+qta1Ozb59OrHJ/Dw9MF3UK4MKRrGM9233C0XqA3L48RIZY2O",
	"kjkqwx3dKdd5xhb0s3XEkJCgczjvHNYG81Hhv7uSMkMm6KUbuelQkxXSvHVvVyutxEZe/YyJoYVWZ3lT",
	"LlmpM0tnXARhkGfMEEiNqgG90AZnQRgwIcViJjsVNvTM7zqXWMW8267KY/OyNH5dfEqkUphZmRht4DAq",
	"JdVo4wqVZd8BjsOGhfbnk3XoGW6xbv2j0j7vcuLzcu4ydP6MY1iacjohy156jHS2ZO1OFSZSpXuSqGWh",
	"km7+GKYm6PQvy87HwfDtDsd44z5aXoaBKLKMXWXoCG4Lac39sOX9+MeonZ+V01MSHJbCVJNZs21NNDbK",
	"v5XSyr40JZUbnDV/bD25k/laSQOmFFu465z4DK6xO/TMQOdr3Wn1HxMYYmqNfL/rSo00LFv/7oyZZEro",
	"b48UQiILQXBf5GCkM5Hech4Zdr1RwvIc045lpUIwUyZKK2tXhxlt9gjsp+R1tJevMa0lFY7dYWV8fTvp",
	"jtUip2TSxis+X2lg7a8USYKaNhkznhWK1k5RcLtaIa6FfC82I9ubWik+2wDsBeYb5Njzvtdp8rytnfGg",
	"cbkbz7IVLp1r0PG950/vSFNbQtKVk+kT23I1O/32Tr49sZ9tRtsxyzSG7etusqnp9ES3MOQW92iw7eh2",
	"jS2nuQs484XqNzy7L3jm3cqfrXDfV5Fdo/wMN+LlaCNQ7Ag0mUxY1sB37EZv6YXTu/s0Z+iH4V1uTRgo",
	"2SRAqkntNNNvOjZzvop9RWbEPrVc7C6qC41qA4u6cLGeHjYZXBLZ4kLNvcvOSztvcawFKZ9pCGy6YLdT",
	"+ZmFblI/SSF2FJ0WRbew7HaGfYo1/kJMrnMvWwxBIwXlvth6QV5exzvxNnZ9khHuAKjjrQC1YkrOjEFF",
	"mP+3t6z3Meo9vCz/9i5vBuFJtKyGv9nqlWwTUf+sd2Gim6j0m42+Jza6Q2E8eMmVnHPNpSCm2QCWz+2O",
	"3viIghK3SaFzFCmmnYbBS5S1YGZTusOltbptrdCGiaQjz/oK3xWoDbx42pk8qI/YcYPcZHhr3NPcqVBi",
	"WCYdh2UmbnhRRNFJQieyv7YHB2Ww5Pb2kchlEepzrt8dnQaTQnGzeE065pipUesSzG3mM5HymqOfx7UE",
	"j6p5K0XM+Z9w4dKNXIxlh0qRzYfHL1+AHNskbFmQgVwqEuCDPGMCziL497++7X972IfXNvFhZ6vCTGEs",
	"XfJ2goL8C0zhuQSNao4K6B7UmCWogYmUpl0It+7vNbxZ5PjaUgJEre7DXxQ3BgVwYVc8z1EQYSf9qH9i",
	"08Zo4AoTVmgEyXJuS1ETFJBK1DbRnitJQTWc9Af9C3EhevA4y8Am4DQwhbApywoH8absbnwI77mZQky7",
	"xfYgcXWDMRyoWjQP+7ThWWGYIawpX2goJcOeyRXAIG4WvoYwiOFAmimq91wjnEYnECdajUczrjUXk9it",
	"/WaK4LtOBC8CidM5U4buhEHOzHQI3EAiZ6hhrOTM7lzKBkiRLfrwCl0CS9NHduPGwvpCADCh36OC0+gU",
	"YiHNaCwLkcYh4AeWmGwBGb9GKAkEVS1oCT23viYtRPhoLOtzxec8wwmmQJBD7xKm1ALiVZrfOqVDaCtc",
	"/AiQJVMgSznL7TWnBRFfkSIFWorpc1cqdXdmN6d1LFXP5qgWkMgsQ0sAxM+fvYmBz/IMZ2TXLKMyrukb",
	"YRRLDBw8fvoKomjw/eEQYsLkOHR/LTbHcDCIQjh+EMKDKCSoPwyJkJigOYYDlmXyvV0xhLgXV4WxH7yi",
	"WGg3zRWfMbWAa1zQpRLCE+YC036V7DCE+F1MGxwk28oqIRz/9+//GEQRJFNGR0GlDys1hFQmBR0ZUxjz",
	"jN49ArIP1RPdGO2jMEdmKM5wxbuqSkJExjelOSV2hKuyV+hsX/mnNFehNdrLuO+416iTxVWhjHZcr5XF",
	"a8Wy+PARxHb1mAjpMOchsCs5RycAbir84F5ZFbaX5NMHPxCeYVxW2z8YYiyJSLMGFdec0/ZAZc0qhLJo",
	"ZgfDqrJVFrTK/SrWyrGTZlvTuhC1oRgGFfbWoByEwRyVw/4g6g/6kY0hcxQs58EwsNBonQUztZbiiOX8",
	"iBVmepSwLLtiyXUwvFmG3ngmJ2RD1gZlYbzRKiY8mg+OGsBAm5SZx5aJlhnqITSDSXJ7ZIUFL9JgGPzE",
	"tTlvLBg2Gic2BMKrKUfWb12GO82zxc8d5q4VuXf4pix40sy2s1LrTBAG+CHPrC/kyiWdRe7KP1gVEff2",
	"vqu4aN0H12ZhhYtuxWYOGpXO4yi6pcq5X3VzLbroKHOeC3SFcrI7vhz0idZTR03XJjXVqyIqzR/sOf9k",
	"j/m2+DTR1mcuxZpctiYieBXzkYtaqiis1Hcbl9WdBbosk6/Fau7bt60gtqtT4ZIIy6XeWQnBhbXOvDX8",
	"BzIH3Gh4XJgpCsOvYaJkkWtyEEiIyZwYC/vOySFnj4kL0XRCBDjKoCOCqOwwgmYzBDodKOzVMzW5KgfH",
	"UXTooLCJFo7w82a2aD+4sP1HTuztGf4o08UXkfgyd7BsBgNVcu5r6FxnW4HHa0ytkh07pfkq2zumpASE",
	"zvW1DPhJJnV2arXPWlPGvQMEmv9wr/kPouO7BBzr4FK46LG9X2KE/fx24310w9Pl51rw52haCvmLCXc7",
	"HrqHNoTmn36uCCz3Bb0XabC8rMRhPjiyctOzgdFWD66uG4Tg1Qm6PblVx8H98ONaTbef5cX9+AROTk4e",
	"PqpdeyOhB99ByhZ6Uw8aRdtBZ3/lrZXl7XsL+b4MwCj+sfGSzpkAZmAmtYGHx5YuFzDZOSMj5Shj6pbW",
	"QiPvgNZnFIKXMTdF2o/8mHE3/7dMi3V4vxuSdpuc2893xb0Gn/188Xbz1Jcm1LYdjaoWu0+gddV194vG",
	"DK0OqC0Rg5fguecBg7PUu0QLrTZ7L2oo0cSq6VoDmicAjbCinGhf96t2oKo9rR7wAo7OLv+6pX+59MxI",
	"amv/PRcj7GlHqvLzDlbFazG4H2al/c8Fe9iVL6k77X6bLcrjbq+K8O619jQFbRctKuPllfY0lKKjUcvT",
	"gK5Y22/c2hpvbxD1/oZ41m9sulfh7Ho72k7R7OBLEPBbNPlp+lGFiG7KyE5ZDxHbYF5HhilmaHC7pK/L",
	"9lP75R3JdkO+TtfJcZulv66Ab99bdXeV0p53b4ifo2ne5dcwY5uCfN90/arv/NMifVsA6vrnq33tk2tg",
	"+3+wT2Wr3VfOtm4RVUfUrwGVvqJtKj2thm1yDXUlqK3h0hl+STg6w00opPlEYNrjAqwycW1KNdr7+jx2",
	"2SDLU+AuhTzD+6WHdafrV1a/7qspta7zUu5pfFNH1lWzl73Sus3r7eXShi9qXt12obJgGEyNyfXw6Mh5",
	"YKVW9W0r8FRqM/z+9PTEXnq5z02dLSqMy3GWzzP0n5oa671w+uoN1Cnp5eXyfwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
