//go:build go1.22

// Package adminapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package adminapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuditEventOutcome.
const (
	Denied  AuditEventOutcome = "denied"
	Failure AuditEventOutcome = "failure"
	Success AuditEventOutcome = "success"
	Unknown AuditEventOutcome = "unknown"
)

// Valid indicates whether the value is a known member of the AuditEventOutcome enum.
func (e AuditEventOutcome) Valid() bool {
	switch e {
	case Denied:
		return true
	case Failure:
		return true
	case Success:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for MeLocale.
const (
	MeLocaleEn MeLocale = "en"
)

// Valid indicates whether the value is a known member of the MeLocale enum.
func (e MeLocale) Valid() bool {
	switch e {
	case MeLocaleEn:
		return true
	default:
		return false
	}
}

// Defines values for MeRole.
const (
	OrgAdmin      MeRole = "org_admin"
	OrgAuditor    MeRole = "org_auditor"
	OrgOperator   MeRole = "org_operator"
	PlatformAdmin MeRole = "platform_admin"
)

// Valid indicates whether the value is a known member of the MeRole enum.
func (e MeRole) Valid() bool {
	switch e {
	case OrgAdmin:
		return true
	case OrgAuditor:
		return true
	case OrgOperator:
		return true
	case PlatformAdmin:
		return true
	default:
		return false
	}
}

// Defines values for MeUpdateLocale.
const (
	MeUpdateLocaleEn MeUpdateLocale = "en"
)

// Valid indicates whether the value is a known member of the MeUpdateLocale enum.
func (e MeUpdateLocale) Valid() bool {
	switch e {
	case MeUpdateLocaleEn:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationStatus.
const (
	Active             OrganizationStatus = "active"
	Provisioning       OrganizationStatus = "provisioning"
	ProvisioningFailed OrganizationStatus = "provisioning_failed"
	Suspended          OrganizationStatus = "suspended"
)

// Valid indicates whether the value is a known member of the OrganizationStatus enum.
func (e OrganizationStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Provisioning:
		return true
	case ProvisioningFailed:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// Defines values for Csrf.
const (
	CsrfN1 Csrf = "1"
)

// Valid indicates whether the value is a known member of the Csrf enum.
func (e Csrf) Valid() bool {
	switch e {
	case CsrfN1:
		return true
	default:
		return false
	}
}

// Defines values for CreateOrganizationParamsXPaddockCSRF.
const (
	CreateOrganizationParamsXPaddockCSRFN1 CreateOrganizationParamsXPaddockCSRF = "1"
)

// Valid indicates whether the value is a known member of the CreateOrganizationParamsXPaddockCSRF enum.
func (e CreateOrganizationParamsXPaddockCSRF) Valid() bool {
	switch e {
	case CreateOrganizationParamsXPaddockCSRFN1:
		return true
	default:
		return false
	}
}

// Defines values for CreateDeviceGroupParamsXPaddockCSRF.
const (
	CreateDeviceGroupParamsXPaddockCSRFN1 CreateDeviceGroupParamsXPaddockCSRF = "1"
)

// Valid indicates whether the value is a known member of the CreateDeviceGroupParamsXPaddockCSRF enum.
func (e CreateDeviceGroupParamsXPaddockCSRF) Valid() bool {
	switch e {
	case CreateDeviceGroupParamsXPaddockCSRFN1:
		return true
	default:
		return false
	}
}

// Defines values for DeleteDeviceGroupParamsXPaddockCSRF.
const (
	DeleteDeviceGroupParamsXPaddockCSRFN1 DeleteDeviceGroupParamsXPaddockCSRF = "1"
)

// Valid indicates whether the value is a known member of the DeleteDeviceGroupParamsXPaddockCSRF enum.
func (e DeleteDeviceGroupParamsXPaddockCSRF) Valid() bool {
	switch e {
	case DeleteDeviceGroupParamsXPaddockCSRFN1:
		return true
	default:
		return false
	}
}

// Defines values for UpdateDeviceGroupParamsXPaddockCSRF.
const (
	UpdateDeviceGroupParamsXPaddockCSRFN1 UpdateDeviceGroupParamsXPaddockCSRF = "1"
)

// Valid indicates whether the value is a known member of the UpdateDeviceGroupParamsXPaddockCSRF enum.
func (e UpdateDeviceGroupParamsXPaddockCSRF) Valid() bool {
	switch e {
	case UpdateDeviceGroupParamsXPaddockCSRFN1:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMeParamsXPaddockCSRF.
const (
	UpdateMeParamsXPaddockCSRFN1 UpdateMeParamsXPaddockCSRF = "1"
)

// Valid indicates whether the value is a known member of the UpdateMeParamsXPaddockCSRF enum.
func (e UpdateMeParamsXPaddockCSRF) Valid() bool {
	switch e {
	case UpdateMeParamsXPaddockCSRFN1:
		return true
	default:
		return false
	}
}

// AuditActor defines model for AuditActor.
type AuditActor struct {
	Display *string `json:"display,omitempty"`
	Id      *string `json:"id,omitempty"`
	Ip      *string `json:"ip,omitempty"`
	StepUp  bool    `json:"step_up"`
	Type    string  `json:"type"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Actor         AuditActor             `json:"actor"`
	Code          string                 `json:"code"`
	CorrelationId string                 `json:"correlation_id"`
	ErrorCode     *string                `json:"error_code,omitempty"`
	EventId       openapi_types.UUID     `json:"event_id"`
	OccurredAt    time.Time              `json:"occurred_at"`
	Outcome       AuditEventOutcome      `json:"outcome"`
	Params        map[string]interface{} `json:"params"`
	RecordedAt    time.Time              `json:"recorded_at"`
	Source        string                 `json:"source"`
	Target        *AuditTarget           `json:"target"`
}

// AuditEventOutcome defines model for AuditEvent.Outcome.
type AuditEventOutcome string

// AuditEventPage defines model for AuditEventPage.
type AuditEventPage struct {
	Items      []AuditEvent `json:"items"`
	NextCursor *string      `json:"next_cursor"`
}

// AuditTarget defines model for AuditTarget.
type AuditTarget struct {
	Display *string `json:"display,omitempty"`
	Id      string  `json:"id"`
	Type    string  `json:"type"`
}

// DeviceGroup defines model for DeviceGroup.
type DeviceGroup struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// DeviceGroupCreate defines model for DeviceGroupCreate.
type DeviceGroupCreate struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// DeviceGroupPage defines model for DeviceGroupPage.
type DeviceGroupPage struct {
	Items      []DeviceGroup `json:"items"`
	NextCursor *string       `json:"next_cursor"`
}

// DeviceGroupUpdate defines model for DeviceGroupUpdate.
type DeviceGroupUpdate struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// Me defines model for Me.
type Me struct {
	DisplayName  string             `json:"display_name"`
	Id           openapi_types.UUID `json:"id"`
	Locale       MeLocale           `json:"locale"`
	Organization *MeOrganization    `json:"organization"`
	Role         MeRole             `json:"role"`
	Username     string             `json:"username"`
}

// MeLocale defines model for Me.Locale.
type MeLocale string

// MeRole defines model for Me.Role.
type MeRole string

// MeOrganization defines model for MeOrganization.
type MeOrganization struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Slug string             `json:"slug"`
}

// MeUpdate defines model for MeUpdate.
type MeUpdate struct {
	Locale MeUpdateLocale `json:"locale"`
}

// MeUpdateLocale defines model for MeUpdate.Locale.
type MeUpdateLocale string

// Organization defines model for Organization.
type Organization struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    OrganizationStatus `json:"status"`
}

// OrganizationStatus defines model for Organization.Status.
type OrganizationStatus string

// OrganizationCreate defines model for OrganizationCreate.
type OrganizationCreate struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// OrganizationPage defines model for OrganizationPage.
type OrganizationPage struct {
	Items      []Organization `json:"items"`
	NextCursor *string        `json:"next_cursor"`
}

// Problem defines model for Problem.
type Problem struct {
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`

	// Instance Request ID
	Instance string `json:"instance"`
	Status   int    `json:"status"`
	Title    string `json:"title"`

	// Type urn:paddock:problem:<code>
	Type string `json:"type"`
}

// Csrf defines model for Csrf.
type Csrf string

// Cursor defines model for Cursor.
type Cursor = string

// Id defines model for Id.
type Id = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// ListOrganizationsParams defines parameters for ListOrganizations.
type ListOrganizationsParams struct {
	// Cursor Opaque cursor from next_cursor of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateOrganizationParams defines parameters for CreateOrganization.
type CreateOrganizationParams struct {
	XPaddockCSRF CreateOrganizationParamsXPaddockCSRF `json:"X-Paddock-CSRF"`
}

// CreateOrganizationParamsXPaddockCSRF defines parameters for CreateOrganization.
type CreateOrganizationParamsXPaddockCSRF string

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	// From RFC 3339; default now - 7 days.
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To RFC 3339; default now. The range may span at most 92 days.
	To   *time.Time `form:"to,omitempty" json:"to,omitempty"`
	Code *string    `form:"code,omitempty" json:"code,omitempty"`

	// Cursor Opaque cursor from next_cursor of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListDeviceGroupsParams defines parameters for ListDeviceGroups.
type ListDeviceGroupsParams struct {
	// Cursor Opaque cursor from next_cursor of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateDeviceGroupParams defines parameters for CreateDeviceGroup.
type CreateDeviceGroupParams struct {
	XPaddockCSRF CreateDeviceGroupParamsXPaddockCSRF `json:"X-Paddock-CSRF"`
}

// CreateDeviceGroupParamsXPaddockCSRF defines parameters for CreateDeviceGroup.
type CreateDeviceGroupParamsXPaddockCSRF string

// DeleteDeviceGroupParams defines parameters for DeleteDeviceGroup.
type DeleteDeviceGroupParams struct {
	XPaddockCSRF DeleteDeviceGroupParamsXPaddockCSRF `json:"X-Paddock-CSRF"`
}

// DeleteDeviceGroupParamsXPaddockCSRF defines parameters for DeleteDeviceGroup.
type DeleteDeviceGroupParamsXPaddockCSRF string

// UpdateDeviceGroupParams defines parameters for UpdateDeviceGroup.
type UpdateDeviceGroupParams struct {
	XPaddockCSRF UpdateDeviceGroupParamsXPaddockCSRF `json:"X-Paddock-CSRF"`
}

// UpdateDeviceGroupParamsXPaddockCSRF defines parameters for UpdateDeviceGroup.
type UpdateDeviceGroupParamsXPaddockCSRF string

// UpdateMeParams defines parameters for UpdateMe.
type UpdateMeParams struct {
	XPaddockCSRF UpdateMeParamsXPaddockCSRF `json:"X-Paddock-CSRF"`
}

// UpdateMeParamsXPaddockCSRF defines parameters for UpdateMe.
type UpdateMeParamsXPaddockCSRF string

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = OrganizationCreate

// CreateDeviceGroupJSONRequestBody defines body for CreateDeviceGroup for application/json ContentType.
type CreateDeviceGroupJSONRequestBody = DeviceGroupCreate

// UpdateDeviceGroupJSONRequestBody defines body for UpdateDeviceGroup for application/json ContentType.
type UpdateDeviceGroupJSONRequestBody = DeviceGroupUpdate

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = MeUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/platform/v1/organizations)
	ListOrganizations(w http.ResponseWriter, r *http.Request, params ListOrganizationsParams)

	// (POST /api/platform/v1/organizations)
	CreateOrganization(w http.ResponseWriter, r *http.Request, params CreateOrganizationParams)

	// (GET /api/platform/v1/organizations/{id})
	GetOrganization(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/v1/audit-events)
	ListAuditEvents(w http.ResponseWriter, r *http.Request, params ListAuditEventsParams)

	// (GET /api/v1/device-groups)
	ListDeviceGroups(w http.ResponseWriter, r *http.Request, params ListDeviceGroupsParams)

	// (POST /api/v1/device-groups)
	CreateDeviceGroup(w http.ResponseWriter, r *http.Request, params CreateDeviceGroupParams)

	// (DELETE /api/v1/device-groups/{id})
	DeleteDeviceGroup(w http.ResponseWriter, r *http.Request, id Id, params DeleteDeviceGroupParams)

	// (GET /api/v1/device-groups/{id})
	GetDeviceGroup(w http.ResponseWriter, r *http.Request, id Id)

	// (PATCH /api/v1/device-groups/{id})
	UpdateDeviceGroup(w http.ResponseWriter, r *http.Request, id Id, params UpdateDeviceGroupParams)

	// (GET /api/v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (PATCH /api/v1/me)
	UpdateMe(w http.ResponseWriter, r *http.Request, params UpdateMeParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListOrganizations operation middleware
func (siw *ServerInterfaceWrapper) ListOrganizations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrganizationsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrganizations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrganization operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganization(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOrganizationParams

	headers := r.Header

	// ------------- Required header parameter "X-Paddock-CSRF" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paddock-CSRF")]; found {
		var XPaddockCSRF CreateOrganizationParamsXPaddockCSRF
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Paddock-CSRF", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Paddock-CSRF", valueList[0], &XPaddockCSRF, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Paddock-CSRF", Err: err})
			return
		}

		params.XPaddockCSRF = XPaddockCSRF

	} else {
		err := fmt.Errorf("Header parameter X-Paddock-CSRF is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Paddock-CSRF", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrganization(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetOrganization(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrganization(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) ListAuditEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditEventsParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuditEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDeviceGroups operation middleware
func (siw *ServerInterfaceWrapper) ListDeviceGroups(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDeviceGroupsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeviceGroups(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDeviceGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateDeviceGroup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateDeviceGroupParams

	headers := r.Header

	// ------------- Required header parameter "X-Paddock-CSRF" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paddock-CSRF")]; found {
		var XPaddockCSRF CreateDeviceGroupParamsXPaddockCSRF
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Paddock-CSRF", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Paddock-CSRF", valueList[0], &XPaddockCSRF, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Paddock-CSRF", Err: err})
			return
		}

		params.XPaddockCSRF = XPaddockCSRF

	} else {
		err := fmt.Errorf("Header parameter X-Paddock-CSRF is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Paddock-CSRF", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDeviceGroup(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDeviceGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteDeviceGroup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteDeviceGroupParams

	headers := r.Header

	// ------------- Required header parameter "X-Paddock-CSRF" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paddock-CSRF")]; found {
		var XPaddockCSRF DeleteDeviceGroupParamsXPaddockCSRF
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Paddock-CSRF", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Paddock-CSRF", valueList[0], &XPaddockCSRF, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Paddock-CSRF", Err: err})
			return
		}

		params.XPaddockCSRF = XPaddockCSRF

	} else {
		err := fmt.Errorf("Header parameter X-Paddock-CSRF is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Paddock-CSRF", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDeviceGroup(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeviceGroup operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceGroup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeviceGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateDeviceGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateDeviceGroup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateDeviceGroupParams

	headers := r.Header

	// ------------- Required header parameter "X-Paddock-CSRF" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paddock-CSRF")]; found {
		var XPaddockCSRF UpdateDeviceGroupParamsXPaddockCSRF
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Paddock-CSRF", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Paddock-CSRF", valueList[0], &XPaddockCSRF, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Paddock-CSRF", Err: err})
			return
		}

		params.XPaddockCSRF = XPaddockCSRF

	} else {
		err := fmt.Errorf("Header parameter X-Paddock-CSRF is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Paddock-CSRF", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDeviceGroup(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateMeParams

	headers := r.Header

	// ------------- Required header parameter "X-Paddock-CSRF" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paddock-CSRF")]; found {
		var XPaddockCSRF UpdateMeParamsXPaddockCSRF
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Paddock-CSRF", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Paddock-CSRF", valueList[0], &XPaddockCSRF, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Paddock-CSRF", Err: err})
			return
		}

		params.XPaddockCSRF = XPaddockCSRF

	} else {
		err := fmt.Errorf("Header parameter X-Paddock-CSRF is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Paddock-CSRF", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/me", wrapper.UpdateMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/device-groups", wrapper.ListDeviceGroups)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/device-groups", wrapper.CreateDeviceGroup)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/device-groups/{id}", wrapper.DeleteDeviceGroup)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/device-groups/{id}", wrapper.GetDeviceGroup)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/device-groups/{id}", wrapper.UpdateDeviceGroup)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/audit-events", wrapper.ListAuditEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/platform/v1/organizations", wrapper.ListOrganizations)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/platform/v1/organizations", wrapper.CreateOrganization)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/platform/v1/organizations/{id}", wrapper.GetOrganization)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type ListOrganizationsRequestObject struct {
	Params ListOrganizationsParams
}

type ListOrganizationsResponseObject interface {
	VisitListOrganizationsResponse(w http.ResponseWriter) error
}

type ListOrganizations200JSONResponse OrganizationPage

func (response ListOrganizations200JSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizations400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response ListOrganizations400ApplicationProblemPlusJSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizations401ApplicationProblemPlusJSONResponse Problem

func (response ListOrganizations401ApplicationProblemPlusJSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizations403ApplicationProblemPlusJSONResponse Problem

func (response ListOrganizations403ApplicationProblemPlusJSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationRequestObject struct {
	Params CreateOrganizationParams
	Body   *CreateOrganizationJSONRequestBody
}

type CreateOrganizationResponseObject interface {
	VisitCreateOrganizationResponse(w http.ResponseWriter) error
}

type CreateOrganization200JSONResponse Organization

func (response CreateOrganization200JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization201ResponseHeaders struct {
	Location *string
}

type CreateOrganization201JSONResponse struct {
	Body    Organization
	Headers CreateOrganization201ResponseHeaders
}

func (response CreateOrganization201JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganization400ApplicationProblemPlusJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization401ApplicationProblemPlusJSONResponse Problem

func (response CreateOrganization401ApplicationProblemPlusJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization403ApplicationProblemPlusJSONResponse Problem

func (response CreateOrganization403ApplicationProblemPlusJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization409ApplicationProblemPlusJSONResponse Problem

func (response CreateOrganization409ApplicationProblemPlusJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganization502ApplicationProblemPlusJSONResponse Problem

func (response CreateOrganization502ApplicationProblemPlusJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganizationRequestObject struct {
	Id Id `json:"id"`
}

type GetOrganizationResponseObject interface {
	VisitGetOrganizationResponse(w http.ResponseWriter) error
}

type GetOrganization200JSONResponse Organization

func (response GetOrganization200JSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganization400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetOrganization400ApplicationProblemPlusJSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganization401ApplicationProblemPlusJSONResponse Problem

func (response GetOrganization401ApplicationProblemPlusJSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganization403ApplicationProblemPlusJSONResponse Problem

func (response GetOrganization403ApplicationProblemPlusJSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganization404ApplicationProblemPlusJSONResponse Problem

func (response GetOrganization404ApplicationProblemPlusJSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEventsRequestObject struct {
	Params ListAuditEventsParams
}

type ListAuditEventsResponseObject interface {
	VisitListAuditEventsResponse(w http.ResponseWriter) error
}

type ListAuditEvents200JSONResponse AuditEventPage

func (response ListAuditEvents200JSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response ListAuditEvents400ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents401ApplicationProblemPlusJSONResponse Problem

func (response ListAuditEvents401ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents403ApplicationProblemPlusJSONResponse Problem

func (response ListAuditEvents403ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeviceGroupsRequestObject struct {
	Params ListDeviceGroupsParams
}

type ListDeviceGroupsResponseObject interface {
	VisitListDeviceGroupsResponse(w http.ResponseWriter) error
}

type ListDeviceGroups200JSONResponse DeviceGroupPage

func (response ListDeviceGroups200JSONResponse) VisitListDeviceGroupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeviceGroups400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response ListDeviceGroups400ApplicationProblemPlusJSONResponse) VisitListDeviceGroupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeviceGroups401ApplicationProblemPlusJSONResponse Problem

func (response ListDeviceGroups401ApplicationProblemPlusJSONResponse) VisitListDeviceGroupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeviceGroups403ApplicationProblemPlusJSONResponse Problem

func (response ListDeviceGroups403ApplicationProblemPlusJSONResponse) VisitListDeviceGroupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeviceGroupRequestObject struct {
	Params CreateDeviceGroupParams
	Body   *CreateDeviceGroupJSONRequestBody
}

type CreateDeviceGroupResponseObject interface {
	VisitCreateDeviceGroupResponse(w http.ResponseWriter) error
}

type CreateDeviceGroup201ResponseHeaders struct {
	Location *string
}

type CreateDeviceGroup201JSONResponse struct {
	Body    DeviceGroup
	Headers CreateDeviceGroup201ResponseHeaders
}

func (response CreateDeviceGroup201JSONResponse) VisitCreateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeviceGroup400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CreateDeviceGroup400ApplicationProblemPlusJSONResponse) VisitCreateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeviceGroup401ApplicationProblemPlusJSONResponse Problem

func (response CreateDeviceGroup401ApplicationProblemPlusJSONResponse) VisitCreateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeviceGroup403ApplicationProblemPlusJSONResponse Problem

func (response CreateDeviceGroup403ApplicationProblemPlusJSONResponse) VisitCreateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeviceGroup409ApplicationProblemPlusJSONResponse Problem

func (response CreateDeviceGroup409ApplicationProblemPlusJSONResponse) VisitCreateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDeviceGroupRequestObject struct {
	Id     Id `json:"id"`
	Params DeleteDeviceGroupParams
}

type DeleteDeviceGroupResponseObject interface {
	VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error
}

type DeleteDeviceGroup204Response struct {
}

func (response DeleteDeviceGroup204Response) VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDeviceGroup400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response DeleteDeviceGroup400ApplicationProblemPlusJSONResponse) VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDeviceGroup401ApplicationProblemPlusJSONResponse Problem

func (response DeleteDeviceGroup401ApplicationProblemPlusJSONResponse) VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDeviceGroup403ApplicationProblemPlusJSONResponse Problem

func (response DeleteDeviceGroup403ApplicationProblemPlusJSONResponse) VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDeviceGroup404ApplicationProblemPlusJSONResponse Problem

func (response DeleteDeviceGroup404ApplicationProblemPlusJSONResponse) VisitDeleteDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceGroupRequestObject struct {
	Id Id `json:"id"`
}

type GetDeviceGroupResponseObject interface {
	VisitGetDeviceGroupResponse(w http.ResponseWriter) error
}

type GetDeviceGroup200JSONResponse DeviceGroup

func (response GetDeviceGroup200JSONResponse) VisitGetDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceGroup400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetDeviceGroup400ApplicationProblemPlusJSONResponse) VisitGetDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceGroup401ApplicationProblemPlusJSONResponse Problem

func (response GetDeviceGroup401ApplicationProblemPlusJSONResponse) VisitGetDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceGroup403ApplicationProblemPlusJSONResponse Problem

func (response GetDeviceGroup403ApplicationProblemPlusJSONResponse) VisitGetDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceGroup404ApplicationProblemPlusJSONResponse Problem

func (response GetDeviceGroup404ApplicationProblemPlusJSONResponse) VisitGetDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroupRequestObject struct {
	Id     Id `json:"id"`
	Params UpdateDeviceGroupParams
	Body   *UpdateDeviceGroupJSONRequestBody
}

type UpdateDeviceGroupResponseObject interface {
	VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error
}

type UpdateDeviceGroup200JSONResponse DeviceGroup

func (response UpdateDeviceGroup200JSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroup400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response UpdateDeviceGroup400ApplicationProblemPlusJSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroup401ApplicationProblemPlusJSONResponse Problem

func (response UpdateDeviceGroup401ApplicationProblemPlusJSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroup403ApplicationProblemPlusJSONResponse Problem

func (response UpdateDeviceGroup403ApplicationProblemPlusJSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroup404ApplicationProblemPlusJSONResponse Problem

func (response UpdateDeviceGroup404ApplicationProblemPlusJSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeviceGroup409ApplicationProblemPlusJSONResponse Problem

func (response UpdateDeviceGroup409ApplicationProblemPlusJSONResponse) VisitUpdateDeviceGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMeRequestObject struct {
	Params UpdateMeParams
	Body   *UpdateMeJSONRequestBody
}

type UpdateMeResponseObject interface {
	VisitUpdateMeResponse(w http.ResponseWriter) error
}

type UpdateMe200JSONResponse Me

func (response UpdateMe200JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response UpdateMe400ApplicationProblemPlusJSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe401ApplicationProblemPlusJSONResponse Problem

func (response UpdateMe401ApplicationProblemPlusJSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe403ApplicationProblemPlusJSONResponse Problem

func (response UpdateMe403ApplicationProblemPlusJSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/platform/v1/organizations)
	ListOrganizations(ctx context.Context, request ListOrganizationsRequestObject) (ListOrganizationsResponseObject, error)

	// (POST /api/platform/v1/organizations)
	CreateOrganization(ctx context.Context, request CreateOrganizationRequestObject) (CreateOrganizationResponseObject, error)

	// (GET /api/platform/v1/organizations/{id})
	GetOrganization(ctx context.Context, request GetOrganizationRequestObject) (GetOrganizationResponseObject, error)

	// (GET /api/v1/audit-events)
	ListAuditEvents(ctx context.Context, request ListAuditEventsRequestObject) (ListAuditEventsResponseObject, error)

	// (GET /api/v1/device-groups)
	ListDeviceGroups(ctx context.Context, request ListDeviceGroupsRequestObject) (ListDeviceGroupsResponseObject, error)

	// (POST /api/v1/device-groups)
	CreateDeviceGroup(ctx context.Context, request CreateDeviceGroupRequestObject) (CreateDeviceGroupResponseObject, error)

	// (DELETE /api/v1/device-groups/{id})
	DeleteDeviceGroup(ctx context.Context, request DeleteDeviceGroupRequestObject) (DeleteDeviceGroupResponseObject, error)

	// (GET /api/v1/device-groups/{id})
	GetDeviceGroup(ctx context.Context, request GetDeviceGroupRequestObject) (GetDeviceGroupResponseObject, error)

	// (PATCH /api/v1/device-groups/{id})
	UpdateDeviceGroup(ctx context.Context, request UpdateDeviceGroupRequestObject) (UpdateDeviceGroupResponseObject, error)

	// (GET /api/v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)

	// (PATCH /api/v1/me)
	UpdateMe(ctx context.Context, request UpdateMeRequestObject) (UpdateMeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListOrganizations operation middleware
func (sh *strictHandler) ListOrganizations(w http.ResponseWriter, r *http.Request, params ListOrganizationsParams) {
	var request ListOrganizationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrganizations(ctx, request.(ListOrganizationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrganizations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrganizationsResponseObject); ok {
		if err := validResponse.VisitListOrganizationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrganization operation middleware
func (sh *strictHandler) CreateOrganization(w http.ResponseWriter, r *http.Request, params CreateOrganizationParams) {
	var request CreateOrganizationRequestObject

	request.Params = params

	var body CreateOrganizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrganization(ctx, request.(CreateOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrganizationResponseObject); ok {
		if err := validResponse.VisitCreateOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrganization operation middleware
func (sh *strictHandler) GetOrganization(w http.ResponseWriter, r *http.Request, id Id) {
	var request GetOrganizationRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrganization(ctx, request.(GetOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrganizationResponseObject); ok {
		if err := validResponse.VisitGetOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAuditEvents operation middleware
func (sh *strictHandler) ListAuditEvents(w http.ResponseWriter, r *http.Request, params ListAuditEventsParams) {
	var request ListAuditEventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuditEvents(ctx, request.(ListAuditEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuditEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAuditEventsResponseObject); ok {
		if err := validResponse.VisitListAuditEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDeviceGroups operation middleware
func (sh *strictHandler) ListDeviceGroups(w http.ResponseWriter, r *http.Request, params ListDeviceGroupsParams) {
	var request ListDeviceGroupsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDeviceGroups(ctx, request.(ListDeviceGroupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDeviceGroups")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDeviceGroupsResponseObject); ok {
		if err := validResponse.VisitListDeviceGroupsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDeviceGroup operation middleware
func (sh *strictHandler) CreateDeviceGroup(w http.ResponseWriter, r *http.Request, params CreateDeviceGroupParams) {
	var request CreateDeviceGroupRequestObject

	request.Params = params

	var body CreateDeviceGroupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDeviceGroup(ctx, request.(CreateDeviceGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDeviceGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDeviceGroupResponseObject); ok {
		if err := validResponse.VisitCreateDeviceGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDeviceGroup operation middleware
func (sh *strictHandler) DeleteDeviceGroup(w http.ResponseWriter, r *http.Request, id Id, params DeleteDeviceGroupParams) {
	var request DeleteDeviceGroupRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDeviceGroup(ctx, request.(DeleteDeviceGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDeviceGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDeviceGroupResponseObject); ok {
		if err := validResponse.VisitDeleteDeviceGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeviceGroup operation middleware
func (sh *strictHandler) GetDeviceGroup(w http.ResponseWriter, r *http.Request, id Id) {
	var request GetDeviceGroupRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeviceGroup(ctx, request.(GetDeviceGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeviceGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceGroupResponseObject); ok {
		if err := validResponse.VisitGetDeviceGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateDeviceGroup operation middleware
func (sh *strictHandler) UpdateDeviceGroup(w http.ResponseWriter, r *http.Request, id Id, params UpdateDeviceGroupParams) {
	var request UpdateDeviceGroupRequestObject

	request.Id = id
	request.Params = params

	var body UpdateDeviceGroupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateDeviceGroup(ctx, request.(UpdateDeviceGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateDeviceGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateDeviceGroupResponseObject); ok {
		if err := validResponse.VisitUpdateDeviceGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMe operation middleware
func (sh *strictHandler) UpdateMe(w http.ResponseWriter, r *http.Request, params UpdateMeParams) {
	var request UpdateMeRequestObject

	request.Params = params

	var body UpdateMeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMe(ctx, request.(UpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMeResponseObject); ok {
		if err := validResponse.VisitUpdateMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fr/bts48n+VAb8LfFucLNtxunvV/pVrb4viGqRoe7gDmpzNiGObG4lkSSqpN/Dz3Hvckx1IyrJkS3bc",
	"H2la3F+JpCE5v+czQ9+SVOZKChTWkOSWKKppjha1f3pm9NT95YIkZI6UoSYRETRHkpB/9l5TxmR61Xv2",
	"9s1vJCIaPxRcIyOJ1QVGxKRzzKlbj6LISfKeDMlFROxCueXGai5mZLmMyLNCG6kdIUOTaq4sl+7EM0U/",
	"FAip/wxTLXMQ+NGOyxdyCnaOoDRec1kYUHSGMYkCtx8K1Is1s2EJqTO1zcdLVgmrqJ2vV3O2U7yp1Dm1",
	"JCFF4Sm3d37Fc26rzTd4y/zH+oYMp7TILEmeDCKS0488d/o7GrgnLsLTsDqHC4sz1GTpTtJolBQGvf1e",
	"a3mZYe7+TaWwKDwPVKmMp9Qpua8CxZ9+N07jtzUeftI4JQn5v/7aQfrhq+mv9vUnNm325rdn8PT4yS9Q",
	"7gwMLeWZib0eyg3c/icF4/YktcHwSkuF2vLAN+NGZXTRYqXI2aL1tWp9bSyqcVH/dillhlS4j+FNmyes",
	"bf0+fF3vtPZgefk7ptZt5GX563Wp36YsdCXiLoXWlLGMSCoZtkqTSq0x85Ybd+gBtZZ63LkDOibLtXvc",
	"NiIyTQutkY2pbdAzarFneY6tiwqbyhzrYW+KNEVjSESmlGeFdusYCo7u1EJcCXkjWjJDFLJR0CJj3IlN",
	"s9c17YZA3DKHxlRqdiDfRhY6bVeapXqGIXSy7GxKkvd3sOa7sGh5ERFRZBm9zDAwvOlflUmaCm+KUTrF",
	"Wr0Vw1HpYRWbldq2/GW3676mM9x2X24xb/6zV/IQCFV8Eao1XbjnWvJ2GzXVEu0Jw3B+c5NOgd5VFvvs",
	"xHJQkuhQ8nO85im+0DJkoiZPqUZqD3TWRs7tlGVvgIcC1LK+UOxAnjatxVb1rclsVBe3cc4evT3zy7pT",
	"wZRmBqNNczfVlNOPr1DM7Jwkw4Erpp0KaVL6qls97xPd77FHmi8Ra3Wn+lbBVuPh796UD9VAW5yfYmd2",
	"GHeGxR3DKpMpzRoVENvrm9QzKvgfdCX/3crLKZ7V17VUmIho2WRA6tmYspy7CHT/O7FpKBv+k0ua/kll",
	"1DoBS+o2rguDukNFbVmgIo+aCi6Z3NBCpb2LVqOdbWhsI4A+M+2ZrJjdUSpPGnUH+yl+UkDc0XU2ONqh",
	"st0K+5Ta85WU7BA2tYWpy660vOaGS+EoPNDh146n+vuxw5QeSZrCKBQM2X6FbZmwOr1RoPYp9JOKUksK",
	"O9qbwtZqU9Ra1K7V+td72vtj0Ht6Uf7tXdwOo9FguXr9094qvc+J67J+iZLVzFvfqGbVmuKNYOhqmkIL",
	"214RhLFUhL5hoxHGDwUaCy+ft3Ybla9vNvERsdxmuBOLNk8qtEhUGMUkZdednBeDwSh1Evn/9gO2EsCG",
	"s+vRENqOSs5tjTppMC00t4u3zs5BmQaNKVOOn3mkUl5xXA89SobHK7q1Myj+N1yE0QIXU7kt74mrTHDy",
	"+uVqAlTOoUBJbWkGj1RGBZwO4D///jn++XEMb32n5Kl1Yecwldqvm6FwVRAZvJBgUF+jBmcHPaUpGqCC",
	"ObJzEfb9fwPvFgrfek7AcWti+Ifm1qIALvyOZwqFY2wUD+IRmOLSoIVLTGlhECRVvOf0OUMBTKIBIS0o",
	"LV1zDKN4GJ+Lc9GDkywD38YboBqha6ICjyZdk5zJY7jhdg4Td9rECzJZWXACj3Tlmo9jd+BpYanlYgbl",
	"BwOlZ3iZwtwPJs15XwLDCTySdo76hhuE48EIJqnR03HOjeFiNgl7v5sj1As8cAMCnaYV1dbZhIKidp4A",
	"t+A6WxMGfe7k0jdAimwRwxsMHa9xi/zBjY3NuQCgwtyghuPBMUyEtOOpLASbRIAfaWqzBWT8CqFkEPRq",
	"Q8/omUdEbiOwc2q96pXm1zzDGTJwtcd9S6nWC5h87JUO3PPQKYHNgJv8CkjTObhsnStvZlY45lesSIGe",
	"Y7cc/Awg2Mwf7vaJz0UVkAlZ+Xjl/CQi16hDjJFBPIwHHlEqFFRxkhDvgn4YYOc+IvtU8T4t7Lyf0iy7",
	"pOkVSW6XUe19JmcuVrdeysLW3q4QYv962G8YwB1Sdt0bqVBmaBJoQsuYeG6Dzl8ykpBX3NizxoZRYx7d",
	"AYvXJP1ykLyM9lKGgayDzo2B6dFgsGNYetiQdKt4tkxLzwT6sbV36broEQi8cTE65drY2Jn2OPDWdmQl",
	"w3oy6+iHB9KPDqD3Y7GZ8SittCu5WEZESXNnD4CAn4wP9kaScBmLWwMnhZ2jsPwKZq7HNC4LKAzJyi1a",
	"ZTKX0ak4F81MIyCUMWjBi6tgQzA0R3BICDT2Kkrj8tGjo8HgcYjDpqsGxs+ajcuBvmr0tHRAL8NfJFt8",
	"Fd8rQeqyWfFXfeJ9eH/rPUFN18i8gx8Fh72X44NSmEtCob55BbySadUodV8ULR9cMDr6pwfRPxkcfW6w",
	"R2SjCDpMWFN7XDZSfvnuytG/5Wz5ueXjBdqNgPxmzr0Jeh5g/nb0x18i3x+U9F4ysrxYucP1sO/9pufR",
	"z174UI2wIqiNrGI40ww1MrhcQO3+JILVvQq43VAwLmbtmGN9adGCOLZvN0ej0dNfobyiBSFvoAe/AKML",
	"03X57AAtab0w3jlQv9PhsUfYmooZQk4XYBQVQC3k0lh4erSTLys/iavW+/XQJu64Xf++wNvGtdge6FYD",
	"8eZhY7WQqC+WtRhkfobfCwDrwCBcjZGbIdkaZbWrgu8c2G/e4+xxjqDfEsB+T7i+6Rh7wX2Ha8Qd4Ll+",
	"ffWgsPP2peOdoPPwazDwP+h6d/9sw6OBZOxJtvHoZvKrYCjDDC3u9/Rt337uV34h32741/E2O+Ew9mOh",
	"y0OtGmzF3JlfvnC9QNu05X0Ula6Ool5Ifmibf1pb4Ued6fzz61O4uP0e6lN5xXzPo509rhqY+hGy0j3W",
	"pvKHUI3aFK6Jy6S2lZdO8Wumo1PsykKGzwSyHhfgg4kbW4bRwearqSvHMurLAG4LSC/wA4rD6hce9xx+",
	"7aYpo67VKA+0v/BGr18fe5NWF8fvL5zlwrVssHahM5KQubXKJP1+QGBlVMX+JzBzaWzy5+PjkTd6ec7q",
	"FxeEFnbuW8jyOcf6UzNiax9CvNZeVPOv5cXyvwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
