package audit

import (
	"fmt"
	"strings"
)

// RenderMarkdown renders the code registry as docs/compliance/audit-codes.md.
func RenderMarkdown() string {
	var b strings.Builder
	b.WriteString("# Audit event codes\n\n")
	b.WriteString("<!-- Generated by `make gen` from server/internal/domain/audit/codes.go. Do not edit. -->\n\n")
	b.WriteString("Schema `" + Schema + "`. Codes are stable English identifiers; events are never translated or rewritten.\n")
	b.WriteString("The portal renders them through the message key `audit.<code>`.\n\n")
	b.WriteString("| Code | Description | Params | Outcomes |\n| --- | --- | --- | --- |\n")
	for _, d := range Definitions() {
		desc := d.Description
		if d.Note != "" {
			desc += " " + d.Note
		}
		params := "–"
		if len(d.Params) > 0 {
			params = "`" + strings.Join(d.Params, "`, `") + "`"
		}
		outcomes := "– (never emitted)"
		if d.Emitted {
			parts := make([]string, len(d.Outcomes))
			for i, o := range d.Outcomes {
				parts[i] = string(o)
			}
			outcomes = strings.Join(parts, ", ")
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", d.Code, desc, params, outcomes)
	}
	return b.String()
}
