package system

import (
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
	"time"
)

// TestAutoinstallGate is gate D-AI (plan M4b §6, AC1, AC2): user-data generated by the API installs a throwaway VM
// from the 26.04 ISO; at the first boot the disk passphrase of the user-data and the boot PIN (twice) are typed; the
// device enrolls itself and becomes compliant; the next boot unlocks with the PIN, the install passphrase no longer
// unlocks, and the recovery key from the API unlocks at the PIN prompt once the PIN attempts are used up. It runs
// only with PADDOCK_SYSTEM_VMS=paddock-ai-2604 (about an hour) and deletes the VM at the end.
func TestAutoinstallGate(t *testing.T) {
	if !slices.Contains(strings.Split(os.Getenv("PADDOCK_SYSTEM_VMS"), ","), aiVMName) {
		t.Skip("gate D-AI runs with PADDOCK_SYSTEM_VMS=" + aiVMName)
	}
	s := newStack(t)
	iso := os.Getenv("PADDOCK_SYSTEM_ISO_2604")
	if iso == "" {
		home, _ := os.UserHomeDir()
		iso = filepath.Join(home, "Downloads", "ubuntu-26.04.1-desktop-amd64.iso")
	}
	v := s.InstallRelease(t)

	tok := s.Call(http.MethodPost, "/api/v1/enrollment-tokens", map[string]any{
		"name": "systest " + aiVMName + " " + unique(), "max_uses": 1, "auto_approve": true,
		"expires_at": time.Now().Add(3 * time.Hour).UTC().Format(time.RFC3339),
	}, http.StatusCreated)
	var created struct {
		Token struct {
			ID string `json:"id"`
		} `json:"token"`
		EnrollmentConfig json.RawMessage `json:"enrollment_config"`
	}
	if err := json.Unmarshal(tok.Body, &created); err != nil {
		t.Fatal(err)
	}
	s.RevokeOnCleanup(created.Token.ID)
	userData := s.Call(http.MethodPost, "/api/v1/autoinstall", map[string]any{
		"enrollment_config": created.EnrollmentConfig, "release": "26.04", "hostname": aiVMName,
		"locale": "en_US.UTF-8", "keyboard_layout": "us", "timezone": "Europe/Berlin",
	}, http.StatusOK).Body
	if !strings.Contains(string(userData), "/packages/"+v+"/paddock-agent_"+v+"_amd64.deb") {
		t.Fatalf("the user-data does not install release %s", v)
	}
	passphrase := storagePassphrase(t, userData)
	vm := buildAIVM(t, s.root, iso, withTestAccess(t, userData, s.root, &VM{dir: filepath.Join(s.root, "test", "vms", "virtualbox")}))

	pin := randomDigits(t, 8)
	vm.StartWithPassphrase(t, passphrase)
	d := &Device{VM: vm, s: s}
	d.AnswerDiskSetup(t, pin)
	if out := vm.Must("sudo passwd -S paddock-install | cut -d' ' -f2"); out != "L" {
		t.Errorf("the installer account is not locked: %s", out)
	}
	Until(t, aiVMName+" enrolls itself", 10*time.Minute, 10*time.Second, nil, func() bool {
		var page struct {
			Items []struct {
				ID    string `json:"id"`
				State string `json:"state"`
			} `json:"items"`
		}
		_ = json.Unmarshal(s.Call(http.MethodGet, "/api/v1/devices?q="+aiVMName+"&state=active", nil, http.StatusOK).Body, &page)
		for _, item := range page.Items {
			if d.ID == "" || d.ID == item.ID {
				d.ID = item.ID
				return true
			}
		}
		return false
	})
	if out := vm.Must("test -e /etc/paddock/enroll.json && echo present || echo gone"); out != "gone" {
		t.Error("the enrollment configuration is still on the device")
	}
	info := d.WaitDisk(t, "compliant", 30*time.Minute, func(i diskInfo) bool { return i.state() == "compliant" })
	if stored(info.RecoveryKeys) < 1 || stored(info.Headers) < 2 || !slices.Equal(vm.Keyslots(t), []string{"recovery", "tpm2+pin"}) {
		t.Fatalf("compliant disk %+v, keyslots %v", info, vm.Keyslots(t))
	}
	if vm.Opens(t, passphrase) {
		t.Fatal("the install passphrase still unlocks the disk")
	}
	vm.RebootWithPIN(t, pin)

	s.StepUp()
	var revealed struct {
		RecoveryKey string `json:"recovery_key"`
	}
	if err := json.Unmarshal(s.Call(http.MethodPost, "/api/v1/devices/"+d.ID+"/disk/recovery-key",
		map[string]any{"confirm_hostname": aiVMName}, http.StatusOK).Body, &revealed); err != nil {
		t.Fatal(err)
	}
	_, _ = vm.SSH(t.Context(), nil, "sudo systemctl reboot")
	vm.waitSSHDown(t)
	vm.unlockAtPrompt(t, []string{revealed.RecoveryKey}, "recovery key")
	// The entries before the recovery key counted as TPM authorization failures (throwaway VM, empty lockout auth).
	_, _ = vm.SSH(t.Context(), nil, "sudo tpm2_dictionarylockout --clear-lockout")
}
