// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package auditstore

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const ensureAuditPartition = `-- name: EnsureAuditPartition :exec
SELECT audit_ensure_partition($1::date)
`

func (q *Queries) EnsureAuditPartition(ctx context.Context, month time.Time) error {
	_, err := q.db.Exec(ctx, ensureAuditPartition, month)
	return err
}

const firstAuditDay = `-- name: FirstAuditDay :one
SELECT LEAST(
  (SELECT min(o.day) FROM audit_object o WHERE o.organization_id = $1),
  (SELECT min(m.day) FROM audit_manifest m WHERE m.organization_id = $1)
)::date AS day
`

func (q *Queries) FirstAuditDay(ctx context.Context, organizationID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, firstAuditDay, organizationID)
	var day time.Time
	err := row.Scan(&day)
	return day, err
}

const getAuditEventTime = `-- name: GetAuditEventTime :one
SELECT occurred_at FROM audit_event WHERE event_id = $1 LIMIT 1
`

func (q *Queries) GetAuditEventTime(ctx context.Context, eventID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, getAuditEventTime, eventID)
	var occurred_at time.Time
	err := row.Scan(&occurred_at)
	return occurred_at, err
}

const getAuditManifest = `-- name: GetAuditManifest :one
SELECT organization_id, day, sha256, prev_sha256, signature, key_version, object_key FROM audit_manifest WHERE organization_id = $1 AND day = $2
`

type GetAuditManifestParams struct {
	OrganizationID uuid.UUID
	Day            time.Time
}

func (q *Queries) GetAuditManifest(ctx context.Context, arg GetAuditManifestParams) (AuditManifest, error) {
	row := q.db.QueryRow(ctx, getAuditManifest, arg.OrganizationID, arg.Day)
	var i AuditManifest
	err := row.Scan(
		&i.OrganizationID,
		&i.Day,
		&i.Sha256,
		&i.PrevSha256,
		&i.Signature,
		&i.KeyVersion,
		&i.ObjectKey,
	)
	return i, err
}

const getLatestAuditManifest = `-- name: GetLatestAuditManifest :one
SELECT organization_id, day, sha256, prev_sha256, signature, key_version, object_key FROM audit_manifest WHERE organization_id = $1 ORDER BY day DESC LIMIT 1
`

func (q *Queries) GetLatestAuditManifest(ctx context.Context, organizationID uuid.UUID) (AuditManifest, error) {
	row := q.db.QueryRow(ctx, getLatestAuditManifest, organizationID)
	var i AuditManifest
	err := row.Scan(
		&i.OrganizationID,
		&i.Day,
		&i.Sha256,
		&i.PrevSha256,
		&i.Signature,
		&i.KeyVersion,
		&i.ObjectKey,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_event (event_id, organization_id, occurred_at, recorded_at, code, outcome, source, actor, target,
                         params, correlation_id, object_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12)
ON CONFLICT DO NOTHING
RETURNING event_id
`

type InsertAuditEventParams struct {
	EventID        uuid.UUID
	OrganizationID uuid.UUID
	OccurredAt     time.Time
	RecordedAt     time.Time
	Code           string
	Outcome        string
	Source         string
	Actor          json.RawMessage
	Target         json.RawMessage
	Params         json.RawMessage
	CorrelationID  string
	ObjectKey      string
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.EventID,
		arg.OrganizationID,
		arg.OccurredAt,
		arg.RecordedAt,
		arg.Code,
		arg.Outcome,
		arg.Source,
		arg.Actor,
		arg.Target,
		arg.Params,
		arg.CorrelationID,
		arg.ObjectKey,
	)
	var event_id uuid.UUID
	err := row.Scan(&event_id)
	return event_id, err
}

const insertAuditManifest = `-- name: InsertAuditManifest :exec
INSERT INTO audit_manifest (organization_id, day, sha256, prev_sha256, signature, key_version, object_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditManifestParams struct {
	OrganizationID uuid.UUID
	Day            time.Time
	Sha256         []byte
	PrevSha256     []byte
	Signature      string
	KeyVersion     int32
	ObjectKey      string
}

func (q *Queries) InsertAuditManifest(ctx context.Context, arg InsertAuditManifestParams) error {
	_, err := q.db.Exec(ctx, insertAuditManifest,
		arg.OrganizationID,
		arg.Day,
		arg.Sha256,
		arg.PrevSha256,
		arg.Signature,
		arg.KeyVersion,
		arg.ObjectKey,
	)
	return err
}

const insertAuditObject = `-- name: InsertAuditObject :exec
INSERT INTO audit_object (object_key, organization_id, day, event_count, sha256)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditObjectParams struct {
	ObjectKey      string
	OrganizationID uuid.UUID
	Day            time.Time
	EventCount     int32
	Sha256         []byte
}

func (q *Queries) InsertAuditObject(ctx context.Context, arg InsertAuditObjectParams) error {
	_, err := q.db.Exec(ctx, insertAuditObject,
		arg.ObjectKey,
		arg.OrganizationID,
		arg.Day,
		arg.EventCount,
		arg.Sha256,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT event_id, organization_id, occurred_at, recorded_at, code, outcome, source, actor, target, params, correlation_id, object_key FROM audit_event
WHERE occurred_at >= $1 AND occurred_at < $2
  AND ($3::text IS NULL OR code = $3::text)
  AND ($4::timestamptz IS NULL
       OR (occurred_at, event_id) < ($4::timestamptz, $5::uuid))
ORDER BY occurred_at DESC, event_id DESC
LIMIT $6
`

type ListAuditEventsParams struct {
	FromTime   time.Time
	ToTime     time.Time
	Code       *string
	CursorTime *time.Time
	CursorID   uuid.NullUUID
	MaxRows    int32
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.FromTime,
		arg.ToTime,
		arg.Code,
		arg.CursorTime,
		arg.CursorID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.EventID,
			&i.OrganizationID,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.Code,
			&i.Outcome,
			&i.Source,
			&i.Actor,
			&i.Target,
			&i.Params,
			&i.CorrelationID,
			&i.ObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditManifests = `-- name: ListAuditManifests :many
SELECT organization_id, day, sha256, prev_sha256, signature, key_version, object_key FROM audit_manifest
WHERE organization_id = $1 AND day BETWEEN $2 AND $3
ORDER BY day
`

type ListAuditManifestsParams struct {
	OrganizationID uuid.UUID
	FromDay        time.Time
	ToDay          time.Time
}

func (q *Queries) ListAuditManifests(ctx context.Context, arg ListAuditManifestsParams) ([]AuditManifest, error) {
	rows, err := q.db.Query(ctx, listAuditManifests, arg.OrganizationID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditManifest{}
	for rows.Next() {
		var i AuditManifest
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Day,
			&i.Sha256,
			&i.PrevSha256,
			&i.Signature,
			&i.KeyVersion,
			&i.ObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditObjectsForDay = `-- name: ListAuditObjectsForDay :many
SELECT object_key, organization_id, day, event_count, sha256, created_at FROM audit_object WHERE organization_id = $1 AND day = $2 ORDER BY object_key
`

type ListAuditObjectsForDayParams struct {
	OrganizationID uuid.UUID
	Day            time.Time
}

func (q *Queries) ListAuditObjectsForDay(ctx context.Context, arg ListAuditObjectsForDayParams) ([]AuditObject, error) {
	rows, err := q.db.Query(ctx, listAuditObjectsForDay, arg.OrganizationID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditObject{}
	for rows.Next() {
		var i AuditObject
		if err := rows.Scan(
			&i.ObjectKey,
			&i.OrganizationID,
			&i.Day,
			&i.EventCount,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditObjectsInRange = `-- name: ListAuditObjectsInRange :many
SELECT object_key, organization_id, day, event_count, sha256, created_at FROM audit_object
WHERE organization_id = $1 AND day BETWEEN $2 AND $3
ORDER BY day, object_key
`

type ListAuditObjectsInRangeParams struct {
	OrganizationID uuid.UUID
	FromDay        time.Time
	ToDay          time.Time
}

func (q *Queries) ListAuditObjectsInRange(ctx context.Context, arg ListAuditObjectsInRangeParams) ([]AuditObject, error) {
	rows, err := q.db.Query(ctx, listAuditObjectsInRange, arg.OrganizationID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditObject{}
	for rows.Next() {
		var i AuditObject
		if err := rows.Scan(
			&i.ObjectKey,
			&i.OrganizationID,
			&i.Day,
			&i.EventCount,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditOrganizations = `-- name: ListAuditOrganizations :many
SELECT organization_id FROM audit_object
UNION
SELECT organization_id FROM audit_manifest
ORDER BY organization_id
`

func (q *Queries) ListAuditOrganizations(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAuditOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var organization_id uuid.UUID
		if err := rows.Scan(&organization_id); err != nil {
			return nil, err
		}
		items = append(items, organization_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAuditSealLock = `-- name: ReleaseAuditSealLock :one
SELECT pg_advisory_unlock(hashtext('audit-seal')) AS unlocked
`

func (q *Queries) ReleaseAuditSealLock(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, releaseAuditSealLock)
	var unlocked bool
	err := row.Scan(&unlocked)
	return unlocked, err
}

const tryAuditSealLock = `-- name: TryAuditSealLock :one
SELECT pg_try_advisory_lock(hashtext('audit-seal')) AS locked
`

func (q *Queries) TryAuditSealLock(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tryAuditSealLock)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}
