// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditstore

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AuditEvent struct {
	EventID        uuid.UUID
	OrganizationID uuid.UUID
	OccurredAt     time.Time
	RecordedAt     time.Time
	Code           string
	Outcome        string
	Source         string
	Actor          json.RawMessage
	Target         json.RawMessage
	Params         json.RawMessage
	CorrelationID  string
	ObjectKey      string
}

type AuditManifest struct {
	OrganizationID uuid.UUID
	Day            time.Time
	Sha256         []byte
	PrevSha256     []byte
	Signature      string
	KeyVersion     int32
	ObjectKey      string
}

type AuditObject struct {
	ObjectKey      string
	OrganizationID uuid.UUID
	Day            time.Time
	EventCount     int32
	Sha256         []byte
	CreatedAt      time.Time
}
